# Generated by Django 5.2.6 on 2025-09-21 11:00

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.ticket_attachment_upload_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
