# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_category_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Formato: XX-XXX (ID Usuario-Secuencia)', max_length=10, verbose_name='Número de Ticket'),
        ),
    ]
