# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ticket_number'),
    ]

    operations = [
    ]
