# Generated by Django 5.2.6 on 2025-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de horas estimadas o trabajadas en el ticket', max_digits=6, null=True, verbose_name='Horas estimadas/trabajadas'),
        ),
    ]
