# Generated by Django 5.2.6 on 2025-09-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_public_shareable',
            field=models.BooleanField(default=False, help_text='Permite que este ticket sea visible mediante un enlace público', verbose_name='Compartir públicamente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para compartir el ticket públicamente', verbose_name='Token de compartir'),
        ),
    ]
