# Generated by Django 5.2.6 on 2025-09-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_populate_unique_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para compartir el ticket públicamente', unique=True, verbose_name='Token de compartir'),
        ),
    ]
