# Generated by Django 5.2.6 on 2025-09-21 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_add_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la nota', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Contenido detallado de la nota', verbose_name='Descripción')),
                ('is_private', models.BooleanField(default=True, help_text='Si está marcada, solo será visible para agentes', verbose_name='Nota privada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(help_text='Agente que creó la nota', on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tickets', models.ManyToManyField(blank=True, help_text='Tickets asociados a esta nota', related_name='notes', to='tickets.ticket', verbose_name='Tickets relacionados')),
                ('user', models.ForeignKey(help_text='Usuario al que está asociada esta nota', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Nota de Usuario',
                'verbose_name_plural': 'Notas de Usuario',
                'ordering': ['-created_at'],
            },
        ),
    ]
