# Generated by Django 4.2.20 on 2025-09-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0013_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(verbose_name='Fecha y hora de entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida')),
                ('notas', models.TextField(blank=True, help_text='Comentarios opcionales sobre la jornada', max_length=500, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Horario',
                'verbose_name_plural': 'Registros de Horario',
                'ordering': ['-fecha_entrada'],
                'unique_together': {('user', 'fecha_entrada')},
            },
        ),
    ]
