# Generated by Django 4.2.20 on 2025-09-21 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_project_timeentry_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la empresa', verbose_name='Descripción')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('color', models.CharField(default='#28a745', help_text='Color en formato hexadecimal (ej: #28a745)', max_length=7, verbose_name='Color identificativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Empresa activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa o cliente asociado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.company', verbose_name='Empresa/Cliente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.company', verbose_name='Empresa'),
        ),
    ]
