# Generated by Django 4.2.20 on 2025-09-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_company_ticket_company_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_user_registration', models.BooleanField(default=True, help_text='Permite que nuevos usuarios se registren en el sistema', verbose_name='Permitir registro de usuarios')),
                ('site_name', models.CharField(default='TicketPro', help_text='Nombre que aparece en el encabezado del sistema', max_length=100, verbose_name='Nombre del sitio')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enviar notificaciones por correo electrónico', verbose_name='Notificaciones por email')),
                ('default_ticket_priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad asignada automáticamente a nuevos tickets', max_length=20, verbose_name='Prioridad por defecto de tickets')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
