# Generated by Django 4.2.20 on 2025-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_systemconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='email_notifications_enabled',
        ),
    ]
