# Generated by Django 5.2.6 on 2025-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_remove_systemconfiguration_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coste_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Coste interno por hora de trabajo (€)', max_digits=10, verbose_name='Coste por hora'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta por hora de trabajo (€)', max_digits=10, verbose_name='Precio por hora'),
        ),
    ]
