# Generated by Django 4.2.20 on 2025-09-21 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0019_userprofile_coste_hora_userprofile_precio_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo del documento', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del contenido del documento', max_length=500, verbose_name='Descripción')),
                ('file', models.FileField(help_text='Archivo de documentación (PDF, DOC, DOCX, TXT, etc.)', upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('file_size', models.PositiveIntegerField(editable=False, verbose_name='Tamaño del archivo (bytes)')),
                ('file_type', models.CharField(editable=False, max_length=100, verbose_name='Tipo de archivo')),
                ('public_share_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para compartir el documento públicamente', unique=True, verbose_name='Token de compartir público')),
                ('is_public', models.BooleanField(default=True, help_text='Si está marcado, el documento puede ser accedido sin autenticación', verbose_name='Disponible públicamente')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Contador de veces que se ha descargado el documento', verbose_name='Número de descargas')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para categorizar el documento', max_length=300, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa o cliente asociado al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tickets.company', verbose_name='Empresa/Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
