# Generated by Django 4.2.20 on 2025-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo o posición del usuario en la empresa', max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='descripcion_cargo',
            field=models.TextField(blank=True, help_text='Descripción detallada de las responsabilidades del cargo', max_length=300, null=True, verbose_name='Descripción del Cargo'),
        ),
    ]
