# Generated by Django 5.2.6 on 2025-09-21 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_userprofile_cargo_userprofile_descripcion_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo para la URL', max_length=200, verbose_name='Título')),
                ('url', models.URLField(help_text='Dirección web completa (incluye http:// o https://)', max_length=500, verbose_name='URL')),
                ('username', models.CharField(help_text='Nombre de usuario para acceder', max_length=100, verbose_name='Usuario')),
                ('encrypted_password', models.TextField(help_text='Contraseña almacenada de forma segura', verbose_name='Contraseña encriptada')),
                ('description', models.TextField(blank=True, help_text='Información adicional sobre esta URL', null=True, verbose_name='Descripción')),
                ('category', models.CharField(blank=True, help_text='Ej: Servidor, Base de datos, Servicio web, etc.', max_length=100, null=True, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la URL está activa o no', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_urls', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Gestor de URL',
                'verbose_name_plural': 'Gestores de URLs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='tickets_url_categor_93bc17_idx'), models.Index(fields=['created_by', 'is_active'], name='tickets_url_created_b1aaff_idx')],
            },
        ),
    ]
