# Generated by Django 5.2.6 on 2025-09-21 19:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_urlmanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la orden de trabajo', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del trabajo a realizar', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('accepted', 'Aceptado'), ('finished', 'Terminado')], default='draft', help_text='Estado actual de la orden de trabajo', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateField(help_text='Fecha límite para completar la orden', verbose_name='Fecha de entrega')),
                ('is_public', models.BooleanField(default=False, help_text='Permite que esta orden sea visible públicamente', verbose_name='Publicar públicamente')),
                ('public_share_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para compartir la orden públicamente', unique=True, verbose_name='Token de compartir público')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado para completar la orden', max_digits=6, null=True, verbose_name='Horas estimadas')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario responsable de la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('company', models.ForeignKey(help_text='Empresa a la que se dirige la orden de trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'company'], name='tickets_wor_status_601655_idx'), models.Index(fields=['due_date', 'status'], name='tickets_wor_due_dat_812aa5_idx'), models.Index(fields=['created_by', 'status'], name='tickets_wor_created_4578e0_idx')],
            },
        ),
    ]
