# Generated by Django 4.2.20 on 2025-09-21 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0023_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha límite para completar la orden (opcional)', null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.work_order_attachment_upload_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Adjunto de Orden de Trabajo',
                'verbose_name_plural': 'Adjuntos de Órdenes de Trabajo',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
