# Generated by Django 4.2.20 on 2025-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_workorder_due_date_workorderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio o costo de la orden de trabajo', max_digits=10, null=True, verbose_name='Importe'),
        ),
    ]
