# Generated by Django 4.2.20 on 2025-09-23 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0025_workorder_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Título descriptivo de la tarea', max_length=200, verbose_name='Nombre de la tarea')),
                ('description', models.TextField(help_text='Descripción detallada de la tarea a realizar', verbose_name='Descripción')),
                ('due_date', models.DateTimeField(help_text='Fecha y hora límite para completar la tarea', verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado actual de la tarea', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado para completar la tarea', max_digits=6, null=True, verbose_name='Horas estimadas')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo real empleado en la tarea', max_digits=6, null=True, verbose_name='Horas reales')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Usuarios responsables de la tarea', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('project', models.ForeignKey(blank=True, help_text='Proyecto al que pertenece la tarea (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tickets.project', verbose_name='Proyecto asociado')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='tickets_tas_status_7142a2_idx'), models.Index(fields=['priority', 'status'], name='tickets_tas_priorit_85dd83_idx'), models.Index(fields=['created_by', 'status'], name='tickets_tas_created_0e7423_idx')],
            },
        ),
    ]
