# Generated by Django 4.2.20 on 2025-09-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_update_task_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
