# Generated by Django 4.2.20 on 2025-09-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket en el que se trabajará (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Orden de trabajo en la que se trabajará (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.workorder', verbose_name='Orden de Trabajo'),
        ),
    ]
