# Generated by Django 4.2.20 on 2025-09-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0031_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la sesión')),
                ('notes', models.TextField(blank=True, help_text='Notas generales sobre el plan del día', verbose_name='Notas del día')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión Diaria de Tareas',
                'verbose_name_plural': 'Sesiones Diarias de Tareas',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('notes', models.TextField(blank=True, help_text='Notas específicas sobre el trabajo en esta tarea', verbose_name='Notas específicas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_items', to='tickets.dailytasksession', verbose_name='Sesión diaria')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='tickets.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Item de Tarea Diaria',
                'verbose_name_plural': 'Items de Tareas Diarias',
                'ordering': ['order', 'task__priority'],
                'unique_together': {('session', 'task')},
            },
        ),
    ]
