# Generated by Django 4.2.20 on 2025-09-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_dailytasksession_dailytaskitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytasksession',
            options={'ordering': ['-created_at', '-date'], 'verbose_name': 'Gestión de Tareas', 'verbose_name_plural': 'Gestiones de Tareas'},
        ),
        migrations.AlterUniqueTogether(
            name='dailytasksession',
            unique_together=set(),
        ),
    ]
