# Generated by Django 4.2.20 on 2025-09-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_alter_dailytasksession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_token',
            field=models.UUIDField(blank=True, help_text='Token único para acceso público a tareas', null=True, verbose_name='Token público'),
        ),
    ]
