# Generated by Django 4.2.20 on 2025-09-23 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_userprofile_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token único para acceso público a tareas', unique=True, verbose_name='Token público'),
        ),
    ]
