# Generated by Django 4.2.20 on 2025-09-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_alter_userprofile_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Tarea en la que se trabajará (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.task', verbose_name='Tarea'),
        ),
    ]
