# Generated by Django 4.2.20 on 2025-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_timeentry_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_share_token',
            field=models.CharField(blank=True, help_text='Token único para compartir información del proyecto públicamente', max_length=64, null=True, unique=True, verbose_name='Token de Compartir Público'),
        ),
    ]
