# Generated by Django 4.2.20 on 2025-09-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_auto_20250923_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto asociado al ticket (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.project', verbose_name='Proyecto'),
        ),
    ]
