# Generated by Django 4.2.20 on 2025-09-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_ticket_project'),
    ]

    operations = [
    ]
