# Generated by Django 4.2.20 on 2025-09-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_auto_20250923_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto asociado a la orden de trabajo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='tickets.project', verbose_name='Proyecto'),
        ),
    ]
