# Generated by Django 4.2.20 on 2025-09-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_auto_20250923_1859'),
    ]

    operations = [
    ]
