# Generated by Django 4.2.20 on 2025-09-23 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0044_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que tienen acceso a este proyecto', related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Asignados'),
        ),
    ]
