# Generated by Django 4.2.20 on 2025-10-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0045_project_assigned_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del comando', max_length=200, verbose_name='Título')),
                ('command', models.TextField(help_text='El comando completo con sus parámetros', verbose_name='Comando')),
                ('description', models.TextField(help_text='Descripción detallada de lo que hace el comando', verbose_name='Descripción')),
                ('category', models.CharField(choices=[('linux', 'Linux/Unix'), ('windows', 'Windows'), ('docker', 'Docker'), ('git', 'Git'), ('python', 'Python'), ('javascript', 'JavaScript'), ('database', 'Base de Datos'), ('network', 'Redes'), ('security', 'Seguridad'), ('devops', 'DevOps'), ('web', 'Desarrollo Web'), ('mobile', 'Desarrollo Móvil'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Categoría')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para facilitar la búsqueda', max_length=500, verbose_name='Etiquetas')),
                ('example_usage', models.TextField(blank=True, help_text='Ejemplo práctico de cómo usar el comando', verbose_name='Ejemplo de uso')),
                ('notes', models.TextField(blank=True, help_text='Notas importantes, advertencias o tips', verbose_name='Notas adicionales')),
                ('is_dangerous', models.BooleanField(default=False, help_text='Marcar si el comando puede ser destructivo o peligroso', verbose_name='Comando peligroso')),
                ('is_favorite', models.BooleanField(default=False, help_text='Marcar como comando favorito', verbose_name='Favorito')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Contador de cuántas veces se ha copiado/usado este comando', verbose_name='Veces usado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'ordering': ['-is_favorite', '-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='tickets_com_categor_af5eb4_idx'), models.Index(fields=['is_favorite'], name='tickets_com_is_favo_15ef9c_idx'), models.Index(fields=['created_by'], name='tickets_com_created_a1cc4e_idx'), models.Index(fields=['title'], name='tickets_com_title_019642_idx')],
            },
        ),
    ]
