# Generated by Django 4.2.20 on 2025-10-06 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0046_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_public_contact_form',
            field=models.BooleanField(default=False, help_text='Permite que visitantes envíen formularios de contacto para crear empresas', verbose_name='Activar formulario de contacto público'),
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('message', models.TextField(blank=True, help_text='Información adicional sobre la empresa o servicios requeridos', verbose_name='Mensaje Adicional')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('company_created', 'Empresa Creada')], default='pending', max_length=20, verbose_name='Estado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas para el seguimiento de la solicitud', verbose_name='Notas del Administrador')),
                ('created_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.company', verbose_name='Empresa Creada')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_contact_forms', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('submitted_by_user', models.ForeignKey(help_text='Usuario que tiene activado el formulario de contacto', on_delete=django.db.models.deletion.CASCADE, related_name='contact_form_owner', to=settings.AUTH_USER_MODEL, verbose_name='Propietario del formulario')),
            ],
            options={
                'verbose_name': 'Formulario de Contacto',
                'verbose_name_plural': 'Formularios de Contacto',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_con_status_5364b5_idx'), models.Index(fields=['submitted_by_user'], name='tickets_con_submitt_7730bc_idx'), models.Index(fields=['submitted_at'], name='tickets_con_submitt_64c7b1_idx')],
            },
        ),
    ]
