# Generated by Django 4.2.20 on 2025-10-06 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_userprofile_enable_public_contact_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Token único para acceso público a estadísticas', null=True, verbose_name='Token público'),
        ),
    ]
