# Generated by Django 4.2.20 on 2025-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_company_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Token único para acceso público a estadísticas', null=True, verbose_name='Token público'),
        ),
    ]
