# Generated by Django 4.2.20 on 2025-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_alter_company_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa (opcional)', null=True, upload_to='company_logos/', verbose_name='Logo de la empresa'),
        ),
    ]
