# Generated by Django 4.2.20 on 2025-10-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0050_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Oportunidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Contacto Principal')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor estimado de la oportunidad', max_digits=12, verbose_name='Valor Estimado')),
                ('probability', models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=20, verbose_name='Probabilidad de Cierre (%)')),
                ('expected_close_date', models.DateField(verbose_name='Fecha Estimada de Cierre')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Cierre')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='Último Contacto')),
                ('next_follow_up', models.DateField(blank=True, null=True, verbose_name='Próximo Seguimiento')),
                ('source', models.CharField(blank=True, help_text='¿Cómo se originó esta oportunidad?', max_length=100, verbose_name='Fuente')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (ej: #007bff)', max_length=7, verbose_name='Color')),
                ('is_final', models.BooleanField(default=False, help_text='Indica si este estado representa el cierre de la oportunidad', verbose_name='Estado Final')),
                ('is_won', models.BooleanField(default=False, help_text='Indica si este estado representa una venta exitosa', verbose_name='Estado Ganado')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el pipeline', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Estado de Oportunidad',
                'verbose_name_plural': 'Estados de Oportunidad',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del cambio')),
                ('comment', models.TextField(blank=True, help_text='Razón del cambio de estado', verbose_name='Comentario')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_changes', to='tickets.opportunitystatus', verbose_name='Nuevo Estado')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.opportunity', verbose_name='Oportunidad')),
                ('previous_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_changes', to='tickets.opportunitystatus', verbose_name='Estado Anterior')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('is_important', models.BooleanField(default=False, help_text='Marcar como nota importante', verbose_name='Importante')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.opportunity', verbose_name='Oportunidad')),
            ],
            options={
                'verbose_name': 'Nota de Oportunidad',
                'verbose_name_plural': 'Notas de Oportunidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='tickets.opportunitystatus', verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status'], name='tickets_opp_status__f64e39_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['assigned_to'], name='tickets_opp_assigne_9ec48a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company'], name='tickets_opp_company_f0d2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='tickets_opp_expecte_4a3ef5_idx'),
        ),
    ]
