# Generated by Django 4.2.20 on 2025-10-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0051_opportunity_opportunitystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='salesperson',
            field=models.ForeignKey(help_text='Usuario responsable de la venta (por defecto quien crea la oportunidad)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
