# Generated by Django 4.2.20 on 2025-10-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_opportunity_salesperson'),
    ]

    operations = [
    ]
