# Generated by Django 4.2.20 on 2025-10-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_auto_20251006_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='salesperson',
        ),
    ]
