# Generated by Django 4.2.20 on 2025-10-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0054_auto_20251006_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DominoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la partida')),
                ('status', models.CharField(choices=[('waiting', 'Esperando jugadores'), ('in_progress', 'En progreso'), ('finished', 'Terminada'), ('cancelled', 'Cancelada')], default='waiting', max_length=20, verbose_name='Estado')),
                ('max_players', models.IntegerField(default=4, verbose_name='Máximo de jugadores')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminado el')),
                ('board_state', models.JSONField(default=list, verbose_name='Estado del tablero')),
                ('last_play', models.JSONField(blank=True, null=True, verbose_name='Última jugada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_domino_games', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_domino_games', to=settings.AUTH_USER_MODEL, verbose_name='Turno actual')),
            ],
            options={
                'verbose_name': 'Partida de Dominó',
                'verbose_name_plural': 'Partidas de Dominó',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='public_token',
            field=models.UUIDField(blank=True, help_text='Token único para acceso público a estadísticas', null=True, verbose_name='Token público'),
        ),
        migrations.CreateModel(
            name='DominoTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(verbose_name='Lado izquierdo')),
                ('right', models.IntegerField(verbose_name='Lado derecho')),
            ],
            options={
                'verbose_name': 'Ficha de Dominó',
                'verbose_name_plural': 'Fichas de Dominó',
                'unique_together': {('left', 'right')},
            },
        ),
        migrations.CreateModel(
            name='DominoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Se unió el')),
                ('turn_order', models.IntegerField(verbose_name='Orden de turno')),
                ('hand', models.JSONField(default=list, verbose_name='Fichas en mano')),
                ('has_passed', models.BooleanField(default=False, verbose_name='Ha pasado turno')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos acumulados')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.dominogame', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Jugador de Dominó',
                'verbose_name_plural': 'Jugadores de Dominó',
                'ordering': ['turn_order'],
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='DominoMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_left', models.IntegerField(verbose_name='Lado izquierdo de la ficha')),
                ('tile_right', models.IntegerField(verbose_name='Lado derecho de la ficha')),
                ('side_played', models.CharField(blank=True, choices=[('left', 'Izquierda'), ('right', 'Derecha')], max_length=10, null=True, verbose_name='Lado jugado')),
                ('is_pass', models.BooleanField(default=False, verbose_name='Pasó turno')),
                ('move_number', models.IntegerField(verbose_name='Número de movimiento')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Jugado el')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='tickets.dominogame', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Movimiento de Dominó',
                'verbose_name_plural': 'Movimientos de Dominó',
                'ordering': ['move_number'],
            },
        ),
        migrations.AddField(
            model_name='dominogame',
            name='players',
            field=models.ManyToManyField(related_name='domino_games', through='tickets.DominoPlayer', to=settings.AUTH_USER_MODEL, verbose_name='Jugadores'),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_domino_games', to=settings.AUTH_USER_MODEL, verbose_name='Ganador'),
        ),
    ]
