# Generated by Django 4.2.20 on 2025-10-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_dominogame_alter_company_public_token_dominotile_and_more'),
    ]

    operations = [
    ]
