# Generated by Django 4.2.20 on 2025-10-06 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0056_auto_20251007_0021'),
    ]

    operations = [
        # Eliminar las tablas existentes de dominó
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tickets_dominomove;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tickets_dominotile;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tickets_dominoplayer;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS tickets_dominogame;",
            reverse_sql="",
        ),
        
        # Recrear las tablas con la estructura correcta
        migrations.CreateModel(
            name='DominoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la partida')),
                ('status', models.CharField(choices=[('waiting', 'Esperando jugadores'), ('in_progress', 'En progreso'), ('finished', 'Terminada'), ('cancelled', 'Cancelada')], default='waiting', max_length=20, verbose_name='Estado')),
                ('max_players', models.IntegerField(default=4, verbose_name='Máximo de jugadores')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminado el')),
                ('board_state', models.JSONField(default=list, verbose_name='Estado del tablero')),
                ('last_play', models.JSONField(blank=True, null=True, verbose_name='Última jugada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_domino_games', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Partida de Dominó',
                'verbose_name_plural': 'Partidas de Dominó',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DominoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Se unió el')),
                ('score', models.IntegerField(default=0, verbose_name='Puntuación')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última vez visto')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.dominogame', verbose_name='Partida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Jugador de Dominó',
                'verbose_name_plural': 'Jugadores de Dominó',
            },
        ),
        migrations.CreateModel(
            name='DominoTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(verbose_name='Lado izquierdo')),
                ('right', models.IntegerField(verbose_name='Lado derecho')),
                ('is_played', models.BooleanField(default=False, verbose_name='¿Jugada?')),
                ('position_on_board', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posición en tablero')),
                ('played_at', models.DateTimeField(blank=True, null=True, verbose_name='Jugada el')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.dominogame', verbose_name='Partida')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.dominoplayer', verbose_name='Jugador actual')),
            ],
            options={
                'verbose_name': 'Ficha de Dominó',
                'verbose_name_plural': 'Fichas de Dominó',
            },
        ),
        migrations.CreateModel(
            name='DominoMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, verbose_name='Posición')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Movimiento realizado el')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.dominogame', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.dominoplayer', verbose_name='Jugador')),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.dominotile', verbose_name='Ficha jugada')),
            ],
            options={
                'verbose_name': 'Movimiento de Dominó',
                'verbose_name_plural': 'Movimientos de Dominó',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dominogame',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_games', to='tickets.dominoplayer', verbose_name='Turno actual'),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='players',
            field=models.ManyToManyField(related_name='domino_games', through='tickets.DominoPlayer', to=settings.AUTH_USER_MODEL, verbose_name='Jugadores'),
        ),
        migrations.AddField(
            model_name='dominogame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='tickets.dominoplayer', verbose_name='Ganador'),
        ),
        migrations.AlterUniqueTogether(
            name='dominoplayer',
            unique_together={('game', 'user')},
        ),
    ]
