# Generated by Django 4.2.20 on 2025-10-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0057_auto_20251007_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominoplayer',
            name='final_score',
            field=models.IntegerField(default=0, verbose_name='Puntuación Final'),
        ),
    ]
