# Generated by Django 4.2.20 on 2025-10-06 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0058_dominoplayer_final_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la reunión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duration', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('public_token', models.CharField(max_length=100, unique=True, verbose_name='Token público')),
                ('allow_questions', models.BooleanField(default=True, verbose_name='Permitir preguntas')),
                ('require_email', models.BooleanField(default=False, verbose_name='Requerir email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'ordering': ['registered_at'],
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.CreateModel(
            name='MeetingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('answer', models.TextField(blank=True, verbose_name='Respuesta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('answered', 'Respondida'), ('ignored', 'Ignorada')], default='pending', max_length=20, verbose_name='Estado')),
                ('asker_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del preguntante')),
                ('asker_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del preguntante')),
                ('asked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Preguntado el')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.meetingattendee', verbose_name='Asistente')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Pregunta de reunión',
                'verbose_name_plural': 'Preguntas de reuniones',
                'ordering': ['asked_at'],
            },
        ),
        migrations.RemoveField(
            model_name='dominomove',
            name='game',
        ),
        migrations.RemoveField(
            model_name='dominomove',
            name='player',
        ),
        migrations.RemoveField(
            model_name='dominomove',
            name='tile',
        ),
        migrations.AlterUniqueTogether(
            name='dominoplayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dominoplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='dominoplayer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dominotile',
            name='game',
        ),
        migrations.RemoveField(
            model_name='dominotile',
            name='player',
        ),
        migrations.DeleteModel(
            name='DominoGame',
        ),
        migrations.DeleteModel(
            name='DominoMove',
        ),
        migrations.DeleteModel(
            name='DominoPlayer',
        ),
        migrations.DeleteModel(
            name='DominoTile',
        ),
    ]
