# Generated by Django 4.2.20 on 2025-10-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0059_meeting_meetingattendee_meetingquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa relacionada con la reunión (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.company', verbose_name='Empresa'),
        ),
    ]
