# Generated by Django 4.2.20 on 2025-10-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0060_add_company_to_meeting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingattendee',
            unique_together=set(),
        ),
    ]
