# Generated by Django 4.2.20 on 2025-10-07 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0061_remove_unique_meeting_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Actividad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('activity_type', models.CharField(choices=[('call', 'Llamada'), ('meeting', 'Reunión'), ('email', 'Correo Electrónico'), ('task', 'Tarea'), ('demo', 'Demostración'), ('proposal', 'Propuesta'), ('follow_up', 'Seguimiento'), ('other', 'Otro')], default='task', max_length=20, verbose_name='Tipo de Actividad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('overdue', 'Vencida')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('scheduled_date', models.DateTimeField(help_text='Fecha y hora cuando debe realizarse la actividad', verbose_name='Fecha Programada')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('result', models.TextField(blank=True, help_text='Resultado o notas de la actividad completada', verbose_name='Resultado')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duración estimada o real de la actividad', null=True, verbose_name='Duración (minutos)')),
                ('location', models.CharField(blank=True, help_text='Lugar donde se realizará la actividad', max_length=200, verbose_name='Ubicación')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.opportunity', verbose_name='Oportunidad')),
            ],
            options={
                'verbose_name': 'Actividad de Oportunidad',
                'verbose_name_plural': 'Actividades de Oportunidades',
                'ordering': ['scheduled_date', '-priority'],
                'indexes': [models.Index(fields=['status'], name='tickets_opp_status_0e4bf1_idx'), models.Index(fields=['assigned_to'], name='tickets_opp_assigne_2a67b8_idx'), models.Index(fields=['scheduled_date'], name='tickets_opp_schedul_b790b6_idx'), models.Index(fields=['activity_type'], name='tickets_opp_activit_3b20aa_idx'), models.Index(fields=['priority'], name='tickets_opp_priorit_c1d415_idx')],
            },
        ),
    ]
