# Generated by Django 4.2.20 on 2025-10-07 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0063_course_courseclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Visto el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tickets.courseclass', verbose_name='Clase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Visualización de Clase',
                'verbose_name_plural': 'Visualizaciones de Clases',
                'ordering': ['-viewed_at'],
                'unique_together': {('course_class', 'user')},
            },
        ),
    ]
