# Generated by Django 4.2.20 on 2025-10-07 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_courseclassview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona una empresa, solo los usuarios de esa empresa podrán ver este curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa'),
        ),
    ]
