# Generated by Django 4.2.20 on 2025-10-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_course_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public_enabled',
            field=models.BooleanField(default=False, help_text='Permite que el curso sea accesible públicamente mediante un enlace', verbose_name='Acceso público habilitado'),
        ),
        migrations.AddField(
            model_name='course',
            name='public_token',
            field=models.UUIDField(blank=True, help_text='Token para acceso público al curso sin autenticación', null=True, verbose_name='Token público'),
        ),
    ]
