# Generated by Django 4.2.20 on 2025-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0066_course_is_public_enabled_course_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar Americano ($)'), ('GBP', 'Libra Esterlina (£)'), ('JPY', 'Yen Japonés (¥)'), ('CAD', 'Dólar Canadiense (C$)'), ('AUD', 'Dólar Australiano (A$)'), ('CHF', 'Franco Suizo (CHF)'), ('CNY', 'Yuan Chino (¥)'), ('MXN', 'Peso Mexicano ($)'), ('COP', 'Peso Colombiano ($)')], default='EUR', help_text='Moneda utilizada para mostrar valores en el sistema', max_length=10, verbose_name='Moneda por defecto'),
        ),
    ]
