# Generated by Django 4.2.20 on 2025-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_add_currency_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='contact_position',
            field=models.CharField(blank=True, help_text='Posición o cargo del contacto en la empresa', max_length=100, verbose_name='Cargo del Contacto'),
        ),
    ]
