# Generated by Django 4.2.20 on 2025-10-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0068_add_contact_position_to_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('status', models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo')], default='positive', max_length=10, verbose_name='Estado')),
                ('source', models.CharField(blank=True, help_text='¿De dónde obtuviste este contacto?', max_length=200, null=True, verbose_name='Fuente')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el contacto', null=True, verbose_name='Notas')),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Contacto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-contact_date'],
            },
        ),
    ]
