# Generated by Django 4.2.20 on 2025-10-07 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0070_add_blog_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que fue aprobado el ticket', null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó el ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indica si el ticket ha sido aprobado por el cliente', verbose_name='Aprobado'),
        ),
    ]
