# Generated by Django 4.2.20 on 2025-10-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0071_add_ticket_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('development', 'Desarrollo'), ('bug', 'Error')], default='development', max_length=15, verbose_name='Tipo'),
        ),
    ]
