# Generated by Django 4.2.20 on 2025-10-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_add_ticket_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('desarrollo', 'Desarrollo'), ('error', 'Error')], default='desarrollo', max_length=15, verbose_name='Tipo'),
        ),
    ]
