# Generated by Django 4.2.20 on 2025-10-07 20:24

from django.db import migrations


def convert_ticket_types_forward(apps, schema_editor):
    """Convertir valores de ticket_type de inglés a español"""
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Convertir 'development' a 'desarrollo'
    Ticket.objects.filter(ticket_type='development').update(ticket_type='desarrollo')
    
    # Convertir 'bug' a 'error'
    Ticket.objects.filter(ticket_type='bug').update(ticket_type='error')


def convert_ticket_types_reverse(apps, schema_editor):
    """Revertir valores de ticket_type de español a inglés"""
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Convertir 'desarrollo' a 'development'
    Ticket.objects.filter(ticket_type='desarrollo').update(ticket_type='development')
    
    # Convertir 'error' a 'bug'
    Ticket.objects.filter(ticket_type='error').update(ticket_type='bug')


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0073_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.RunPython(
            convert_ticket_types_forward,
            convert_ticket_types_reverse
        ),
    ]