# Generated by Django 4.2.20 on 2025-10-07 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0074_convert_ticket_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='ai_chat_enabled',
            field=models.BooleanField(default=False, help_text='Habilita o deshabilita la funcionalidad de chat con IA', verbose_name='Chat IA habilitado'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Clave de API para conectar con ChatGPT', max_length=200, verbose_name='API Key de OpenAI'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='openai_model',
            field=models.CharField(default='gpt-4o', help_text='Modelo de IA a utilizar por defecto (ej: gpt-4o, gpt-3.5-turbo)', max_length=50, verbose_name='Modelo de OpenAI'),
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la conversación', max_length=200, verbose_name='Título de la conversación')),
                ('ai_model', models.CharField(default='gpt-4o', help_text='Modelo utilizado para esta conversación', max_length=50, verbose_name='Modelo de IA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Chat IA',
                'verbose_name_plural': 'Sesiones de Chat IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'IA'), ('system', 'Sistema')], max_length=10, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido del mensaje')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Número de tokens consumidos para este mensaje', verbose_name='Tokens utilizados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.aichatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat IA',
                'verbose_name_plural': 'Mensajes de Chat IA',
                'ordering': ['created_at'],
            },
        ),
    ]
