# Generated by Django 4.2.20 on 2025-10-07 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0075_systemconfiguration_ai_chat_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industria')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de extracción')),
                ('created_company', models.ForeignKey(blank=True, help_text='Referencia a la empresa creada en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.company', verbose_name='Empresa creada')),
            ],
            options={
                'verbose_name': 'Empresa Extraída',
                'verbose_name_plural': 'Empresas Extraídas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL de la página web para extraer empresas y contactos', verbose_name='URL a analizar')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título de la tarea')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la tarea', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('companies_found', models.PositiveIntegerField(default=0, verbose_name='Empresas encontradas')),
                ('contacts_found', models.PositiveIntegerField(default=0, verbose_name='Contactos encontrados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Datos JSON extraídos de la página web', verbose_name='Datos extraídos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea de Scraping Web',
                'verbose_name_plural': 'Tareas de Scraping Web',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de extracción')),
                ('created_contact', models.ForeignKey(blank=True, help_text='Referencia al contacto creado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.contact', verbose_name='Contacto creado')),
                ('scraped_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tickets.scrapedcompany', verbose_name='Empresa extraída')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_contacts', to='tickets.webscrapingtask', verbose_name='Tarea de scraping')),
            ],
            options={
                'verbose_name': 'Contacto Extraído',
                'verbose_name_plural': 'Contactos Extraídos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scrapedcompany',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_companies', to='tickets.webscrapingtask', verbose_name='Tarea de scraping'),
        ),
    ]
