# Generated by Django 4.2.20 on 2025-10-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0076_scrapedcompany_webscrapingtask_scrapedcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscrapingtask',
            name='crawled_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs que fueron analizadas durante el crawling', verbose_name='URLs analizadas'),
        ),
        migrations.AddField(
            model_name='webscrapingtask',
            name='pages_crawled',
            field=models.PositiveIntegerField(default=0, verbose_name='Páginas analizadas'),
        ),
    ]
