# Generated by Django 4.2.20 on 2025-10-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0077_webscrapingtask_crawled_urls_and_more'),
    ]

    operations = [
    ]
