# Generated by Django 4.2.20 on 2025-10-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0078_auto_20251008_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscrapingtask',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea de Celery para seguimiento en tiempo real', max_length=255, null=True, verbose_name='ID de tarea Celery'),
        ),
    ]
