# Generated by Django 4.2.20 on 2025-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0079_webscrapingtask_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcompany',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='scrapedcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='scrapedcontact',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
    ]
