# Generated by Django 4.2.20 on 2025-10-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0080_alter_scrapedcompany_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedcontact',
            name='created_contact',
        ),
        migrations.RemoveField(
            model_name='scrapedcontact',
            name='scraped_company',
        ),
        migrations.RemoveField(
            model_name='scrapedcontact',
            name='task',
        ),
        migrations.RemoveField(
            model_name='webscrapingtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScrapedCompany',
        ),
        migrations.DeleteModel(
            name='ScrapedContact',
        ),
        migrations.DeleteModel(
            name='WebScrapingTask',
        ),
    ]
