# Generated by Django 4.2.20 on 2025-10-07 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0081_remove_scrapedcontact_created_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='El concepto o término a definir', max_length=200, unique=True, verbose_name='Término')),
                ('definition', models.TextField(help_text='Explicación del concepto', verbose_name='Definición')),
                ('category', models.CharField(blank=True, help_text='Categoría del concepto (opcional)', max_length=100, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, help_text='Si el concepto debe mostrarse en el home', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['order', 'term'],
            },
        ),
    ]
