# Generated by Django 4.2.20 on 2025-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0082_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, help_text='Token único para autenticación en la API REST', max_length=64, null=True, unique=True, verbose_name='Token de API'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_api_access',
            field=models.BooleanField(default=False, help_text='Permite acceso a tickets via API REST usando token de autenticación', verbose_name='Activar acceso API REST'),
        ),
    ]
