# Generated by Django 4.2.20 on 2025-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0083_userprofile_api_token_userprofile_enable_api_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_api_access',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_telegram_notifications',
            field=models.BooleanField(default=False, help_text='Envía notificaciones a un grupo de Telegram cuando se crean tickets', verbose_name='Activar notificaciones de Telegram'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Token del bot de Telegram proporcionado por @BotFather', max_length=200, null=True, verbose_name='Token del Bot de Telegram'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del grupo o chat donde enviar las notificaciones (ej: -100123456789)', max_length=100, null=True, verbose_name='ID del Chat/Grupo de Telegram'),
        ),
    ]
