# Generated by Django 4.2.20 on 2025-10-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0084_remove_userprofile_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Examen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='¿Es público?')),
                ('public_token', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Token público')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Puntuación mínima para aprobar (%)')),
                ('time_limit', models.IntegerField(blank=True, help_text='Dejar vacío para sin límite de tiempo', null=True, verbose_name='Tiempo límite (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Pregunta')),
                ('option_a', models.CharField(max_length=500, verbose_name='Opción A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Opción B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Opción C')),
                ('correct_option', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C')], max_length=1, verbose_name='Opción correcta')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Pregunta del Examen',
                'verbose_name_plural': 'Preguntas del Examen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=200, verbose_name='Nombre del participante')),
                ('participant_email', models.EmailField(max_length=254, verbose_name='Email del participante')),
                ('score', models.FloatField(verbose_name='Puntuación (%)')),
                ('total_questions', models.IntegerField(verbose_name='Total de preguntas')),
                ('correct_answers', models.IntegerField(verbose_name='Respuestas correctas')),
                ('started_at', models.DateTimeField(verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completado en')),
                ('time_taken', models.IntegerField(verbose_name='Tiempo tomado (segundos)')),
                ('passed', models.BooleanField(default=False, verbose_name='¿Aprobado?')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tickets.exam', verbose_name='Examen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Examen',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C')], max_length=1, verbose_name='Opción seleccionada')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.examattempt', verbose_name='Intento')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.examquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta del Examen',
                'verbose_name_plural': 'Respuestas del Examen',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
