# Generated by Django 4.2.20 on 2025-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0085_exam_examquestion_examattempt_examanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='certificate_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado generado en'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='certificate_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token del certificado'),
        ),
    ]
