# Generated by Django 4.2.20 on 2025-10-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0087_contactoweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para la URL pública de subida', unique=True, verbose_name='Token de subida')),
                ('title', models.CharField(help_text='Descripción de qué tipo de documentos se esperan', max_length=200, verbose_name='Título de la subida')),
                ('description', models.TextField(blank=True, help_text='Instrucciones para quien vaya a subir el documento', verbose_name='Instrucciones')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Opcional: fecha límite para usar esta URL', null=True, verbose_name='Fecha de expiración')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivada, no se pueden subir más documentos', verbose_name='Activa')),
                ('max_uploads', models.PositiveIntegerField(blank=True, help_text='Opcional: límite de documentos que se pueden subir', null=True, verbose_name='Máximo de subidas')),
                ('upload_count', models.PositiveIntegerField(default=0, help_text='Contador de documentos subidos usando esta URL', verbose_name='Documentos subidos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa o cliente para el cual se subirán los documentos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_upload_urls', to='tickets.company', verbose_name='Empresa/Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_upload_urls', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'URL Pública de Subida',
                'verbose_name_plural': 'URLs Públicas de Subida',
                'ordering': ['-created_at'],
            },
        ),
    ]
