# Generated by Django 4.2.20 on 2025-10-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0088_publicdocumentupload'),
    ]

    operations = [
    ]
