# Generated by Django 4.2.20 on 2025-10-09 10:41

from django.db import migrations


def create_teacher_group(apps, schema_editor):
    """Crear el grupo de Profesores"""
    Group = apps.get_model('auth', 'Group')
    
    # Crear el grupo de Profesores si no existe
    teacher_group, created = Group.objects.get_or_create(name='Profesores')
    
    if created:
        print("Grupo 'Profesores' creado exitosamente")
    else:
        print("Grupo 'Profesores' ya existe")


def reverse_create_teacher_group(apps, schema_editor):
    """Eliminar el grupo de Profesores"""
    Group = apps.get_model('auth', 'Group')
    
    try:
        teacher_group = Group.objects.get(name='Profesores')
        teacher_group.delete()
        print("Grupo 'Profesores' eliminado")
    except Group.DoesNotExist:
        print("Grupo 'Profesores' no existe")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0089_auto_20251009_1241'),
    ]

    operations = [
        migrations.RunPython(create_teacher_group, reverse_create_teacher_group),
    ]
