# Generated by Django 4.2.20 on 2025-10-09 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0090_auto_20251009_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Dejar vacío para que no expire', null=True, verbose_name='Fecha de expiración')),
                ('max_registrations', models.PositiveIntegerField(blank=True, help_text='Número máximo de usuarios que pueden registrarse con este token', null=True, verbose_name='Máximo de registros')),
                ('registration_count', models.PositiveIntegerField(default=0, verbose_name='Registros realizados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='tickets.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Token de Registro de Curso',
                'verbose_name_plural': 'Tokens de Registro de Curso',
                'ordering': ['-created_at'],
            },
        ),
    ]
