# Generated by Django 4.2.20 on 2025-10-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0091_courseregistrationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de aplicación')),
                ('job_title', models.CharField(max_length=150, verbose_name='Título del puesto')),
                ('job_description', models.TextField(verbose_name='Descripción del puesto')),
                ('proposed_salary_euros', models.DecimalField(blank=True, decimal_places=2, help_text='Salario que la empresa está dispuesta a pagar', max_digits=10, null=True, verbose_name='Salario propuesto (EUR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('max_applications', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de aplicaciones')),
                ('application_count', models.PositiveIntegerField(default=0, verbose_name='Aplicaciones recibidas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_tokens', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Token de Aplicación de Empleo',
                'verbose_name_plural': 'Tokens de Aplicación de Empleo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(max_length=150, verbose_name='Cargo')),
                ('salary_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario (EUR)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción/Experiencia')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Archivo de currículo')),
                ('ai_analysis', models.TextField(blank=True, help_text='Resumen automático generado por IA', verbose_name='Análisis de IA')),
                ('ai_score', models.PositiveIntegerField(blank=True, help_text='Puntuación automática del candidato', null=True, verbose_name='Puntuación IA (1-10)')),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('interview', 'En entrevista'), ('hired', 'Contratado'), ('rejected', 'Rechazado')], default='applied', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aplicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-created_at'],
            },
        ),
    ]
