# Generated by Django 4.2.20 on 2025-10-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0092_jobapplicationtoken_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='ai_employee_analysis_prompt',
            field=models.TextField(default='Analiza el siguiente perfil de candidato y dame un resumen profesional y una puntuación del 1 al 10 para el cargo solicitado. Considera experiencia, formación, habilidades y adecuación al puesto.\n\nDatos del candidato:\n{datos}\n\nPor favor, responde en este formato:\nResumen: [Aquí tu análisis profesional del candidato]\nPuntuación: [Número del 1 al 10]', help_text='Plantilla del prompt que se enviará a la IA para analizar candidatos. Usa {datos} donde se insertarán los datos del candidato.', verbose_name='Prompt para análisis de empleados'),
        ),
    ]
