# Generated by Django 4.2.20 on 2025-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0093_systemconfiguration_ai_employee_analysis_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('in_process', 'En trámites'), ('employee', 'Empleado'), ('not_employee', 'No empleado')], default='candidate', max_length=20, verbose_name='Estado'),
        ),
    ]
