# Generated by Django 4.2.20 on 2025-10-09 12:15

from django.db import migrations


def migrate_employee_status(apps, schema_editor):
    """Mapear estados antiguos a nuevos"""
    Employee = apps.get_model('tickets', 'Employee')
    
    # Mapeo de estados antiguos a nuevos
    status_mapping = {
        'applied': 'candidate',      # Aplicado -> Candidato
        'interview': 'in_process',   # En entrevista -> En trámites
        'hired': 'employee',         # Contratado -> Empleado
        'rejected': 'not_employee',  # Rechazado -> No empleado
    }
    
    for employee in Employee.objects.all():
        old_status = employee.status
        if old_status in status_mapping:
            employee.status = status_mapping[old_status]
            employee.save()


def reverse_migrate_employee_status(apps, schema_editor):
    """Revertir mapeo de estados"""
    Employee = apps.get_model('tickets', 'Employee')
    
    # Mapeo inverso
    reverse_status_mapping = {
        'candidate': 'applied',
        'in_process': 'interview',
        'employee': 'hired',
        'not_employee': 'rejected',
    }
    
    for employee in Employee.objects.all():
        new_status = employee.status
        if new_status in reverse_status_mapping:
            employee.status = reverse_status_mapping[new_status]
            employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0094_alter_employee_status'),
    ]

    operations = [
        migrations.RunPython(migrate_employee_status, reverse_migrate_employee_status),
    ]
