# Generated by Django 4.2.20 on 2025-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0095_auto_20251009_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiring_meeting_opinion',
            field=models.TextField(blank=True, help_text='Comentarios y evaluación de la reunión/entrevista de contratación', verbose_name='Opinión de reunión de contratación'),
        ),
    ]
