# Generated by Django 4.2.20 on 2025-10-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0096_employee_hiring_meeting_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField(help_text='Mes de la nómina (1-12)', verbose_name='Mes')),
                ('period_year', models.PositiveIntegerField(help_text='Año de la nómina', verbose_name='Año')),
                ('payroll_pdf', models.FileField(help_text='Archivo PDF de la nómina', upload_to='payrolls/', verbose_name='Nómina (PDF)')),
                ('payment_receipt', models.FileField(blank=True, help_text='Archivo del comprobante de pago (opcional)', null=True, upload_to='payment_receipts/', verbose_name='Comprobante de pago')),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario bruto')),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario neto')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre esta nómina', verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='tickets.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Nómina de Empleado',
                'verbose_name_plural': 'Nóminas de Empleados',
                'ordering': ['-period_year', '-period_month', '-created_at'],
                'unique_together': {('employee', 'period_month', 'period_year')},
            },
        ),
    ]
