# Generated by Django 4.2.20 on 2025-10-09 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0097_employeepayroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Acuerdo')),
                ('body', models.TextField(help_text='Contenido completo del acuerdo/contrato', verbose_name='Cuerpo del Acuerdo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('signed', 'Firmado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('public_token', models.CharField(max_length=100, unique=True, verbose_name='Token Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('max_signers', models.PositiveIntegerField(default=10, help_text='Número máximo de personas que pueden firmar este acuerdo', verbose_name='Máximo de firmantes')),
                ('requires_approval', models.BooleanField(default=False, help_text='Las firmas requieren aprobación antes de ser válidas', verbose_name='Requiere aprobación')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Acuerdo',
                'verbose_name_plural': 'Acuerdos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200, verbose_name='Nombre del firmante')),
                ('signer_email', models.EmailField(max_length=254, verbose_name='Email del firmante')),
                ('signature_data', models.TextField(help_text='Datos de la firma digital (base64)', verbose_name='Datos de la firma')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de firma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Firma válida')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Firma aprobada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('pdf_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF descargado en')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Veces descargado')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='tickets.agreement', verbose_name='Acuerdo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
            ],
            options={
                'verbose_name': 'Firma de Acuerdo',
                'verbose_name_plural': 'Firmas de Acuerdos',
                'ordering': ['-signed_at'],
                'unique_together': {('agreement', 'signer_email')},
            },
        ),
    ]
