# Generated by Django 4.2.20 on 2025-10-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0098_agreement_agreementsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Dirección de email que aparecerá como remitente', max_length=254, verbose_name='Email remitente'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='Servidor de correo saliente (ej: smtp.gmail.com, mail.tu-dominio.com)', max_length=255, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Contraseña o token de aplicación para SMTP', max_length=255, verbose_name='Contraseña SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Dirección de email para autenticación SMTP', max_length=254, verbose_name='Usuario SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, help_text='Puerto del servidor SMTP (587 para TLS, 465 para SSL, 25 para sin cifrado)', null=True, verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Activar cifrado SSL (para puerto 465)', verbose_name='Usar SSL'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Activar cifrado TLS (recomendado para puerto 587)', verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_email_notifications',
            field=models.BooleanField(default=False, help_text='Envía notificaciones por email cuando se reciben contactos desde la web', verbose_name='Activar notificaciones por email'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Direcciones de email donde enviar notificaciones (una por línea)', verbose_name='Emails de notificación'),
        ),
    ]
