# Generated by Django 4.2.20 on 2025-10-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0099_systemconfiguration_email_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(help_text='Descripción que aparecerá en la landing page', verbose_name='Descripción del Producto')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal de la landing page', null=True, upload_to='landing_pages/', verbose_name='Imagen del Producto')),
                ('slug', models.SlugField(help_text='URL única para acceder a la landing page (ej: mi-producto)', max_length=200, unique=True, verbose_name='URL de la Landing Page')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, la landing page será accesible públicamente', verbose_name='Página Activa')),
                ('color_principal', models.CharField(default='#00A651', help_text='Color principal de la landing page (formato HEX: #00A651)', max_length=7, verbose_name='Color Principal')),
                ('color_secundario', models.CharField(default='#E8F5E8', help_text='Color secundario para fondos (formato HEX: #E8F5E8)', max_length=7, verbose_name='Color Secundario')),
                ('titulo_formulario', models.CharField(default='VEA TODAS LAS DEMOSTRACIONES', max_length=200, verbose_name='Título del Formulario')),
                ('subtitulo_formulario', models.TextField(default='Salesforce acerca a las empresas con sus clientes. Vea nuestras demostraciones gratuitas y obtenga más información sobre cómo podemos ayudar a su negocio.', verbose_name='Subtítulo del Formulario')),
                ('empresa_campana', models.CharField(blank=True, help_text='Nombre de la empresa que ejecuta la campaña', max_length=200, verbose_name='Empresa de la Campaña')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de visitas')),
                ('submissions_count', models.PositiveIntegerField(default=0, verbose_name='Formularios enviados')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tickets.landingpage', verbose_name='Landing Page')),
            ],
            options={
                'verbose_name': 'Envío de Landing Page',
                'verbose_name_plural': 'Envíos de Landing Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
