# Generated by Django 4.2.20 on 2025-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0100_landingpage_landingpagesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Cuéntanos más sobre tus necesidades o proyecto', verbose_name='Mensaje o comentarios'),
        ),
    ]
