# Generated by Django 4.2.20 on 2025-10-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0101_landingpagesubmission_mensaje'),
    ]

    operations = [
    ]
