# Generated by Django 4.2.20 on 2025-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0102_auto_20251010_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Token del bot de Telegram para enviar notificaciones (ej: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz)', max_length=200, verbose_name='Bot Token de Telegram'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat o canal donde enviar las notificaciones (ej: -1001234567890 o @mi_canal)', max_length=200, verbose_name='Chat ID de Telegram'),
        ),
    ]
