# Generated by Django 4.2.20 on 2025-10-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0103_landingpage_telegram_bot_token_and_more'),
    ]

    operations = [
    ]
