# Generated by Django 4.2.20 on 2025-10-10 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0104_auto_20251010_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la tarea (opcional)', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la tarea', verbose_name='Orden')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado para completar la tarea', max_digits=6, null=True, verbose_name='Horas Estimadas')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo real trabajado en la tarea', max_digits=6, verbose_name='Horas Reales')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tickets.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Tarea de Orden de Trabajo',
                'verbose_name_plural': 'Tareas de Órdenes de Trabajo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTaskTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas Trabajadas')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del trabajo realizado', verbose_name='Descripción del Trabajo')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado en')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tickets.workordertask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Registro de Tiempo de Tarea',
                'verbose_name_plural': 'Registros de Tiempo de Tareas',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['task', 'date'], name='tickets_wor_task_id_24de67_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['work_order', 'status'], name='tickets_wor_work_or_a46bca_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertask',
            index=models.Index(fields=['work_order', 'order'], name='tickets_wor_work_or_790b7c_idx'),
        ),
    ]
