# Generated by Django 4.2.20 on 2025-10-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0105_workordertask_workordertasktimeentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_company_score',
            field=models.IntegerField(blank=True, help_text='Evaluación de la calidad/seriedad de la empresa', null=True, verbose_name='Puntuación Empresa (1-10)'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_contact_score',
            field=models.IntegerField(blank=True, help_text='Evaluación de la calidad del contacto', null=True, verbose_name='Puntuación Contacto (1-10)'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_evaluated',
            field=models.BooleanField(default=False, verbose_name='Evaluado por IA'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_evaluation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de evaluación IA'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_evaluation_summary',
            field=models.TextField(blank=True, help_text='Resumen detallado de la evaluación', verbose_name='Resumen de Evaluación IA'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_overall_score',
            field=models.FloatField(blank=True, help_text='Puntuación promedio general', null=True, verbose_name='Puntuación General'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_priority_level',
            field=models.CharField(blank=True, choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], max_length=20, verbose_name='Nivel de Prioridad IA'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_project_score',
            field=models.IntegerField(blank=True, help_text='Evaluación del potencial del proyecto', null=True, verbose_name='Puntuación Proyecto (1-10)'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='ai_recommendations',
            field=models.TextField(blank=True, help_text='Recomendaciones de seguimiento', verbose_name='Recomendaciones IA'),
        ),
    ]
