# Generated by Django 4.2.20 on 2025-10-11 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0106_landingpagesubmission_ai_company_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTaskTimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del trabajo realizado')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='tickets.workordertask', verbose_name='Tarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Tiempo de Tarea',
                'verbose_name_plural': 'Sesiones de Tiempo de Tareas',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['task', 'is_active'], name='tickets_wor_task_id_191efe_idx'), models.Index(fields=['user', 'is_active'], name='tickets_wor_user_id_28e74e_idx')],
            },
        ),
    ]
