# Generated by Django 4.2.20 on 2025-10-11 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0108_auto_20251011_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertasktimesession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que inició la sesión (puede ser vacío para sesiones públicas)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
