# Generated by Django 4.2.20 on 2025-10-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0109_alter_workordertasktimesession_user'),
    ]

    operations = [
    ]
