# Generated by Django 4.2.20 on 2025-10-11 18:38

from django.db import migrations
from decimal import Decimal
from django.utils import timezone


def add_time_to_completed_tasks(apps, schema_editor):
    """
    Agregar tiempo automático a tareas completadas que no tienen tiempo registrado
    """
    WorkOrderTask = apps.get_model('tickets', 'WorkOrderTask')
    WorkOrderTaskTimeEntry = apps.get_model('tickets', 'WorkOrderTaskTimeEntry')
    
    # Encontrar tareas completadas sin tiempo registrado
    completed_tasks = WorkOrderTask.objects.filter(
        status='completed',
        actual_hours__isnull=True
    ).exclude(
        time_entries__isnull=False
    )
    
    for task in completed_tasks:
        # Si tiene started_at y completed_at, calcular la duración
        if task.started_at and task.completed_at:
            duration = task.completed_at - task.started_at
            hours = Decimal(str(duration.total_seconds() / 3600))
            
            # Crear entrada de tiempo automática
            WorkOrderTaskTimeEntry.objects.create(
                task=task,
                hours=round(hours, 2),
                description="Tiempo automático calculado - migración de datos",
                date=task.completed_at.date()
            )
            
            # Actualizar actual_hours de la tarea
            task.actual_hours = round(hours, 2)
            task.save(update_fields=['actual_hours'])
            
        # Si no tiene fechas pero está completada, asignar tiempo mínimo de 0.5 horas
        elif not task.started_at or not task.completed_at:
            WorkOrderTaskTimeEntry.objects.create(
                task=task,
                hours=Decimal('0.5'),
                description="Tiempo estimado para tarea completada - migración de datos",
                date=task.completed_at.date() if task.completed_at else timezone.now().date()
            )
            
            task.actual_hours = Decimal('0.5')
            task.save(update_fields=['actual_hours'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0110_auto_20251011_2038'),
    ]

    operations = [
        migrations.RunPython(add_time_to_completed_tasks, migrations.RunPython.noop),
    ]
