# Generated by Django 4.2.20 on 2025-10-11 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0111_add_time_to_completed_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Archivo')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del archivo', verbose_name='Descripción')),
                ('file', models.FileField(upload_to='shared_files/%Y/%m/', verbose_name='Archivo')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, todos los usuarios de la empresa pueden ver este archivo', verbose_name='Público')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Número de descargas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='tickets.company', verbose_name='Empresa')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo Compartido',
                'verbose_name_plural': 'Archivos Compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedFileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de descarga')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to=settings.AUTH_USER_MODEL, verbose_name='Descargado por')),
                ('shared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='tickets.sharedfile', verbose_name='Archivo Compartido')),
            ],
            options={
                'verbose_name': 'Descarga de Archivo',
                'verbose_name_plural': 'Descargas de Archivos',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
