# Generated by Django 4.2.20 on 2025-10-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0112_sharedfile_sharedfiledownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='tickets.company', verbose_name='Empresa'),
        ),
    ]
