# Generated by Django 4.2.20 on 2025-10-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0113_alter_sharedfile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la grabación')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la grabación', verbose_name='Descripción')),
                ('audio_file', models.FileField(upload_to='recordings/%Y/%m/', verbose_name='Archivo de audio')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, todos los usuarios de la empresa pueden ver esta grabación', verbose_name='Público')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en segundos')),
                ('transcription_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20, verbose_name='Estado de transcripción')),
                ('transcription_text', models.TextField(blank=True, verbose_name='Texto transcrito')),
                ('transcription_confidence', models.FloatField(blank=True, help_text='Porcentaje de confianza de la transcripción', null=True, verbose_name='Confianza de transcripción (%)')),
                ('transcription_language', models.CharField(default='es', max_length=10, verbose_name='Idioma detectado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('transcribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de transcripción')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='tickets.company', verbose_name='Empresa')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_recordings', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Grabación',
                'verbose_name_plural': 'Grabaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingPlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reproducción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('played_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording_playbacks', to=settings.AUTH_USER_MODEL, verbose_name='Reproducido por')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbacks', to='tickets.recording', verbose_name='Grabación')),
            ],
            options={
                'verbose_name': 'Reproducción',
                'verbose_name_plural': 'Reproducciones',
                'ordering': ['-played_at'],
            },
        ),
    ]
