# Generated by Django 4.2.20 on 2025-10-11 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0114_recording_recordingplayback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Página de Inicio'), ('blog', 'Blog'), ('blog_post', 'Artículo de Blog'), ('conceptos', 'Conceptos Públicos'), ('contact', 'Contacto'), ('landing', 'Landing Page'), ('course_public', 'Curso Público'), ('ticket_public', 'Ticket Público'), ('other', 'Otra')], max_length=50, verbose_name='Tipo de Página')),
                ('page_url', models.URLField(max_length=500, verbose_name='URL Visitada')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Título de la Página')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Código de País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región/Estado')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='Versión del Navegador')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operativo')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Dispositivo')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Es Móvil')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Es Bot')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Página de Referencia')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Sesión')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en Segundos')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Visita a Página',
                'verbose_name_plural': 'Visitas a Páginas',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['page_type', 'visited_at'], name='tickets_pag_page_ty_a606b5_idx'), models.Index(fields=['ip_address', 'visited_at'], name='tickets_pag_ip_addr_d3b508_idx'), models.Index(fields=['country_code'], name='tickets_pag_country_056adc_idx'), models.Index(fields=['is_bot'], name='tickets_pag_is_bot_d539cc_idx')],
            },
        ),
    ]
