# Generated by Django 4.2.20 on 2025-10-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0115_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBlogConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar este configurador', max_length=200, verbose_name='Nombre del Configurador')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de qué tipo de contenido genera', verbose_name='Descripción')),
                ('keywords', models.TextField(help_text='Palabras clave separadas por comas para generar contenido (ej: tecnología, desarrollo, python)', verbose_name='Palabras Clave')),
                ('topic_template', models.TextField(default='Escribe un artículo completo sobre {keyword} con ejemplos prácticos y consejos útiles.', help_text='Plantilla para generar el prompt. Usa {keyword} donde quieras insertar la palabra clave', verbose_name='Plantilla de Tema')),
                ('content_length', models.CharField(choices=[('short', 'Corto (500-800 palabras)'), ('medium', 'Medio (800-1200 palabras)'), ('long', 'Largo (1200-2000 palabras)')], default='medium', max_length=50, verbose_name='Longitud del Contenido')),
                ('content_style', models.CharField(choices=[('professional', 'Profesional'), ('casual', 'Casual'), ('technical', 'Técnico'), ('educational', 'Educativo'), ('news', 'Noticia')], default='professional', max_length=50, verbose_name='Estilo del Contenido')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, el configurador puede generar contenido automáticamente', verbose_name='Activo')),
                ('schedule_time', models.TimeField(default='10:00', help_text='Hora del día para ejecutar la generación automática (formato 24h)', verbose_name='Hora de Ejecución')),
                ('frequency_days', models.PositiveIntegerField(default=1, help_text='Cada cuántos días ejecutar (1 = diario, 7 = semanal, etc.)', verbose_name='Frecuencia (días)')),
                ('max_posts_per_run', models.PositiveIntegerField(default=1, help_text='Número máximo de posts a generar en cada ejecución', verbose_name='Máximo Posts por Ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('total_posts_generated', models.PositiveIntegerField(default=0, verbose_name='Total Posts Generados')),
                ('default_category', models.ForeignKey(blank=True, help_text='Categoría a asignar a los posts generados', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.blogcategory', verbose_name='Categoría por Defecto')),
            ],
            options={
                'verbose_name': 'Configurador de IA para Blog',
                'verbose_name_plural': 'Configuradores de IA para Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIBlogGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_used', models.CharField(max_length=200, verbose_name='Palabra Clave Utilizada')),
                ('prompt_used', models.TextField(verbose_name='Prompt Utilizado')),
                ('generation_status', models.CharField(choices=[('success', 'Exitoso'), ('error', 'Error'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado de Generación')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('execution_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Ejecución (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('configurator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='tickets.aiblogconfigurator', verbose_name='Configurador')),
                ('generated_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.blogpost', verbose_name='Post Generado')),
            ],
            options={
                'verbose_name': 'Log de Generación IA',
                'verbose_name_plural': 'Logs de Generación IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
