# Generated by Django 4.2.20 on 2025-10-13 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0116_aiblogconfigurator_aibloggenerationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Documentación')),
                ('description', models.TextField(blank=True, help_text='Descripción de qué contiene esta documentación', verbose_name='Descripción')),
                ('public_token', models.UUIDField(default=uuid.uuid4, help_text='Token único para acceso público', unique=True, verbose_name='Token Público')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, se puede acceder públicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documentación Múltiple',
                'verbose_name_plural': 'Documentaciones Múltiples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultipleDocumentationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Número de orden del documento', verbose_name='Número')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('file', models.FileField(help_text='Archivo a compartir', upload_to='multiple_documentation/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, help_text='Descripción del archivo', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.multipledocumentation', verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'Item de Documentación',
                'verbose_name_plural': 'Items de Documentación',
                'ordering': ['number'],
                'unique_together': {('documentation', 'number')},
            },
        ),
    ]
