# Generated by Django 4.2.20 on 2025-10-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0117_multipledocumentation_multipledocumentationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleDocumentationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tickets.multipledocumentation', verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'Visita a Documentación',
                'verbose_name_plural': 'Visitas a Documentación',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MultipleDocumentationItemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Número de Descargas')),
                ('unique_downloaders', models.PositiveIntegerField(default=0, help_text='Número de IPs únicas que han descargado este archivo', verbose_name='Descargadores Únicos')),
                ('first_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Primera Descarga')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Descarga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tickets.multipledocumentationitem', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Estadística de Archivo',
                'verbose_name_plural': 'Estadísticas de Archivos',
            },
        ),
        migrations.CreateModel(
            name='MultipleDocumentationDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='tickets.multipledocumentationitem', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Descarga de Archivo',
                'verbose_name_plural': 'Descargas de Archivos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MultipleDocumentationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.PositiveIntegerField(default=0, help_text='Número total de veces que se ha visitado la página pública', verbose_name='Visualizaciones de Página')),
                ('unique_visitors', models.PositiveIntegerField(default=0, help_text='Número de visitantes únicos (basado en IP)', verbose_name='Visitantes Únicos')),
                ('total_downloads', models.PositiveIntegerField(default=0, help_text='Número total de archivos descargados', verbose_name='Descargas Totales')),
                ('first_view_date', models.DateTimeField(blank=True, null=True, verbose_name='Primera Visualización')),
                ('last_view_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Visualización')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Descarga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tickets.multipledocumentation', verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'Estadística de Documentación',
                'verbose_name_plural': 'Estadísticas de Documentación',
                'unique_together': {('documentation',)},
            },
        ),
    ]
