# Generated by Django 4.2.20 on 2025-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0118_multipledocumentationvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipledocumentation',
            name='access_password',
            field=models.CharField(blank=True, help_text='Contraseña requerida para acceder a la documentación pública', max_length=100, verbose_name='Contraseña de acceso'),
        ),
        migrations.AddField(
            model_name='multipledocumentation',
            name='password_protected',
            field=models.BooleanField(default=False, help_text='Si está marcado, se requerirá una contraseña para acceder', verbose_name='Protegido con contraseña'),
        ),
    ]
