# Generated by Django 4.2.20 on 2025-10-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0120_taskschedule_scheduletask_schedulecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Correo del Cliente')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aprobación')),
                ('notes', models.TextField(blank=True, help_text='Comentarios adicionales del cliente', verbose_name='Notas Adicionales')),
                ('ip_address', models.GenericIPAddressField(help_text='IP desde donde se realizó la aprobación', verbose_name='Dirección IP')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_approval', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Aprobación de Cliente',
                'verbose_name_plural': 'Aprobaciones de Clientes',
                'ordering': ['-approved_at'],
            },
        ),
    ]
