# Generated by Django 4.2.20 on 2025-10-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0121_ticketapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Correo del Cliente')),
                ('overall_satisfaction', models.IntegerField(choices=[(1, '1 - Muy Insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy Satisfecho')], help_text='¿Qué tan satisfecho está con el servicio general?', verbose_name='Satisfacción General')),
                ('resolution_quality', models.IntegerField(choices=[(1, '1 - Muy Mala'), (2, '2 - Mala'), (3, '3 - Regular'), (4, '4 - Buena'), (5, '5 - Excelente')], help_text='¿Cómo califica la calidad de la solución proporcionada?', verbose_name='Calidad de la Solución')),
                ('response_time', models.IntegerField(choices=[(1, '1 - Muy Lento'), (2, '2 - Lento'), (3, '3 - Aceptable'), (4, '4 - Rápido'), (5, '5 - Muy Rápido')], help_text='¿Cómo califica nuestro tiempo de respuesta?', verbose_name='Tiempo de Respuesta')),
                ('communication', models.IntegerField(choices=[(1, '1 - Muy Insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy Satisfecho')], help_text='¿Cómo califica la comunicación durante el proceso?', verbose_name='Calidad de la Comunicación')),
                ('what_went_well', models.TextField(blank=True, help_text='Describa los aspectos positivos de nuestro servicio', null=True, verbose_name='¿Qué funcionó bien?')),
                ('what_could_improve', models.TextField(blank=True, help_text='Sugerencias para mejorar nuestro servicio', null=True, verbose_name='¿Qué se podría mejorar?')),
                ('additional_comments', models.TextField(blank=True, help_text='Cualquier otro comentario que desee compartir', null=True, verbose_name='Comentarios Adicionales')),
                ('would_recommend', models.BooleanField(default=True, help_text='¿Recomendaría nuestros servicios a otros?', verbose_name='¿Recomendaría nuestros servicios?')),
                ('recommendation_reason', models.TextField(blank=True, help_text='¿Por qué sí o por qué no recomendaría nuestros servicios?', null=True, verbose_name='Razón de recomendación')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la encuesta', null=True, verbose_name='Dirección IP')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_survey', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
