# Generated by Django 4.2.20 on 2025-10-14 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0122_satisfactionsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Símbolo de la acción (ej: EUR/USD, AAPL, GOOGL)', max_length=20, unique=True, verbose_name='Símbolo')),
                ('name', models.CharField(help_text='Nombre completo de la acción o par de divisas', max_length=200, verbose_name='Nombre')),
                ('current_price', models.DecimalField(decimal_places=4, help_text='Precio actual de la acción', max_digits=12, verbose_name='Precio Actual')),
                ('previous_price', models.DecimalField(blank=True, decimal_places=4, help_text='Precio del día anterior para calcular cambios', max_digits=12, null=True, verbose_name='Precio Anterior')),
                ('currency', models.CharField(default='USD', help_text='Moneda en la que se cotiza (USD, EUR, etc.)', max_length=10, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa se muestra en el ticker', verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el ticker (menor número = primera)', verbose_name='Orden')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Acción Financiera',
                'verbose_name_plural': 'Acciones Financieras',
                'ordering': ['order', 'symbol'],
            },
        ),
    ]
