# Generated by Django 4.2.20 on 2025-10-14 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0123_financialaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('financial_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tickets.financialaction', verbose_name='Acción Financiera')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historiales de Precios',
                'ordering': ['-recorded_at'],
                'unique_together': {('financial_action', 'recorded_at')},
            },
        ),
    ]
