# Generated by Django 4.2.20 on 2025-10-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0124_financialpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='spin_methodology',
            field=models.TextField(blank=True, help_text='Preguntas generadas automáticamente usando la metodología SPIN de ventas', verbose_name='Metodología SPIN'),
        ),
    ]
