# Generated by Django 4.2.20 on 2025-10-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0126_product'),
    ]

    operations = [
    ]
