# Generated by Django 4.2.20 on 2025-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0127_auto_20251014_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Productos que se discutirán en la reunión', to='tickets.product', verbose_name='Productos'),
        ),
    ]
