# Generated by Django 4.2.20 on 2025-10-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0128_meeting_products'),
    ]

    operations = [
    ]
