# Generated by Django 4.2.20 on 2025-10-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0129_auto_20251014_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='products',
        ),
        migrations.AddField(
            model_name='meeting',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto principal que se discutirá en la reunión', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.product', verbose_name='Producto'),
        ),
    ]
