# Generated by Django 4.2.20 on 2025-10-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0130_remove_meeting_products_meeting_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaction',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Se actualiza automáticamente desde APIs externas', max_digits=12, null=True, verbose_name='Precio Actual'),
        ),
        migrations.AlterField(
            model_name='financialaction',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Se actualiza automáticamente desde APIs externas', max_digits=12, null=True, verbose_name='Precio Anterior'),
        ),
    ]
