# Generated by Django 4.2.20 on 2025-10-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0131_alter_financialaction_current_price_and_more'),
    ]

    operations = [
    ]
