# Generated by Django 4.2.20 on 2025-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0132_auto_20251014_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialpricehistory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Precio'),
        ),
    ]
