# Generated by Django 4.2.20 on 2025-10-15 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0133_alter_financialpricehistory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(help_text='Correo electrónico del cliente', max_length=254, verbose_name='Correo del Cliente')),
                ('client_phone', models.CharField(blank=True, help_text='Número de teléfono del cliente (opcional)', max_length=20, verbose_name='Teléfono del Cliente')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Cantidad de horas a imputar (ej: 2.5)', max_digits=5, verbose_name='Horas')),
                ('category', models.CharField(choices=[('capacitacion', 'Capacitación'), ('pruebas', 'Pruebas'), ('uso', 'Uso')], help_text='Categoría de las horas imputadas', max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del trabajo realizado', verbose_name='Descripción')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha cuando se realizaron las horas de trabajo', verbose_name='Fecha de las horas')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se registró la entrada', null=True, verbose_name='IP del Cliente')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador del cliente', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_time_entries', to='tickets.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Entrada de Tiempo de Cliente',
                'verbose_name_plural': 'Entradas de Tiempo de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(help_text='Token único para acceso público al formulario de horas', max_length=64, unique=True, verbose_name='Token Público')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, el enlace público no funcionará', verbose_name='Activo')),
                ('max_entries_per_day', models.PositiveIntegerField(default=50, help_text='Límite de entradas de tiempo que se pueden crear por día', verbose_name='Máximo de entradas por día')),
                ('requires_phone', models.BooleanField(default=True, help_text='Si es obligatorio que el cliente proporcione su teléfono', verbose_name='Requiere teléfono')),
                ('allowed_categories', models.JSONField(default=list, help_text='Lista de categorías que el cliente puede seleccionar', verbose_name='Categorías permitidas')),
                ('instructions', models.TextField(blank=True, help_text='Instrucciones que verá el cliente en el formulario', verbose_name='Instrucciones')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_access', to='tickets.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Acceso Público de Cliente',
                'verbose_name_plural': 'Accesos Públicos de Clientes',
            },
        ),
    ]
