# Generated by Django 4.2.20 on 2025-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0134_clienttimeentry_clientprojectaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprojectaccess',
            name='dashboard_token',
            field=models.CharField(blank=True, help_text='Token único para acceso público al dashboard de estadísticas', max_length=64, null=True, unique=True, verbose_name='Token Dashboard Público'),
        ),
    ]
