# Generated by Django 4.2.20 on 2025-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0135_clientprojectaccess_dashboard_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttimeentry',
            name='client_name',
            field=models.CharField(blank=True, default='Cliente', help_text='Nombre completo del cliente', max_length=100, verbose_name='Nombre del Cliente'),
        ),
    ]
