# Generated by Django 4.2.20 on 2025-10-16 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0136_clienttimeentry_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por'),
        ),
        migrations.AlterField(
            model_name='clienttimeentry',
            name='client_name',
            field=models.CharField(help_text='Nombre completo del cliente', max_length=100, verbose_name='Nombre del Cliente'),
        ),
    ]
