# Generated by Django 4.2.20 on 2025-10-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0137_add_processed_by_to_landing_page_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='La URL larga que se quiere acortar', max_length=2000, verbose_name='URL Original')),
                ('short_code', models.CharField(help_text='Código único para la URL corta', max_length=10, unique=True, verbose_name='Código Corto')),
                ('title', models.CharField(blank=True, help_text='Título descriptivo opcional para la URL', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la URL', verbose_name='Descripción')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Número de veces que se ha accedido a la URL corta', verbose_name='Clics')),
                ('is_active', models.BooleanField(default=True, help_text='Si la URL corta está activa o deshabilitada', verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha opcional cuando expira la URL corta', null=True, verbose_name='Fecha de expiración')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la URL corta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'URL Corta',
                'verbose_name_plural': 'URLs Cortas',
                'ordering': ['-created_at'],
            },
        ),
    ]
