# Generated by Django 4.2.20 on 2025-10-16 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0138_shorturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre del conjunto de productos', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del conjunto de productos', verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, los clientes podrán ver este conjunto', verbose_name='Público')),
                ('public_token', models.CharField(blank=True, help_text='Token único para acceso público', max_length=32, unique=True, verbose_name='Token Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el conjunto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Conjunto de Productos',
                'verbose_name_plural': 'Conjuntos de Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del producto', max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('video_link', models.URLField(blank=True, help_text='URL del video demostrativo (opcional)', verbose_name='Link del Video')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista', verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tickets.productset', verbose_name='Conjunto de Productos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
