# Generated by Django 4.2.20 on 2025-10-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0139_productset_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última vista pública', null=True, verbose_name='Última vista'),
        ),
        migrations.AddField(
            model_name='productset',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que se ha visto el conjunto público', verbose_name='Vistas'),
        ),
    ]
