# Generated by Django 4.2.20 on 2025-10-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0140_productset_last_viewed_at_productset_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del conjunto de productos (0.00 = gratis, no se muestra)', max_digits=10, verbose_name='Precio'),
        ),
    ]
