# Generated by Django 4.2.20 on 2025-10-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0141_productset_price'),
    ]

    operations = [
    ]
