# Generated by Django 4.2.20 on 2025-10-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0142_auto_20251016_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productset',
            name='price',
        ),
        migrations.AddField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del producto individual', max_digits=10, verbose_name='Precio'),
        ),
    ]
