# Generated by Django 4.2.20 on 2025-10-16 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0143_update_product_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo del precotizador', max_length=200, verbose_name='Título del Precotizador')),
                ('client_description', models.TextField(help_text='Descripción detallada del tipo de cliente y sus necesidades', verbose_name='Descripción del Cliente')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Tu tarifa por hora para este tipo de trabajo', max_digits=10, verbose_name='Precio por Hora')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el precotizador', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Precotizador',
                'verbose_name_plural': 'Precotizadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrecotizadorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request', models.TextField(help_text='Descripción del trabajo solicitado por el cliente', verbose_name='Solicitud del Cliente')),
                ('ai_estimated_hours', models.DecimalField(decimal_places=2, help_text='Número de horas estimadas por la IA', max_digits=8, verbose_name='Horas Estimadas por IA')),
                ('ai_detailed_description', models.TextField(help_text='Descripción detallada del trabajo generada por la IA', verbose_name='Descripción Detallada por IA')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Explicación del razonamiento de la IA para la estimación', verbose_name='Razonamiento de la IA')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('precotizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tickets.precotizador', verbose_name='Precotizador')),
            ],
            options={
                'verbose_name': 'Cotización IA',
                'verbose_name_plural': 'Cotizaciones IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrecotizadorExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción detallada del trabajo a realizar', verbose_name='Descripción del Caso')),
                ('estimated_hours', models.DecimalField(decimal_places=2, help_text='Número de horas estimadas para completar el trabajo', max_digits=8, verbose_name='Horas Estimadas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista', verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('precotizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='tickets.precotizador', verbose_name='Precotizador')),
            ],
            options={
                'verbose_name': 'Ejemplo de Caso',
                'verbose_name_plural': 'Ejemplos de Casos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
