# Generated by Django 4.2.20 on 2025-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0144_add_precotizador_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='precotizadorquote',
            name='ai_full_response',
            field=models.TextField(blank=True, help_text='Respuesta completa de la IA en formato texto plano', verbose_name='Respuesta Completa de la IA'),
        ),
    ]
