# Generated by Django 4.2.20 on 2025-10-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0145_precotizadorquote_ai_full_response'),
    ]

    operations = [
    ]
