# Generated by Django 4.2.20 on 2025-10-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0146_add_ai_full_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='precotizadorquote',
            name='client_comments',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del cliente', verbose_name='Comentarios del Cliente'),
        ),
        migrations.AddField(
            model_name='precotizadorquote',
            name='client_response_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el cliente respondió', null=True, verbose_name='Fecha de Respuesta del Cliente'),
        ),
        migrations.AddField(
            model_name='precotizadorquote',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si la cotización puede ser vista públicamente', verbose_name='Es Público'),
        ),
        migrations.AddField(
            model_name='precotizadorquote',
            name='public_share_token',
            field=models.CharField(blank=True, help_text='Token único para compartir la cotización públicamente', max_length=100, null=True, unique=True, verbose_name='Token de Compartir Público'),
        ),
        migrations.AddField(
            model_name='precotizadorquote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada por el Cliente'), ('rejected', 'Rechazada por el Cliente'), ('expired', 'Expirada')], default='pending', help_text='Estado actual de la cotización', max_length=20, verbose_name='Estado'),
        ),
    ]
