# Generated by Django 4.2.20 on 2025-10-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0147_precotizadorquote_client_comments_and_more'),
    ]

    operations = [
    ]
