# Generated by Django 4.2.20 on 2025-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0148_add_quote_sharing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='precotizador',
            name='allow_public_requests',
            field=models.BooleanField(default=False, help_text='Permite que los clientes soliciten cotizaciones a través de un enlace público', verbose_name='Permitir Solicitudes Públicas'),
        ),
        migrations.AddField(
            model_name='precotizador',
            name='public_request_token',
            field=models.CharField(blank=True, help_text='Token único para el enlace público donde clientes pueden solicitar cotizaciones', max_length=255, null=True, unique=True, verbose_name='Token de Solicitud Pública'),
        ),
    ]
