# Generated by Django 4.2.20 on 2025-10-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0149_precotizador_allow_public_requests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Es público')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documentación de Empresa',
                'verbose_name_plural': 'Documentaciones de Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocumentationURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del enlace')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Contraseña')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='tickets.companydocumentation', verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'URL de Documentación',
                'verbose_name_plural': 'URLs de Documentación',
                'ordering': ['order', 'title'],
            },
        ),
    ]
