# Generated by Django 4.2.20 on 2025-10-17 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0150_companydocumentation_companydocumentationurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('collect_phone', models.BooleanField(default=False, verbose_name='Recopilar teléfono')),
                ('collect_company', models.BooleanField(default=True, verbose_name='Recopilar empresa')),
                ('collect_position', models.BooleanField(default=True, verbose_name='Recopilar cargo')),
                ('collect_notes', models.BooleanField(default=False, verbose_name='Recopilar notas')),
                ('welcome_message', models.TextField(default='¡Gracias por tu interés! Por favor, completa la siguiente información para que podamos contactarte.', verbose_name='Mensaje de bienvenida')),
                ('success_message', models.TextField(default='¡Gracias! Hemos recibido tu información y nos pondremos en contacto contigo pronto.', verbose_name='Mensaje de éxito')),
                ('background_color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (ej: #007bff)', max_length=7, verbose_name='Color de fondo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_generators', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Generador de Contactos',
                'verbose_name_plural': 'Generadores de Contactos',
                'ordering': ['-created_at'],
            },
        ),
    ]
