# Generated by Django 4.2.20 on 2025-10-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0151_contactgenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=50, unique=True, verbose_name='Número de solicitud')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('text', models.TextField(blank=True, verbose_name='Texto de la solicitud')),
                ('url', models.URLField(blank=True, verbose_name='URL relacionada')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('review', 'En revisión'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Empresa',
                'verbose_name_plural': 'Solicitudes de Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRequestGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('sequence_prefix', models.CharField(blank=True, default='', help_text='Prefijo que se antepone al número de solicitud (ej: SR-)', max_length=20, verbose_name='Prefijo de Secuencia')),
                ('next_sequence', models.PositiveIntegerField(default=1, help_text='Número secuencial que se incrementa por cada solicitud', verbose_name='Siguiente secuencia')),
                ('collect_date', models.BooleanField(default=True, verbose_name='Incluir fecha')),
                ('collect_text', models.BooleanField(default=True, verbose_name='Incluir texto de solicitud')),
                ('collect_url', models.BooleanField(default=False, verbose_name='Incluir URL relacionada')),
                ('welcome_message', models.TextField(default='Por favor, envía tu solicitud y nuestro equipo la revisará.', verbose_name='Mensaje de bienvenida')),
                ('success_message', models.TextField(default='Solicitud recibida. Te contactaremos pronto.', verbose_name='Mensaje de éxito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_request_generators', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Generador de Solicitudes Empresa',
                'verbose_name_plural': 'Generadores de Solicitudes Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.companyrequest', verbose_name='Solicitud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de Solicitud',
                'verbose_name_plural': 'Comentarios de Solicitudes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='companyrequest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tickets.companyrequestgenerator', verbose_name='Generador'),
        ),
    ]
