# Generated by Django 4.2.20 on 2025-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0152_companyrequest_companyrequestgenerator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('review', 'En revisión'), ('accepted', 'Aceptada'), ('executed', 'Ejecutada'), ('rejected', 'Rechazada'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='Estado'),
        ),
    ]
