# Generated by Django 4.2.20 on 2025-10-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0153_alter_companyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrequest',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ejecución'),
        ),
        migrations.AddField(
            model_name='companyrequest',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_company_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por'),
        ),
    ]
