# Generated by Django 4.2.20 on 2025-10-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0154_companyrequest_executed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del formulario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto de la pregunta')),
                ('question_type', models.CharField(choices=[('number', 'Cantidad (Número)'), ('multiple_choice', 'Selección múltiple'), ('text', 'Texto libre')], max_length=20, verbose_name='Tipo de pregunta')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.form', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del encuestado')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del encuestado')),
                ('total_score', models.IntegerField(default=0, verbose_name='Puntuación total')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tickets.form', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Respuesta al Formulario',
                'verbose_name_plural': 'Respuestas a Formularios',
                'ordering': ['-response_date'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='Texto de la opción')),
                ('score', models.IntegerField(default=0, verbose_name='Puntuación')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tickets.formquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Preguntas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Respuesta de texto')),
                ('number_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Respuesta numérica')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.formquestion', verbose_name='Pregunta')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.formresponse', verbose_name='Respuesta al formulario')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.formquestionoption', verbose_name='Opción seleccionada')),
            ],
            options={
                'verbose_name': 'Respuesta Individual',
                'verbose_name_plural': 'Respuestas Individuales',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
