# Generated by Django 4.2.20 on 2025-10-17 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0157_alcance_actualizado_en_alter_alcance_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('qr_pending', 'QR Pendiente'), ('error', 'Error')], default='disconnected', max_length=20, verbose_name='Estado')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='Código QR')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('session_data', models.TextField(blank=True, null=True, verbose_name='Datos de sesión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_connected', models.DateTimeField(blank=True, null=True, verbose_name='Última conexión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conexión WhatsApp',
                'verbose_name_plural': 'Conexiones WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Palabra clave')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('is_exact_match', models.BooleanField(default=False, help_text='Si es verdadero, debe coincidir exactamente. Si es falso, busca la palabra en el mensaje.', verbose_name='Coincidencia exacta')),
                ('is_case_sensitive', models.BooleanField(default=False, verbose_name='Sensible a mayúsculas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('priority', models.IntegerField(default=0, help_text='Mayor número = mayor prioridad', verbose_name='Prioridad')),
                ('use_count', models.IntegerField(default=0, verbose_name='Veces usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='tickets.whatsappconnection', verbose_name='Conexión')),
            ],
            options={
                'verbose_name': 'Palabra Clave WhatsApp',
                'verbose_name_plural': 'Palabras Clave WhatsApp',
                'ordering': ['-priority', 'keyword'],
                'unique_together': {('connection', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('received', 'Recibido'), ('sent', 'Enviado'), ('auto_reply', 'Respuesta Automática')], max_length=20, verbose_name='Tipo de mensaje')),
                ('from_number', models.CharField(max_length=50, verbose_name='De')),
                ('to_number', models.CharField(max_length=50, verbose_name='Para')),
                ('message_text', models.TextField(verbose_name='Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.whatsappconnection', verbose_name='Conexión')),
                ('keyword_matched', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.whatsappkeyword', verbose_name='Palabra clave coincidente')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['-timestamp'],
            },
        ),
    ]
