# Generated by Django 4.2.20 on 2025-10-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0158_whatsappconnection_whatsappkeyword_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcance',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del artículo relacionado'),
        ),
    ]
