# Generated by Django 4.2.20 on 2025-10-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0159_alcance_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo para identificar esta imagen', max_length=200, verbose_name='Título')),
                ('image', models.ImageField(help_text='Sube una imagen para generar un prompt', upload_to='image_prompts/%Y/%m/', verbose_name='Imagen')),
                ('generated_prompt', models.TextField(blank=True, help_text='Prompt generado automáticamente por IA', verbose_name='Prompt Generado')),
                ('custom_prompt', models.TextField(blank=True, help_text='Prompt editado manualmente por el usuario', null=True, verbose_name='Prompt Personalizado')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para organizar', max_length=500, verbose_name='Etiquetas')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, otros usuarios pueden ver este prompt', verbose_name='¿Es público?')),
                ('tokens_used', models.IntegerField(default=0, help_text='Cantidad de tokens de IA utilizados', verbose_name='Tokens usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Image to Prompt',
                'verbose_name_plural': 'Image to Prompts',
                'ordering': ['-created_at'],
            },
        ),
    ]
