# Generated by Django 4.2.20 on 2025-10-18 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0160_imageprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ejemplo: Gerente de Ventas IA', max_length=200, verbose_name='Nombre del Gerente IA')),
                ('category', models.CharField(choices=[('ventas', 'Ventas'), ('compras', 'Compras'), ('contabilidad', 'Contabilidad'), ('crm', 'CRM'), ('inventario', 'Inventario'), ('rrhh', 'Recursos Humanos'), ('marketing', 'Marketing'), ('operaciones', 'Operaciones'), ('finanzas', 'Finanzas'), ('ti', 'Tecnología'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, help_text='Describe el rol y responsabilidades de este gerente IA', verbose_name='Descripción')),
                ('instructions', models.TextField(default='Eres un gerente experimentado y empático. Tu objetivo es ayudar al equipo a mejorar.', help_text='Contexto y personalidad del gerente IA', verbose_name='Instrucciones para la IA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_managers', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_managers', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Gerente IA',
                'verbose_name_plural': 'Gerentes IA',
                'ordering': ['company', 'category', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AIManagerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('summary_text', models.TextField(help_text='Resumen de todas las reuniones del período', verbose_name='Resumen general')),
                ('key_insights', models.TextField(help_text='Puntos clave identificados', verbose_name='Insights clave')),
                ('recommendations', models.TextField(help_text='Recomendaciones para la empresa', verbose_name='Recomendaciones')),
                ('total_meetings', models.IntegerField(default=0, verbose_name='Total de reuniones')),
                ('participants_count', models.IntegerField(default=0, verbose_name='Participantes únicos')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ai_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='tickets.aimanager', verbose_name='Gerente IA')),
            ],
            options={
                'verbose_name': 'Resumen del Gerente IA',
                'verbose_name_plural': 'Resúmenes del Gerente IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIManagerMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resumen breve de la reunión', max_length=300, verbose_name='Título')),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio')], default='text', max_length=10, verbose_name='Tipo de entrada')),
                ('user_input', models.TextField(help_text='Lo que el usuario escribió o transcripción del audio', verbose_name='Entrada del usuario')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ai_manager_meetings/%Y/%m/', verbose_name='Archivo de audio')),
                ('ai_response', models.TextField(help_text='Análisis y recomendaciones del gerente IA', verbose_name='Respuesta de la IA')),
                ('ai_summary', models.TextField(help_text='Resumen corto de la reunión', verbose_name='Resumen de la IA')),
                ('improvement_areas', models.TextField(blank=True, help_text='Áreas identificadas para mejorar', verbose_name='Áreas de mejora')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reunión')),
                ('ai_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='tickets.aimanager', verbose_name='Gerente IA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_manager_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reunión con Gerente IA',
                'verbose_name_plural': 'Reuniones con Gerentes IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
