# Generated by Django 4.2.20 on 2025-10-18 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0161_aimanager_aimanagersummary_aimanagermeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('executive_summary', models.TextField(help_text='Resumen general de toda la empresa', verbose_name='Resumen ejecutivo')),
                ('key_metrics', models.TextField(help_text='KPIs y métricas importantes', verbose_name='Métricas clave')),
                ('department_highlights', models.TextField(help_text='Logros por área/gerente', verbose_name='Destacados por departamento')),
                ('challenges', models.TextField(help_text='Principales retos de la empresa', verbose_name='Desafíos identificados')),
                ('strategic_recommendations', models.TextField(help_text='Acciones recomendadas para la dirección', verbose_name='Recomendaciones estratégicas')),
                ('total_managers', models.IntegerField(default=0, verbose_name='Total de gerentes')),
                ('total_meetings', models.IntegerField(default=0, verbose_name='Total de reuniones')),
                ('total_participants', models.IntegerField(default=0, verbose_name='Total de participantes')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='tickets.company', verbose_name='Empresa')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Resumen Empresarial IA',
                'verbose_name_plural': 'Resúmenes Empresariales IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
