# Generated by Django 4.2.20 on 2025-10-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0162_companyaisummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_objectives',
            field=models.TextField(blank=True, help_text='Objetivos, metas y KPIs estratégicos de la empresa. Estos serán considerados en los resúmenes ejecutivos generados por IA.', verbose_name='Objetivos Empresariales'),
        ),
    ]
