# Generated by Django 4.2.20 on 2025-10-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0163_add_business_objectives_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIManagerMeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Documentos, imágenes, PDFs que el gerente debe considerar', upload_to='ai_manager_meeting_attachments/%Y/%m/', verbose_name='Archivo adjunto')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de archivo')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.aimanagermeeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Adjunto de Reunión IA',
                'verbose_name_plural': 'Adjuntos de Reuniones IA',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
