# Generated by Django 4.2.20 on 2025-10-18 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0164_aimanagermeetingattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIPerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(verbose_name='Fecha de evaluación')),
                ('overall_score', models.IntegerField(help_text='Calificación automática generada por IA', verbose_name='Puntuación general (1-100)')),
                ('productivity_score', models.IntegerField(default=0, verbose_name='Productividad (1-100)')),
                ('communication_score', models.IntegerField(default=0, verbose_name='Comunicación (1-100)')),
                ('goal_achievement_score', models.IntegerField(default=0, verbose_name='Logro de objetivos (1-100)')),
                ('consistency_score', models.IntegerField(default=0, verbose_name='Consistencia (1-100)')),
                ('improvement_areas', models.TextField(help_text='Áreas identificadas que necesitan mejora', verbose_name='Áreas de mejora')),
                ('training_recommendations', models.TextField(help_text='Cursos o entrenamientos sugeridos', verbose_name='Recomendaciones de capacitación')),
                ('strengths', models.TextField(help_text='Puntos fuertes del usuario', verbose_name='Fortalezas identificadas')),
                ('meetings_analyzed', models.IntegerField(default=0, verbose_name='Reuniones analizadas')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Inicio del período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fin del período')),
                ('ai_summary', models.TextField(blank=True, help_text='Resumen narrativo generado por IA', verbose_name='Resumen IA')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluations', to='tickets.company', verbose_name='Empresa')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_performance_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño IA',
                'verbose_name_plural': 'Evaluaciones de Desempeño IA',
                'ordering': ['-evaluation_date', '-created_at'],
                'unique_together': {('user', 'evaluation_date')},
            },
        ),
    ]
