# Generated by Django 4.2.20 on 2025-10-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0165_useraiperformanceevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='URL completa (https://ejemplo.com) o dirección IP', max_length=500, verbose_name='URL o IP')),
                ('is_active', models.BooleanField(default=False, verbose_name='Está activo')),
                ('ping_response_time', models.FloatField(blank=True, help_text='Tiempo de respuesta del ping en milisegundos', null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('ip_address', models.CharField(blank=True, max_length=100, verbose_name='Dirección IP')),
                ('cname_records', models.JSONField(blank=True, default=list, verbose_name='Registros CNAME')),
                ('txt_records', models.JSONField(blank=True, default=list, verbose_name='Registros TXT')),
                ('mx_records', models.JSONField(blank=True, default=list, verbose_name='Registros MX')),
                ('ns_records', models.JSONField(blank=True, default=list, verbose_name='Registros NS')),
                ('http_status_code', models.IntegerField(blank=True, null=True, verbose_name='Código de estado HTTP')),
                ('http_headers', models.JSONField(blank=True, default=dict, verbose_name='Headers HTTP')),
                ('redirect_url', models.CharField(blank=True, max_length=500, verbose_name='URL de redirección')),
                ('server_software', models.CharField(blank=True, max_length=200, verbose_name='Software del servidor')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Frameworks, CMS, librerías detectadas', verbose_name='Tecnologías detectadas')),
                ('ssl_valid', models.BooleanField(blank=True, null=True, verbose_name='SSL válido')),
                ('ssl_issuer', models.CharField(blank=True, max_length=200, verbose_name='Emisor del certificado SSL')),
                ('ssl_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración SSL')),
                ('page_title', models.CharField(blank=True, max_length=500, verbose_name='Título de la página')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta descripción')),
                ('page_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño de página (bytes)')),
                ('load_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de carga (s)')),
                ('whois_data', models.JSONField(blank=True, default=dict, verbose_name='Datos WHOIS')),
                ('error_message', models.TextField(blank=True, help_text='Si ocurre algún error durante el rastreo', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de rastreo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_trackers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rastreador Web',
                'verbose_name_plural': 'Rastreadores Web',
                'ordering': ['-created_at'],
            },
        ),
    ]
