# Generated by Django 4.2.20 on 2025-10-18 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0166_websitetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Contrato de Soporte de Software', max_length=255, verbose_name='Nombre del contrato')),
                ('contract_type', models.CharField(help_text='Ej: Soporte de software, Desarrollo, Consultoría, etc.', max_length=100, verbose_name='Tipo de contrato')),
                ('objective_prompt', models.TextField(help_text='Describe el objetivo y alcance del contrato. Ej: Soporte técnico 24/7 para sistema ERP', verbose_name='Objetivo del contrato')),
                ('generated_content', models.TextField(blank=True, help_text='Contenido del contrato generado por IA', verbose_name='Contenido generado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor económico del contrato', max_digits=12, null=True, verbose_name='Monto del contrato')),
                ('currency', models.CharField(default='USD', help_text='Código de moneda (USD, EUR, MXN, etc.)', max_length=3, verbose_name='Moneda')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para compartir el contrato públicamente', unique=True, verbose_name='Token público')),
                ('is_public', models.BooleanField(default=False, help_text='Si está marcado, el contrato se puede ver públicamente con el enlace', verbose_name='Público')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('generated', 'Generado'), ('sent', 'Enviado'), ('signed', 'Firmado'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('generated_at', models.DateTimeField(blank=True, help_text='Cuándo se generó el contenido con IA', null=True, verbose_name='Fecha de generación')),
                ('notes', models.TextField(blank=True, help_text='Notas privadas sobre el contrato', verbose_name='Notas internas')),
                ('client_company', models.ForeignKey(help_text='La empresa que contrata el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='legal_contracts_as_client', to='tickets.company', verbose_name='Empresa cliente')),
                ('company', models.ForeignKey(help_text='Tu empresa que provee el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='legal_contracts_as_provider', to='tickets.company', verbose_name='Empresa proveedora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Contrato Legal',
                'verbose_name_plural': 'Contratos Legales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_token'], name='tickets_leg_public__0a4fe4_idx'), models.Index(fields=['status'], name='tickets_leg_status_daf80d_idx'), models.Index(fields=['-created_at'], name='tickets_leg_created_49c18a_idx')],
            },
        ),
    ]
