# Generated by Django 4.2.20 on 2025-10-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0167_legalcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Contrato')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('contract_text', models.TextField(help_text='Pegue aquí el texto del contrato o déjelo vacío si subirá un archivo', verbose_name='Texto del Contrato')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contract_reviews/%Y/%m/', verbose_name='Archivo del Contrato')),
                ('ai_review', models.TextField(blank=True, help_text='Análisis generado por IA', verbose_name='Revisión de IA')),
                ('risk_assessment', models.TextField(blank=True, verbose_name='Evaluación de Riesgos')),
                ('key_clauses', models.TextField(blank=True, verbose_name='Cláusulas Clave Identificadas')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', max_length=20, verbose_name='Nivel de Riesgo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contract_reviews', to='tickets.company', verbose_name='Empresa Revisora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Revisión de Contrato de Proveedor',
                'verbose_name_plural': 'Revisiones de Contratos de Proveedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
