# Generated by Django 4.2.20 on 2025-10-18 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0168_suppliercontractreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='paypal_client_id',
            field=models.CharField(blank=True, help_text='Client ID de la aplicación PayPal', max_length=200, verbose_name='PayPal Client ID'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='paypal_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret de la aplicación PayPal', max_length=200, verbose_name='PayPal Client Secret'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='paypal_enabled',
            field=models.BooleanField(default=False, help_text='Habilita o deshabilita los pagos con PayPal', verbose_name='PayPal habilitado'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='paypal_mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox (Pruebas)'), ('live', 'Live (Producción)')], default='sandbox', help_text='Modo de operación de PayPal', max_length=20, verbose_name='Modo de PayPal'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='paypal_webhook_id',
            field=models.CharField(blank=True, help_text='ID del webhook configurado en PayPal para recibir notificaciones de pagos', max_length=200, verbose_name='PayPal Webhook ID'),
        ),
        migrations.CreateModel(
            name='PayPalPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del Producto/Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (EUR)')),
                ('attachment', models.FileField(blank=True, help_text='Archivo que el cliente podrá descargar después del pago', null=True, upload_to='paypal_attachments/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('attachment_name', models.CharField(blank=True, help_text='Nombre descriptivo del archivo adjunto', max_length=200, verbose_name='Nombre del archivo')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token Público')),
                ('public_url', models.URLField(blank=True, verbose_name='URL Pública')),
                ('paypal_order_id', models.CharField(blank=True, max_length=200, verbose_name='ID de Orden PayPal')),
                ('paypal_payer_id', models.CharField(blank=True, max_length=200, verbose_name='ID del Pagador')),
                ('paypal_payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Pagador')),
                ('paypal_payer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Pagador')),
                ('paypal_payment_status', models.CharField(blank=True, max_length=50, verbose_name='Estado del Pago PayPal')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paid', 'Pagado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Estado')),
                ('download_count', models.IntegerField(default=0, verbose_name='Número de Descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Enlace de Pago PayPal',
                'verbose_name_plural': 'Enlaces de Pago PayPal',
                'ordering': ['-created_at'],
            },
        ),
    ]
