# Generated by Django 4.2.20 on 2025-10-18 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0169_systemconfiguration_paypal_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpaymentlink',
            name='download_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Descarga Temporal'),
        ),
        migrations.AddField(
            model_name='paypalpaymentlink',
            name='download_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración del Token de Descarga'),
        ),
    ]
