# Generated by Django 4.2.20 on 2025-10-18 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0170_add_download_token_to_paypal_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para acceder a esta orden específica', unique=True, verbose_name='Token de Orden')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe (EUR)')),
                ('paypal_order_id', models.CharField(max_length=200, unique=True, verbose_name='ID de Orden PayPal')),
                ('paypal_payer_id', models.CharField(blank=True, max_length=200, verbose_name='ID del Pagador')),
                ('paypal_payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Pagador')),
                ('paypal_payer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Pagador')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Descarga')),
                ('download_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiración Token de Descarga')),
                ('download_count', models.IntegerField(default=0, verbose_name='Número de Descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('payment_link', models.ForeignKey(help_text='Enlace de pago desde el cual se generó esta orden', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.paypalpaymentlink', verbose_name='Enlace de Pago')),
            ],
            options={
                'verbose_name': 'Orden de Pago PayPal',
                'verbose_name_plural': 'Órdenes de Pago PayPal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paypal_order_id'], name='tickets_pay_paypal__fc7443_idx'), models.Index(fields=['order_token'], name='tickets_pay_order_t_17d071_idx'), models.Index(fields=['download_token'], name='tickets_pay_downloa_dc65d6_idx'), models.Index(fields=['status', 'created_at'], name='tickets_pay_status_06e581_idx')],
            },
        ),
    ]
