# Generated by Django 4.2.20 on 2025-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0171_add_paypal_order_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimanager',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat o canal donde se enviarán los resúmenes', max_length=100, verbose_name='Chat ID de Telegram'),
        ),
        migrations.AddField(
            model_name='aimanager',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Enviar resúmenes automáticamente por Telegram', verbose_name='Telegram Habilitado'),
        ),
    ]
