# Generated by Django 4.2.20 on 2025-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0172_add_telegram_to_aimanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimanager',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Token único del bot de Telegram para este gerente', max_length=200, verbose_name='Token del Bot de Telegram'),
        ),
    ]
