# Generated by Django 4.2.20 on 2025-10-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0173_add_telegram_bot_token_to_aimanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Tarea')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Item de TODO',
                'verbose_name_plural': 'Items de TODO',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
