# Generated by Django 4.2.20 on 2025-10-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0174_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título del Libro')),
                ('topic', models.TextField(help_text='Describe de qué quieres que trate el libro', verbose_name='Tema/Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('chapters_proposed', 'Capítulos Propuestos'), ('in_progress', 'En Progreso'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_books', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_books', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Libro IA',
                'verbose_name_plural': 'Libros IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIBookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título del Capítulo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('summary', models.TextField(blank=True, help_text='Resumen breve de lo que tratará el capítulo', verbose_name='Resumen del Capítulo')),
                ('content', models.TextField(blank=True, help_text='Contenido completo generado por IA', verbose_name='Contenido del Capítulo')),
                ('status', models.CharField(choices=[('proposed', 'Propuesto'), ('summary_created', 'Resumen Creado'), ('content_generated', 'Contenido Generado'), ('completed', 'Completado')], default='proposed', max_length=20, verbose_name='Estado')),
                ('word_count', models.IntegerField(default=0, verbose_name='Conteo de Palabras')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tickets.aibook', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Capítulo de Libro IA',
                'verbose_name_plural': 'Capítulos de Libros IA',
                'ordering': ['book', 'order'],
            },
        ),
    ]
