# Generated by Django 4.2.20 on 2025-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0175_aibook_aibookchapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='aibook',
            name='author',
            field=models.CharField(blank=True, help_text='Nombre del autor del libro', max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='aibookchapter',
            name='content',
            field=models.TextField(blank=True, help_text='Contenido completo en texto plano (sin formato Markdown)', verbose_name='Contenido del Capítulo'),
        ),
    ]
