# Generated by Django 4.2.20 on 2025-10-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0176_aibook_author_alter_aibookchapter_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIArticleProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título del Proyecto')),
                ('main_topic', models.TextField(help_text='Describe el tema principal sobre el cual quieres generar artículos', verbose_name='Tema Principal')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('articles_proposed', 'Artículos Propuestos'), ('in_progress', 'En Progreso'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_article_projects', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_article_projects', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto de Artículos IA',
                'verbose_name_plural': 'Proyectos de Artículos IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título del Artículo')),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=1000, verbose_name='Palabras Clave')),
                ('content', models.TextField(blank=True, help_text='Contenido completo en texto plano', verbose_name='Contenido del Artículo')),
                ('status', models.CharField(choices=[('proposed', 'Propuesto'), ('content_generated', 'Contenido Generado'), ('completed', 'Completado')], default='proposed', max_length=20, verbose_name='Estado')),
                ('word_count', models.IntegerField(default=0, verbose_name='Conteo de Palabras')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tickets.aiarticleproject', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Artículo IA',
                'verbose_name_plural': 'Artículos IA',
                'ordering': ['project', 'order'],
            },
        ),
    ]
