# Generated by Django 4.2.20 on 2025-10-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0177_aiarticleproject_aiarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiarticleproject',
            name='content_format',
            field=models.CharField(choices=[('plain', 'Texto Plano'), ('markdown', 'Markdown')], default='plain', help_text='Formato en el que se generará el contenido de los artículos', max_length=20, verbose_name='Formato de Contenido'),
        ),
    ]
