# Generated by Django 4.2.20 on 2025-10-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0178_aiarticleproject_content_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='products_catalog_token',
            field=models.UUIDField(blank=True, help_text='Token único para acceso público al catálogo de productos', null=True, unique=True, verbose_name='Token del Catálogo Público'),
        ),
    ]
