# Generated by Django 4.2.20 on 2025-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0179_systemconfiguration_products_catalog_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='URL para planificar reuniones (ej: Calendly, Google Meet, Zoom, etc.)', verbose_name='URL de Reunión'),
        ),
    ]
