# Generated by Django 4.2.20 on 2025-10-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0180_add_meeting_url_to_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='preferred_contact_time',
            field=models.CharField(choices=[('asap', 'Lo antes posible'), ('monday', 'El próximo lunes'), ('tuesday', 'El próximo martes'), ('wednesday', 'El próximo miércoles'), ('thursday', 'El próximo jueves'), ('friday', 'El próximo viernes'), ('next_week', 'La próxima semana'), ('flexible', 'Horario flexible')], default='asap', max_length=20, verbose_name='Cuándo prefieres que te contactemos'),
        ),
    ]
