# Generated by Django 4.2.20 on 2025-10-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0181_add_preferred_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
    ]
