# Generated by Django 4.2.20 on 2025-10-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0182_landingpagesubmission_cargo'),
    ]

    operations = [
    ]
