# Generated by Django 4.2.20 on 2025-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0183_auto_20251020_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagesubmission',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='landingpagesubmission',
            name='mensaje',
            field=models.TextField(help_text='Cuéntanos más sobre tus necesidades o proyecto', verbose_name='Mensaje o comentarios'),
        ),
        migrations.AlterField(
            model_name='landingpagesubmission',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
