# Generated by Django 4.2.20 on 2025-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0184_make_fields_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='contact_button_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clics en "Contactar"'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='meeting_button_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clics en "Planificar Reunión"'),
        ),
    ]
