# Generated by Django 4.2.20 on 2025-10-20 09:12
# Modified to be no-op due to duplicate fields with 0185

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0185_add_button_click_counters'),
    ]

    operations = [
        # No operations - fields already added in 0185
    ]
