# Generated by Django 4.2.20 on 2025-10-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0187_add_contact_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contact_date',
        ),
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contact_notes',
        ),
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contacted_by_phone',
        ),
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contacted_by_web',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_tracking_notes',
            field=models.TextField(blank=True, help_text='Notas sobre los contactos realizados', verbose_name='Notas de seguimiento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted_by_phone',
            field=models.BooleanField(default=False, help_text='Marcar si se contactó al cliente por teléfono', verbose_name='Contactado por teléfono'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted_by_web',
            field=models.BooleanField(default=False, help_text='Marcar si se contactó al cliente por web o email', verbose_name='Contactado por web/email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Fecha del último contacto realizado', null=True, verbose_name='Fecha del último contacto'),
        ),
    ]
