# Generated by Django 4.2.20 on 2025-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0187_add_contact_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='contacted_by_phone',
            field=models.BooleanField(default=False, help_text='Marcar si se contactó al cliente por teléfono', verbose_name='Contactado por teléfono'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='contacted_by_web',
            field=models.BooleanField(default=False, help_text='Marcar si se contactó al cliente por web o email', verbose_name='Contactado por web/email'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='contact_notes',
            field=models.TextField(blank=True, help_text='Notas sobre el contacto realizado', verbose_name='Notas de contacto'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='contact_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se realizó el contacto', null=True, verbose_name='Fecha de contacto'),
        ),
    ]
