# Generated by Django 4.2.20 on 2025-10-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0188_add_contact_tracking_fields'),
        ('tickets', '0188_move_contact_tracking_to_contact'),
    ]

    operations = [
    ]
