# Generated by Django 4.2.20 on 2025-10-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0189_merge_20251024_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contact_date',
        ),
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contact_notes',
        ),
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contacted_by_phone',
        ),
        migrations.RemoveField(
            model_name='landingpagesubmission',
            name='contacted_by_web',
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Número de secuencia de la solicitud', verbose_name='Secuencia')),
                ('title', models.CharField(help_text='Título de la solicitud', max_length=200, verbose_name='Título')),
                ('text', models.TextField(help_text='Descripción detallada de la solicitud', verbose_name='Texto')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud', verbose_name='Fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='draft', help_text='Estado actual de la solicitud', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Empleado',
                'verbose_name_plural': 'Solicitudes de Empleados',
                'ordering': ['-sequence', '-created_at'],
                'unique_together': {('sequence',)},
            },
        ),
    ]
