# Generated by Django 4.2.20 on 2025-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0190_remove_landingpagesubmission_contact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Valencia', help_text='Ciudad para mostrar información del clima', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='España', help_text='País para mostrar información del clima', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(default='ES', help_text='Código ISO de 2 letras del país (ej: ES, US, FR)', max_length=2, verbose_name='Código de país'),
        ),
    ]
