# Generated by Django 4.2.20 on 2025-10-24 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0191_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Número único auto-generado', unique=True, verbose_name='Número de Secuencia')),
                ('title', models.CharField(help_text='Título descriptivo del acuerdo interno', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del acuerdo interno', verbose_name='Descripción')),
                ('content', models.TextField(help_text='Contenido completo del acuerdo interno', verbose_name='Contenido')),
                ('agreement_type', models.CharField(choices=[('policy', 'Política'), ('procedure', 'Procedimiento'), ('contract', 'Contrato'), ('guideline', 'Directriz'), ('agreement', 'Acuerdo'), ('regulation', 'Reglamento')], default='agreement', max_length=20, verbose_name='Tipo de Acuerdo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('review', 'En Revisión'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('effective_date', models.DateField(blank=True, help_text='Fecha en que el acuerdo entra en vigencia', null=True, verbose_name='Fecha de Vigencia')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha en que el acuerdo expira (opcional)', null=True, verbose_name='Fecha de Expiración')),
                ('department', models.CharField(blank=True, help_text='Departamento al que aplica el acuerdo', max_length=100, verbose_name='Departamento')),
                ('applies_to_all', models.BooleanField(default=True, help_text='Si el acuerdo aplica a todos los empleados', verbose_name='Aplica a Todos')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas para facilitar búsquedas', max_length=500, verbose_name='Etiquetas')),
                ('version', models.CharField(default='1.0', help_text='Versión del acuerdo', max_length=20, verbose_name='Versión')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_agreements_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_agreements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Acuerdo Interno',
                'verbose_name_plural': 'Acuerdos Internos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'agreement_type'], name='tickets_int_status_0f5bfa_idx'), models.Index(fields=['effective_date', 'expiration_date'], name='tickets_int_effecti_3b51be_idx')],
            },
        ),
    ]
