# Generated by Django 4.2.20 on 2025-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0192_internalagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalagreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('active', 'Activo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
