# Generated by Django 4.2.20 on 2025-10-24 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0193_update_internal_agreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalagreement',
            name='signer_1',
            field=models.ForeignKey(blank=True, help_text='Usuario que firma el acuerdo como primer firmante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_agreements_signed_1', to=settings.AUTH_USER_MODEL, verbose_name='Primer Firmante'),
        ),
        migrations.AddField(
            model_name='internalagreement',
            name='signer_1_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el primer firmante firmó el acuerdo', null=True, verbose_name='Fecha de Firma 1'),
        ),
        migrations.AddField(
            model_name='internalagreement',
            name='signer_2',
            field=models.ForeignKey(blank=True, help_text='Usuario que firma el acuerdo como segundo firmante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_agreements_signed_2', to=settings.AUTH_USER_MODEL, verbose_name='Segundo Firmante'),
        ),
        migrations.AddField(
            model_name='internalagreement',
            name='signer_2_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el segundo firmante firmó el acuerdo', null=True, verbose_name='Fecha de Firma 2'),
        ),
    ]
