# Generated by Django 4.2.20 on 2025-10-24 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0195_fix_duplicate_button_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(unique=True, verbose_name='Secuencia')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plan de Capacitación',
                'verbose_name_plural': 'Planes de Capacitación',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Enlace')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('estimated_hours', models.PositiveIntegerField(default=1, verbose_name='Horas estimadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.trainingplan', verbose_name='Plan de Capacitación')),
            ],
            options={
                'verbose_name': 'Enlace de Capacitación',
                'verbose_name_plural': 'Enlaces de Capacitación',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='not_started', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_progress', to='tickets.trainingplan', verbose_name='Plan de Capacitación')),
            ],
            options={
                'verbose_name': 'Progreso de Capacitación',
                'verbose_name_plural': 'Progreso de Capacitaciones',
                'unique_together': {('employee', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeLinkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completado el')),
                ('time_spent_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo invertido (horas)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_progress', to='tickets.traininglink', verbose_name='Enlace')),
                ('training_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_links', to='tickets.employeetrainingprogress', verbose_name='Progreso de Capacitación')),
            ],
            options={
                'verbose_name': 'Progreso de Enlace',
                'verbose_name_plural': 'Progreso de Enlaces',
                'unique_together': {('employee', 'link')},
            },
        ),
    ]
