# Generated by Django 4.2.20 on 2025-10-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0196_trainingplan_traininglink_employeetrainingprogress_and_more'),
    ]

    operations = [
    ]
