# Generated by Django 4.2.20 on 2025-10-25 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0197_auto_20251024_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la recomendación', max_length=200, verbose_name='Título')),
                ('context_text', models.TextField(help_text='Contexto base que usará la IA para generar respuestas', verbose_name='Texto de Contexto')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, podrá ser usada para generar respuestas', verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Recomendación IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_case', models.TextField(help_text='Caso específico o situación del cliente enviada para análisis', verbose_name='Caso del Cliente')),
                ('ai_response', models.TextField(help_text='Respuesta generada por la IA basada en el contexto y caso', verbose_name='Respuesta de IA')),
                ('is_helpful', models.BooleanField(default=True, help_text='Calificación de utilidad de la respuesta', verbose_name='¿Fue útil?')),
                ('feedback', models.TextField(blank=True, help_text='Comentarios adicionales del usuario sobre la respuesta', verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de uso')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='tickets.airecommendation', verbose_name='Recomendación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation_usage', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Uso de Recomendación IA',
                'verbose_name_plural': 'Usos de Recomendaciones IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
