# Generated by Django 4.2.20 on 2025-10-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0198_airecommendation_airecommendationusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Vacaciones, Enfermedad, Permiso Personal', max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del tipo de ausencia', verbose_name='Descripción')),
                ('requires_documentation', models.BooleanField(default=False, help_text='Si se requiere documentación de respaldo (ej: certificado médico)', verbose_name='Requiere Documentación')),
                ('is_paid', models.BooleanField(default=True, help_text='Si la ausencia es con goce de sueldo', verbose_name='Es Remunerado')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, help_text='Límite anual de días para este tipo de ausencia (opcional)', null=True, verbose_name='Máximo Días por Año')),
                ('color', models.CharField(default='#007bff', help_text='Color para mostrar en el calendario (formato hex: #RRGGBB)', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, help_text='Si este tipo de ausencia está disponible para uso', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Ausencia',
                'verbose_name_plural': 'Tipos de Ausencias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Primer día de ausencia', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Último día de ausencia', verbose_name='Fecha de Fin')),
                ('reason', models.TextField(help_text='Explicación detallada del motivo de la ausencia', verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('documentation_file', models.FileField(blank=True, help_text='Archivo de respaldo (certificado médico, etc.)', null=True, upload_to='absence_documentation/%Y/%m/', verbose_name='Documentación')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('rejection_reason', models.TextField(blank=True, help_text='Razón por la cual se rechazó la ausencia', verbose_name='Motivo de rechazo')),
                ('notes', models.TextField(blank=True, help_text='Comentarios internos sobre la ausencia', verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='tickets.absencetype', verbose_name='Tipo de Ausencia')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Ausencia de Empleado',
                'verbose_name_plural': 'Ausencias de Empleados',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
