# Generated by Django 4.2.20 on 2025-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0199_absencetype_employeeabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='lost_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total de horas laborales perdidas por la ausencia', max_digits=8, verbose_name='Horas Perdidas'),
        ),
    ]
