# Generated by Django 4.2.20 on 2025-10-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0200_add_lost_hours_to_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del protocolo empresarial', max_length=200, verbose_name='Título del Protocolo')),
                ('content', models.TextField(help_text='Contenido completo del protocolo. Puedes usar formato básico.', verbose_name='Contenido del Protocolo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el protocolo está activo y disponible', verbose_name='Activo')),
                ('version', models.CharField(default='1.0', help_text='Versión del protocolo (ej: 1.0, 1.1, 2.0)', max_length=10, verbose_name='Versión')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Protocolo de Empresa',
                'verbose_name_plural': 'Protocolos de Empresa',
                'ordering': ['-created_at'],
            },
        ),
    ]
