# Generated by Django 4.2.20 on 2025-10-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0201_add_company_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprotocol',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este protocolo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='tickets.company', verbose_name='Empresa'),
        ),
    ]
