# Generated by Django 4.2.20 on 2025-10-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0202_add_company_to_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la queja o sugerencia', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del problema o sugerencia', verbose_name='Descripción')),
                ('type', models.CharField(choices=[('complaint', 'Queja'), ('suggestion', 'Sugerencia'), ('feedback', 'Retroalimentación'), ('improvement', 'Mejora'), ('quality_issue', 'Problema de Calidad')], default='complaint', help_text='Tipo de reporte: queja, sugerencia, etc.', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Nivel de prioridad del reporte', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('pending_review', 'Pendiente de Revisión'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('rejected', 'Rechazado')], default='open', help_text='Estado actual del reporte', max_length=20, verbose_name='Estado')),
                ('contact_email', models.EmailField(blank=True, help_text='Email del cliente o usuario que reporta (opcional)', max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, help_text='Teléfono del cliente o usuario que reporta (opcional)', max_length=20, verbose_name='Teléfono de contacto')),
                ('resolution', models.TextField(blank=True, help_text='Descripción de cómo se resolvió la queja o implementó la sugerencia', verbose_name='Resolución')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('attachment', models.FileField(blank=True, help_text='Imagen, documento o archivo relacionado con la queja', null=True, upload_to='qa_complaints/%Y/%m/', verbose_name='Archivo adjunto')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario responsable de resolver la queja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('company', models.ForeignKey(help_text='Empresa asociada a esta queja o sugerencia', on_delete=django.db.models.deletion.CASCADE, related_name='qa_complaints', to='tickets.company', verbose_name='Empresa')),
                ('reported_by', models.ForeignKey(help_text='Usuario que reportó la queja o sugerencia', on_delete=django.db.models.deletion.CASCADE, related_name='reported_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Queja/Sugerencia QA',
                'verbose_name_plural': 'Quejas/Sugerencias QA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido del comentario o nota', verbose_name='Comentario')),
                ('is_internal', models.BooleanField(default=False, help_text='Marca si es un comentario interno (no visible para el cliente)', verbose_name='Comentario interno')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.qacomplaint', verbose_name='Queja/Sugerencia')),
            ],
            options={
                'verbose_name': 'Comentario QA',
                'verbose_name_plural': 'Comentarios QA',
                'ordering': ['created_at'],
            },
        ),
    ]
