# Generated by Django 4.2.20 on 2025-10-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0203_add_qa_complaint_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='qacomplaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que resolvió la queja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por'),
        ),
    ]
