# Generated by Django 4.2.20 on 2025-10-25 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0204_add_resolved_by_to_qa_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprotocol',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Permite que este protocolo sea accesible públicamente sin autenticación', verbose_name='Compartir públicamente'),
        ),
        migrations.AddField(
            model_name='companyprotocol',
            name='public_shared_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se compartió públicamente por primera vez', null=True, verbose_name='Compartido públicamente en'),
        ),
        migrations.AddField(
            model_name='companyprotocol',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador único para acceso público', unique=True, verbose_name='UUID público'),
        ),
    ]
