# Generated by Django 4.2.20 on 2025-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0205_companyprotocol_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprotocol',
            name='public_views_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que se ha visto públicamente este protocolo', verbose_name='Vistas públicas'),
        ),
    ]
