# Generated by Django 4.2.20 on 2025-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0206_companyprotocol_public_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='theme',
            field=models.CharField(choices=[('blue', 'Azul Clásico'), ('green', 'Verde Moderno'), ('sunset', 'Sunset'), ('ocean', 'Océano'), ('purple', 'Púrpura'), ('pink', 'Rosa'), ('minimal', 'Minimal')], default='blue', max_length=20, verbose_name='Tema visual'),
        ),
    ]
