# Generated by Django 4.2.20 on 2025-10-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0207_form_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de análisis')),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Puntuación general')),
                ('problems', models.JSONField(default=list, help_text='Lista de problemas encontrados en formato JSON', verbose_name='Problemas identificados')),
                ('improvements', models.JSONField(default=list, help_text='Lista de mejoras sugeridas en formato JSON', verbose_name='Mejoras sugeridas')),
                ('strengths', models.JSONField(default=list, help_text='Lista de fortalezas identificadas', verbose_name='Fortalezas')),
                ('main_recommendation', models.TextField(verbose_name='Recomendación principal')),
                ('total_responses', models.IntegerField(verbose_name='Total de respuestas analizadas')),
                ('analysis_version', models.CharField(default='1.0', max_length=10, verbose_name='Versión del análisis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analizado por')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='tickets.form', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
