# Generated by Django 4.2.20 on 2025-10-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0208_formaianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='Clave alfanumérica de 12 caracteres en mayúsculas', max_length=12, unique=True, verbose_name='Clave de Licencia')),
                ('product', models.CharField(max_length=200, verbose_name='Producto')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('suspended', 'Suspendida'), ('revoked', 'Revocada')], default='active', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la licencia', verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID Público')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
