# Generated by Django 4.2.20 on 2025-10-25 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0209_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del activo', max_length=200, verbose_name='Nombre del Activo')),
                ('manufacturer', models.CharField(help_text='Marca o fabricante del activo', max_length=100, verbose_name='Fabricante')),
                ('description', models.TextField(help_text='Descripción detallada del activo', verbose_name='Descripción')),
                ('serial_number', models.CharField(help_text='Número de serie único del activo', max_length=100, unique=True, verbose_name='Número de Serie')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('maintenance', 'En Mantenimiento'), ('retired', 'Dado de Baja'), ('lost', 'Perdido'), ('damaged', 'Dañado')], default='available', max_length=20, verbose_name='Estado')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('location', models.CharField(blank=True, help_text='Ubicación física del activo', max_length=200, verbose_name='Ubicación')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el activo', verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='tickets.employee', verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('assigned', 'Asignado'), ('unassigned', 'Desasignado'), ('transferred', 'Transferido'), ('maintenance', 'Enviado a Mantenimiento'), ('returned', 'Devuelto de Mantenimiento'), ('retired', 'Dado de Baja'), ('status_changed', 'Cambio de Estado')], max_length=20, verbose_name='Acción')),
                ('previous_status', models.CharField(blank=True, choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('maintenance', 'En Mantenimiento'), ('retired', 'Dado de Baja'), ('lost', 'Perdido'), ('damaged', 'Dañado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(blank=True, choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('maintenance', 'En Mantenimiento'), ('retired', 'Dado de Baja'), ('lost', 'Perdido'), ('damaged', 'Dañado')], max_length=20, null=True, verbose_name='Nuevo Estado')),
                ('reason', models.TextField(blank=True, help_text='Motivo del cambio o acción', verbose_name='Motivo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.asset', verbose_name='Activo')),
                ('new_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_new', to='tickets.employee', verbose_name='Nuevo Empleado')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_actions', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('previous_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_previous', to='tickets.employee', verbose_name='Empleado Anterior')),
            ],
            options={
                'verbose_name': 'Historial de Activo',
                'verbose_name_plural': 'Historiales de Activos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['asset', '-date'], name='tickets_ass_asset_i_8e7e60_idx'), models.Index(fields=['action'], name='tickets_ass_action_280732_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='tickets_ass_serial__522d94_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='tickets_ass_status_7ecaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['assigned_to'], name='tickets_ass_assigne_2e882c_idx'),
        ),
    ]
