# Generated by Django 4.2.20 on 2025-10-25 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0210_asset_assethistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='new_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_new', to=settings.AUTH_USER_MODEL, verbose_name='Nuevo Usuario'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='previous_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_previous', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Anterior'),
        ),
    ]
