# Generated by Django 4.2.20 on 2025-10-25 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0211_alter_asset_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de lo que quieres lograr', max_length=200, verbose_name='Título del Objetivo')),
                ('objective', models.TextField(help_text='Describe claramente qué quieres lograr', verbose_name='Objetivo')),
                ('current_state', models.TextField(help_text='Describe dónde estás ahora en relación a tu objetivo', verbose_name='Estado Actual')),
                ('context', models.TextField(help_text='Proporciona contexto adicional relevante (experiencia, recursos, limitaciones, etc.)', verbose_name='Contexto')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Estado')),
                ('is_private', models.BooleanField(default=False, help_text='Si está marcado, solo tú podrás ver este tutor', verbose_name='Privado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutors', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tutor IA',
                'verbose_name_plural': 'Tutores IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITutorProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_description', models.TextField(help_text='Describe qué has logrado desde tu último reporte', verbose_name='Descripción del Avance')),
                ('challenges', models.TextField(blank=True, help_text='Describe los obstáculos o dificultades que has enfrentado (opcional)', verbose_name='Desafíos Encontrados')),
                ('ai_feedback', models.TextField(blank=True, help_text='Recomendaciones y consejos generados por la IA', verbose_name='Retroalimentación de la IA')),
                ('ai_recommendations', models.TextField(blank=True, help_text='Sugerencias específicas para mejorar', verbose_name='Recomendaciones de Mejora')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Reporte')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_progress_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='tickets.aitutor', verbose_name='Tutor IA')),
            ],
            options={
                'verbose_name': 'Reporte de Progreso',
                'verbose_name_plural': 'Reportes de Progreso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITutorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tutor_attachments/%Y/%m/', verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño en bytes', verbose_name='Tamaño del Archivo')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo de Archivo')),
                ('description', models.CharField(blank=True, help_text='Descripción opcional del archivo', max_length=500, verbose_name='Descripción')),
                ('ai_analysis', models.TextField(blank=True, help_text='Análisis del archivo generado por la IA', verbose_name='Análisis de la IA')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Subida')),
                ('progress_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.aitutorprogressreport', verbose_name='Reporte de Progreso')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.aitutor', verbose_name='Tutor IA')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto del Tutor',
                'verbose_name_plural': 'Adjuntos del Tutor',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aitutorprogressreport',
            index=models.Index(fields=['tutor'], name='tickets_ait_tutor_i_9b35e4_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutorprogressreport',
            index=models.Index(fields=['created_by'], name='tickets_ait_created_cffdfb_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutorattachment',
            index=models.Index(fields=['tutor'], name='tickets_ait_tutor_i_df1776_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutorattachment',
            index=models.Index(fields=['progress_report'], name='tickets_ait_progres_ffbc87_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutorattachment',
            index=models.Index(fields=['uploaded_by'], name='tickets_ait_uploade_e0cbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutor',
            index=models.Index(fields=['created_by'], name='tickets_ait_created_c91c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutor',
            index=models.Index(fields=['status'], name='tickets_ait_status_629675_idx'),
        ),
        migrations.AddIndex(
            model_name='aitutor',
            index=models.Index(fields=['is_private'], name='tickets_ait_is_priv_c016e0_idx'),
        ),
    ]
