# Generated by Django 4.2.20 on 2025-10-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0212_aitutor_aitutorprogressreport_aitutorattachment_and_more'),
    ]

    operations = [
    ]
