# Generated by Django 4.2.20 on 2025-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0213_auto_20251025_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitutor',
            name='tutor_persona',
            field=models.TextField(default='Un experimentado mentor y profesor', help_text='Describe qué tipo de tutor quieres (ej: un experimentado profesor de Django, un mentor de carrera, etc.)', verbose_name='Personalidad del Tutor'),
        ),
    ]
