# Generated by Django 4.2.20 on 2025-10-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0214_aitutor_tutor_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTimeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único para acceso público', max_length=100, unique=True, verbose_name='Token de Acceso')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, el usuario puede usar el acceso público', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('require_location', models.BooleanField(default=False, help_text='Si está activado, registrará la ubicación GPS al marcar entrada/salida', verbose_name='Requiere ubicación')),
                ('allowed_ip_addresses', models.TextField(blank=True, help_text='Lista de IPs permitidas separadas por comas (opcional)', verbose_name='IPs permitidas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_time_access', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso Público de Horario',
                'verbose_name_plural': 'Accesos Públicos de Horario',
                'ordering': ['-created_at'],
            },
        ),
    ]
