# Generated by Django 4.2.20 on 2025-10-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0215_publictimeaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmanager',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='Marcar como URL principal para mostrar en el dashboard', verbose_name='URL Principal'),
        ),
        migrations.AddIndex(
            model_name='urlmanager',
            index=models.Index(fields=['is_principal', 'is_active'], name='tickets_url_is_prin_a2b0d1_idx'),
        ),
    ]
