# Generated by Django 4.2.20 on 2025-10-26 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0216_urlmanager_is_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la rendición de gastos', max_length=200, verbose_name='Título de la rendición')),
                ('description', models.TextField(blank=True, help_text='Descripción general de los gastos', null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('paid', 'Pagado')], default='draft', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(help_text='Fecha de inicio del período de gastos', verbose_name='Fecha inicio')),
                ('end_date', models.DateField(help_text='Fecha de fin del período de gastos', verbose_name='Fecha fin')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto total')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expense_reports', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='tickets.company', verbose_name='Empresa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Rendición de Gastos',
                'verbose_name_plural': 'Rendiciones de Gastos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha del gasto')),
                ('category', models.CharField(choices=[('food', 'Comida'), ('transport', 'Transporte'), ('hotel', 'Hotel/Alojamiento'), ('fuel', 'Combustible'), ('materials', 'Materiales'), ('entertainment', 'Entretenimiento'), ('communication', 'Comunicaciones'), ('office', 'Oficina/Suministros'), ('medical', 'Gastos médicos'), ('training', 'Capacitación'), ('other', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción del gasto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor/Comercio')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Comprobante/Recibo')),
                ('is_reimbursable', models.BooleanField(default=True, help_text='Marcar si este gasto debe ser reembolsado', verbose_name='Reembolsable')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='tickets.expensereport', verbose_name='Rendición de gastos')),
            ],
            options={
                'verbose_name': 'Item de Gasto',
                'verbose_name_plural': 'Items de Gastos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('is_internal', models.BooleanField(default=False, help_text='Solo visible para administradores', verbose_name='Comentario interno')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.expensereport', verbose_name='Rendición de gastos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de Gasto',
                'verbose_name_plural': 'Comentarios de Gastos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['employee', 'status'], name='tickets_exp_employe_45d6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['company', 'status'], name='tickets_exp_company_d31a73_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['status', 'created_at'], name='tickets_exp_status_bc91d7_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['expense_report', 'category'], name='tickets_exp_expense_23ff2b_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['date', 'category'], name='tickets_exp_date_95396e_idx'),
        ),
    ]
