# Generated by Django 4.2.20 on 2025-10-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0217_expensereport_expenseitem_expensecomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la reunión')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración en minutos')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('meeting_url', models.URLField(blank=True, null=True, verbose_name='URL de la reunión')),
                ('recording_file', models.FileField(blank=True, help_text='Formatos soportados: MP4, AVI, MOV, MP3, WAV, M4A', null=True, upload_to='meeting_recordings/', verbose_name='Archivo de grabación')),
                ('transcription_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Falló')], default='pending', max_length=20, verbose_name='Estado de transcripción')),
                ('transcription_text', models.TextField(blank=True, null=True, verbose_name='Transcripción')),
                ('transcription_confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza de transcripción (%)')),
                ('transcription_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de transcripción')),
                ('transcription_summary', models.TextField(blank=True, null=True, verbose_name='Resumen de transcripción')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='Resumen generado por IA')),
                ('key_points', models.TextField(blank=True, null=True, verbose_name='Puntos clave')),
                ('action_items', models.TextField(blank=True, null=True, verbose_name='Elementos de acción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_video_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('participants', models.ManyToManyField(blank=True, related_name='attended_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Reunión de Video',
                'verbose_name_plural': 'Reuniones de Video',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido de la nota')),
                ('is_private', models.BooleanField(default=False, help_text='Solo visible para el autor', verbose_name='Nota privada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.videomeeting', verbose_name='Reunión')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota de Reunión',
                'verbose_name_plural': 'Notas de Reunión',
                'ordering': ['-created_at'],
            },
        ),
    ]
