# Generated by Django 4.2.20 on 2025-10-26 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0218_videomeeting_meetingnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomeeting',
            name='recording_file',
            field=models.FileField(blank=True, help_text='Formatos soportados: MP4, AVI, MOV, MP3, WAV, M4A, WebM', null=True, upload_to='meeting_recordings/', verbose_name='Archivo de grabación'),
        ),
        migrations.CreateModel(
            name='QuoteGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del generador')),
                ('topic', models.CharField(help_text='Ej: "citas de Einstein sobre el amor", "frases motivacionales de líderes", etc.', max_length=500, verbose_name='Tema de las citas')),
                ('generated_quotes', models.TextField(blank=True, help_text='Almacena las citas en formato JSON', verbose_name='Citas generadas (JSON)')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, las citas aparecerán en el dashboard', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Generador de Citas',
                'verbose_name_plural': 'Generadores de Citas',
                'ordering': ['-created_at'],
            },
        ),
    ]
