# Generated by Django 4.2.20 on 2025-10-26 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0219_alter_videomeeting_recording_file_quotegenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo para la cuenta regresiva', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del evento', verbose_name='Descripción')),
                ('target_date', models.DateTimeField(help_text='Fecha y hora del evento', verbose_name='Fecha objetivo')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, la cuenta regresiva será visible', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cuenta Regresiva',
                'verbose_name_plural': 'Cuentas Regresivas',
                'ordering': ['target_date'],
            },
        ),
    ]
