# Generated by Django 4.2.20 on 2025-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0220_countdowntimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdowntimer',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Si está marcada como privada, solo el creador podrá verla', verbose_name='Privada'),
        ),
    ]
