# Generated by Django 4.2.20 on 2025-10-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0221_countdowntimer_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Si está marcada, solo tú podrás ver, editar y eliminar esta nota', verbose_name='Nota privada'),
        ),
    ]
