# Generated by Django 4.2.20 on 2025-10-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0222_alter_usernote_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa asociada a esta nota', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa'),
        ),
    ]
