# Generated by Django 4.2.20 on 2025-10-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0223_usernote_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='is_shareable',
            field=models.BooleanField(default=False, help_text='Si la nota puede ser compartida mediante un enlace público', verbose_name='Compartible públicamente'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='share_token',
            field=models.CharField(blank=True, help_text='Token único para compartir la nota públicamente', max_length=50, null=True, unique=True, verbose_name='Token de compartir'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Veces que la nota ha sido vista mediante enlace público', verbose_name='Número de visualizaciones'),
        ),
    ]
