# Generated by Django 4.2.20 on 2025-10-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0224_usernote_is_shareable_usernote_share_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del procedimiento', max_length=200, verbose_name='Título')),
                ('url', models.URLField(blank=True, help_text='Enlace externo relacionado al procedimiento (opcional)', verbose_name='URL')),
                ('attachment', models.FileField(help_text='Archivo del procedimiento (PDF, DOC, etc.)', upload_to='procedures/', verbose_name='Adjunto')),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Orden de visualización del procedimiento', verbose_name='Secuencia')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del procedimiento', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si está marcado, el procedimiento será visible', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_procedures', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['sequence', 'title'],
            },
        ),
    ]
