# Generated by Django 4.2.20 on 2025-10-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0225_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el procedimiento (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='tickets.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='attachment',
            field=models.FileField(blank=True, help_text='Archivo del procedimiento (PDF, DOC, etc.) - Opcional', upload_to='procedures/', verbose_name='Adjunto'),
        ),
    ]
