# Generated by Django 4.2.20 on 2025-10-27 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0226_procedure_company_alter_procedure_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting_recordings/', verbose_name='Archivo adjunto')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.videomeeting', verbose_name='Reunión')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de Reunión',
                'verbose_name_plural': 'Adjuntos de Reunión',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
