# Generated by Django 4.2.20 on 2025-10-27 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0227_meetingattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('effective_date', models.DateField(verbose_name='Fecha de vigencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Condición de Uso',
                'verbose_name_plural': 'Condiciones de Uso',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
