# Generated by Django 4.2.20 on 2025-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0228_termsofuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='erp',
            field=models.CharField(blank=True, help_text='Sistema ERP actual del contacto', max_length=100, null=True, verbose_name='ERP'),
        ),
    ]
