# Generated by Django 4.2.20 on 2025-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0229_contact_erp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmanager',
            name='encrypted_password',
            field=models.TextField(blank=True, help_text='Contraseña almacenada de forma segura', null=True, verbose_name='Contraseña encriptada'),
        ),
        migrations.AlterField(
            model_name='urlmanager',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre de usuario para acceder', max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
