# Generated by Django 4.2.20 on 2025-10-28 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0232_migrate_user_field_to_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='URL, texto o datos para generar el QR', verbose_name='Contenido')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('qr_type', models.CharField(choices=[('url', 'URL/Enlace'), ('text', 'Texto'), ('email', 'Email'), ('phone', 'Teléfono'), ('sms', 'SMS'), ('wifi', 'WiFi'), ('vcard', 'Tarjeta de Contacto')], default='text', max_length=20, verbose_name='Tipo de QR')),
                ('size', models.IntegerField(default=256, verbose_name='Tamaño (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
