# Generated by Django 4.2.20 on 2025-10-28 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0233_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID público'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='public_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas públicas'),
        ),
    ]
