# Generated by Django 4.2.20 on 2025-10-28 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0234_qrcode_is_public_qrcode_public_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='public_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='UUID público'),
        ),
    ]
