# Generated by Django 4.2.20 on 2025-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0235_alter_qrcode_public_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='public_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Token público'),
        ),
    ]
