# Generated by Django 4.2.20 on 2025-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0236_add_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='public_token',
            field=models.CharField(max_length=32, null=True, blank=True, unique=True, verbose_name='Token público'),
        ),
    ]
