# Generated by Django 4.2.20 on 2025-10-28 13:55

from django.db import migrations, models, connection


def check_and_add_public_token(apps, schema_editor):
    """Agregar public_token solo si no existe"""
    with connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='tickets_qrcode' AND column_name='public_token';
        """)
        
        column_exists = cursor.fetchone() is not None
        
        if not column_exists:
            # Solo agregar si no existe
            cursor.execute("""
                ALTER TABLE tickets_qrcode 
                ADD COLUMN public_token VARCHAR(32) NULL UNIQUE;
            """)
            print("✅ Columna public_token agregada exitosamente")
        else:
            print("⚠️ Columna public_token ya existe, saltando...")


def reverse_add_public_token(apps, schema_editor):
    """Reversar la operación si es necesario"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='tickets_qrcode' AND column_name='public_token';
        """)
        
        column_exists = cursor.fetchone() is not None
        
        if column_exists:
            cursor.execute("ALTER TABLE tickets_qrcode DROP COLUMN public_token;")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0236_add_public_token'),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_public_token,
            reverse_add_public_token,
        ),
    ]
