# Generated by Django 4.2.20 on 2025-10-28 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0237_auto_20251028_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Tarea')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tarea Rápida',
                'verbose_name_plural': 'Tareas Rápidas',
                'ordering': ['completed', '-created_at'],
                'indexes': [models.Index(fields=['created_by', 'completed'], name='tickets_qui_created_df6627_idx'), models.Index(fields=['created_at'], name='tickets_qui_created_ac6590_idx')],
            },
        ),
    ]
