# Generated by Django 4.2.20 on 2025-10-29 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0239_fix_duplicate_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Secuencia')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='draft', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='tickets.company', verbose_name='Empresa')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sequence'], name='tickets_quo_sequenc_32bced_idx'), models.Index(fields=['company'], name='tickets_quo_company_aa1d76_idx'), models.Index(fields=['salesperson'], name='tickets_quo_salespe_72691e_idx'), models.Index(fields=['date'], name='tickets_quo_date_65bfd5_idx'), models.Index(fields=['status'], name='tickets_quo_status_5a4cb8_idx'), models.Index(fields=['created_at'], name='tickets_quo_created_b2f6e2_idx')],
            },
        ),
    ]
