# Generated by Django 4.2.20 on 2025-10-29 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0240_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento sobre el precio unitario', max_digits=5, verbose_name='Descuento (%)')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional o personalizada del producto', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.product', verbose_name='Producto')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tickets.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Línea de Cotización',
                'verbose_name_plural': 'Líneas de Cotización',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['quotation'], name='tickets_quo_quotati_286726_idx'), models.Index(fields=['product'], name='tickets_quo_product_ddc037_idx')],
            },
        ),
    ]
