# Generated by Django 4.2.20 on 2025-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0241_quotationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='public_token',
            field=models.CharField(blank=True, help_text='Token único para compartir la cotización públicamente', max_length=50, null=True, unique=True, verbose_name='Token Público'),
        ),
    ]
