# Generated by Django 4.2.20 on 2025-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0242_quotation_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_response_comments',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del cliente', verbose_name='Comentarios del Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_response_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el cliente respondió', null=True, verbose_name='Fecha de Respuesta del Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_response_email',
            field=models.EmailField(blank=True, help_text='Email de quien respondió a la cotización', max_length=254, verbose_name='Email del Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_response_name',
            field=models.CharField(blank=True, help_text='Nombre de quien respondió a la cotización', max_length=200, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_status',
            field=models.CharField(choices=[('pending', 'Pendiente de Respuesta'), ('accepted', 'Aceptada por Cliente'), ('rejected', 'Rechazada por Cliente')], default='pending', help_text='Estado de la respuesta del cliente a la cotización', max_length=20, verbose_name='Estado del Cliente'),
        ),
    ]
