# Generated by Django 4.2.20 on 2025-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0243_quotation_client_response_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Fecha límite para aceptar esta cotización', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
