# Generated by Django 4.2.20 on 2025-10-29 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0244_quotation_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(help_text='Token único para el enlace público', max_length=50, unique=True, verbose_name='Token Público')),
                ('title', models.CharField(help_text='Título descriptivo para el cliente', max_length=200, verbose_name='Título del Enlace')),
                ('description', models.TextField(blank=True, help_text='Descripción que verá el cliente al acceder al enlace', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si el enlace está activo y acepta nuevas solicitudes', verbose_name='Activo')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Cuántas veces se ha visitado el enlace', verbose_name='Número de Vistas')),
                ('conversions_count', models.PositiveIntegerField(default=0, help_text='Cuántas cotizaciones se han generado desde este enlace', verbose_name='Conversiones')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_templates', to='tickets.quotation', verbose_name='Cotización Plantilla')),
            ],
            options={
                'verbose_name': 'Plantilla de Cotización Pública',
                'verbose_name_plural': 'Plantillas de Cotización Públicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationTemplateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del Cliente')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa del Cliente')),
                ('client_comments', models.TextField(blank=True, verbose_name='Comentarios del Cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesada'), ('quoted', 'Cotizada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('generated_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_requests', to='tickets.quotation', verbose_name='Cotización Generada')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_template_requests', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tickets.quotationtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Solicitud de Plantilla',
                'verbose_name_plural': 'Solicitudes de Plantillas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template'], name='tickets_quo_templat_d5279f_idx'), models.Index(fields=['status'], name='tickets_quo_status_480efa_idx'), models.Index(fields=['created_at'], name='tickets_quo_created_e59ba2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quotationtemplate',
            index=models.Index(fields=['public_token'], name='tickets_quo_public__00985b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationtemplate',
            index=models.Index(fields=['is_active'], name='tickets_quo_is_acti_22f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationtemplate',
            index=models.Index(fields=['created_at'], name='tickets_quo_created_3a6345_idx'),
        ),
    ]
