# Generated by Django 4.2.20 on 2025-10-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0245_quotationtemplate_quotationtemplaterequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='service_end_date',
            field=models.DateField(blank=True, help_text='Fecha estimada de finalización del servicio (opcional)', null=True, verbose_name='Fecha de Fin del Servicio'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='service_start_date',
            field=models.DateField(blank=True, help_text='Fecha en que comenzará el servicio (opcional)', null=True, verbose_name='Fecha de Inicio del Servicio'),
        ),
    ]
