# Generated by Django 4.2.20 on 2025-10-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0246_add_service_dates_to_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='end_reason',
            field=models.CharField(
                blank=True,
                choices=[('comer', 'Comer'), ('fin_jornada', 'Fin de Jornada'), ('otro', 'Otro')],
                help_text='Motivo por el cual se finaliza la jornada',
                max_length=20,
                null=True,
                verbose_name='Causa de finalización'
            ),
        ),
    ]
