# Generated by Django 4.2.20 on 2025-10-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0249_contactcomment_contactattachment'),
    ]

    operations = [
    ]
