# Generated by Django 4.2.20 on 2025-10-30 19:28

from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0251_contact_comments_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactattachment',
            name='file',
            field=models.FileField(upload_to=tickets.models.contact_attachment_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='opportunityactivity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.opportunity', verbose_name='Oportunidad'),
        ),
    ]
