# Generated by Django 4.2.20 on 2025-10-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0252_alter_contactattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityactivity',
            name='opportunity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='activities',
                to='tickets.opportunity',
                verbose_name='Oportunidad'
            ),
        ),
    ]
