# Generated by Django 4.2.20 on 2025-10-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0253_auto_20251030_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityactivity',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contacto relacionado con esta actividad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.contact', verbose_name='Contacto'),
        ),
    ]
