# Generated by Django 4.2.20 on 2025-10-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0254_opportunityactivity_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, help_text='País del contacto', max_length=100, null=True, verbose_name='País'),
        ),
    ]
