# Generated by Django 4.2.20 on 2025-10-30 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0255_contact_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Número de secuencia de la pregunta', verbose_name='Secuencia')),
                ('question', models.TextField(help_text='Contenido de la pregunta', verbose_name='Pregunta')),
                ('answer', models.TextField(blank=True, help_text='Respuesta a la pregunta', null=True, verbose_name='Respuesta')),
                ('person_name', models.CharField(help_text='Nombre completo de quien hace la pregunta', max_length=200, verbose_name='Nombre de la persona')),
                ('person_email', models.EmailField(help_text='Correo electrónico de quien hace la pregunta', max_length=254, verbose_name='Email de la persona')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_questions_answered', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('company', models.ForeignKey(help_text='Empresa asociada a la pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='crm_questions', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_questions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Pregunta CRM',
                'verbose_name_plural': 'Preguntas CRM',
                'ordering': ['sequence', '-created_at'],
                'unique_together': {('company', 'sequence')},
            },
        ),
    ]
