# Generated by Django 4.2.20 on 2025-10-31 11:49

from django.db import migrations, models
import uuid


def populate_uuid(apps, schema_editor):
    """Poblar UUIDs únicos para empresas existentes"""
    Company = apps.get_model('tickets', 'Company')
    for company in Company.objects.all():
        company.uuid = uuid.uuid4()
        company.save()


def reverse_populate_uuid(apps, schema_editor):
    """Reverso de la función populate_uuid"""
    # No hacemos nada en el reverso
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0256_crmquestion'),
    ]

    operations = [
        # Primero agregamos el campo que permite null
        migrations.AddField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Identificador único para URLs públicas', null=True, verbose_name='UUID público'),
        ),
        # Luego poblamos los valores
        migrations.RunPython(populate_uuid, reverse_populate_uuid),
        # Finalmente hacemos el campo unique
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Identificador único para URLs públicas', null=True, unique=True, verbose_name='UUID público'),
        ),
    ]