# Generated by Django 4.2.20 on 2025-10-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0257_company_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó la pregunta (NULL para preguntas públicas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_questions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
