# Generated by Django 4.2.20 on 2025-10-31 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0258_alter_crmquestion_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Número secuencial de la reunión', verbose_name='Secuencia')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la reunión', verbose_name='Fecha')),
                ('description', models.TextField(help_text='Descripción de lo que se vio en la reunión', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(help_text='Empresa para la cual se realiza la reunión', on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la reunión', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reunión de Soporte',
                'verbose_name_plural': 'Reuniones de Soporte',
                'ordering': ['company', '-sequence'],
                'unique_together': {('company', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='SupportMeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción detallada del punto', verbose_name='Descripción del punto')),
                ('is_selected', models.BooleanField(default=False, help_text='Marcar para crear como ticket', verbose_name='Seleccionado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_meeting_points', to='tickets.supportmeeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Punto de Reunión',
                'verbose_name_plural': 'Puntos de Reunión',
                'ordering': ['created_at'],
            },
        ),
    ]
