# Generated by Django 4.2.20 on 2025-10-31 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0259_supportmeeting_supportmeetingpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMeetingPublicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de acceso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('show_company_meetings', models.BooleanField(default=True, help_text='Si está marcado, se mostrarán todas las reuniones públicas de la empresa', verbose_name='Mostrar otras reuniones de la empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Número de accesos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_link', to='tickets.supportmeeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Enlace Público de Reunión',
                'verbose_name_plural': 'Enlaces Públicos de Reuniones',
                'ordering': ['-created_at'],
            },
        ),
    ]
