# Generated by Django 4.2.20 on 2025-10-31 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0260_supportmeetingpubliclink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('frequency', models.PositiveIntegerField(help_text='Cada cuántas unidades de tiempo se ejecuta', verbose_name='Frecuencia')),
                ('frequency_unit', models.CharField(choices=[('minute', 'Minuto'), ('hour', 'Hora'), ('day', 'Día'), ('month', 'Mes')], default='hour', max_length=10, verbose_name='Unidad de Frecuencia')),
                ('code', models.TextField(help_text='Código Python que se ejecutará en cada iteración', verbose_name='Código a Ejecutar')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('last_result', models.TextField(blank=True, help_text='Resultado de la última ejecución', verbose_name='Último Resultado')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Ejecuciones Exitosas')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ejecuciones con Error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ejecutado en')),
                ('status', models.CharField(choices=[('success', 'Exitosa'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=10, verbose_name='Estado')),
                ('result', models.TextField(blank=True, verbose_name='Resultado')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Ejecución (segundos)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tickets.scheduledtask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Ejecución de Tarea',
                'verbose_name_plural': 'Ejecuciones de Tareas',
                'ordering': ['-executed_at'],
            },
        ),
    ]
