# Generated by Django 4.2.20 on 2025-10-31 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0261_scheduledtask_scheduledtaskexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de modificación')),
                ('field_name', models.CharField(max_length=50, verbose_name='Campo modificado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('change_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón del cambio')),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.timeentry', verbose_name='Registro de Tiempo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó')),
            ],
            options={
                'verbose_name': 'Log de Auditoría de Tiempo',
                'verbose_name_plural': 'Logs de Auditoría de Tiempo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
