# Generated by Django 4.2.20 on 2025-11-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0262_timeentryauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmeetingpoint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado actual del punto', max_length=20, verbose_name='Estado'),
        ),
    ]
