# Generated by Django 4.2.20 on 2025-11-18 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0263_supportmeetingpoint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha del clic')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='Referer')),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='tickets.shorturl', verbose_name='URL Corta')),
            ],
            options={
                'verbose_name': 'Clic de URL Corta',
                'verbose_name_plural': 'Clics de URLs Cortas',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['short_url', '-clicked_at'], name='tickets_sho_short_u_6104d4_idx'), models.Index(fields=['country', '-clicked_at'], name='tickets_sho_country_1a1087_idx')],
            },
        ),
    ]
