# Generated by Django 4.2.20 on 2025-11-19 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0264_shorturlclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='QARating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('sad', '😞 Triste'), ('neutral', '😐 Neutro'), ('happy', '😊 Feliz')], help_text='Calificación: triste, neutro o feliz', max_length=10, verbose_name='Calificación')),
                ('opinion', models.TextField(help_text='Tu opinión sobre el servicio de QA', verbose_name='Opinión')),
                ('name', models.CharField(blank=True, help_text='Tu nombre (opcional)', max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, help_text='Tu correo electrónico (opcional)', max_length=254, verbose_name='Correo electrónico')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la calificación', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, help_text='Información del navegador', max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('is_public', models.BooleanField(default=True, help_text='Si la calificación puede mostrarse públicamente', verbose_name='Visible públicamente')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa asociada a esta calificación (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_ratings', to='tickets.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario registrado que dejó la calificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Calificación QA',
                'verbose_name_plural': 'Calificaciones QA',
                'ordering': ['-created_at'],
            },
        ),
    ]
