# Generated by Django 4.2.20 on 2025-11-19 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0265_qarating'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del juego (ej: Final Torneo 2025)', max_length=200, verbose_name='Nombre del Juego')),
                ('player1_name', models.CharField(help_text='Nombre del primer jugador', max_length=100, verbose_name='Jugador 1')),
                ('player2_name', models.CharField(help_text='Nombre del segundo jugador', max_length=100, verbose_name='Jugador 2')),
                ('player1_score', models.IntegerField(default=0, verbose_name='Puntos Jugador 1')),
                ('player2_score', models.IntegerField(default=0, verbose_name='Puntos Jugador 2')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('finished', 'Finalizado')], default='pending', max_length=20, verbose_name='Estado del Juego')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para acceso público', unique=True, verbose_name='UUID Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('max_points', models.IntegerField(default=0, help_text='0 = sin límite', verbose_name='Puntos máximos')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el juego', verbose_name='Notas')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Contador de Juego',
                'verbose_name_plural': 'Contadores de Juegos',
                'ordering': ['-created_at'],
            },
        ),
    ]
