# Generated by Django 4.2.20 on 2025-11-19 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0266_gamecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre del ejercicio (ej: Rutina de Flexiones)', max_length=200, verbose_name='Título')),
                ('sets_target', models.IntegerField(help_text='Número de tandas objetivo', verbose_name='Tandas Objetivo')),
                ('reps_target', models.IntegerField(help_text='Número de repeticiones objetivo por tanda', verbose_name='Repeticiones Objetivo')),
                ('current_sets', models.IntegerField(default=0, verbose_name='Tandas Actuales')),
                ('current_reps', models.IntegerField(default=0, verbose_name='Repeticiones Actuales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('paused', 'Pausado'), ('finished', 'Finalizado')], default='pending', max_length=20, verbose_name='Estado')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para acceso público', unique=True, verbose_name='UUID Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el ejercicio', verbose_name='Notas')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Contador de Ejercicio',
                'verbose_name_plural': 'Contadores de Ejercicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
