# Generated by Django 4.2.20 on 2025-11-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0267_exercisecounter'),
    ]

    operations = [
    ]
