# Generated by Django 4.2.20 on 2025-11-19 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0268_auto_20251119_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre del objetivo deportivo (ej: Correr 5K en menos de 30 minutos)', max_length=200, verbose_name='Título del Objetivo')),
                ('player_name', models.CharField(help_text='Nombre de la persona que realizará el objetivo', max_length=200, verbose_name='Nombre del Jugador')),
                ('target_time', models.IntegerField(blank=True, help_text='Tiempo objetivo en segundos para completar el objetivo', null=True, verbose_name='Tiempo Objetivo (segundos)')),
                ('target_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia objetivo en kilómetros', max_digits=10, null=True, verbose_name='Distancia Objetivo (km)')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para acceso público', unique=True, verbose_name='UUID Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el objetivo', verbose_name='Notas')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_goals', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sport_goals', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Objetivo Deportivo',
                'verbose_name_plural': 'Objetivos Deportivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportGoalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_time', models.IntegerField(blank=True, help_text='Tiempo real en segundos que tomó completar', null=True, verbose_name='Tiempo Real (segundos)')),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia real recorrida en kilómetros', max_digits=10, null=True, verbose_name='Distancia Real (km)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre este intento específico', verbose_name='Notas')),
                ('sport_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tickets.sportgoal', verbose_name='Objetivo Deportivo')),
            ],
            options={
                'verbose_name': 'Registro de Objetivo',
                'verbose_name_plural': 'Registros de Objetivos',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
