# Generated by Django 4.2.20 on 2025-11-20 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0269_sportgoal_sportgoalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='api_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para autenticar llamadas a la API de esta landing page', unique=True, verbose_name='Token de API'),
        ),
    ]
