# Generated by Django 4.2.20 on 2025-11-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0270_landingpage_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(help_text='Número de secuencia único de la solicitud', max_length=50, unique=True, verbose_name='Secuencia')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de lo que se solicita', verbose_name='Descripción')),
                ('requested_to', models.CharField(help_text='Nombre de la persona a quien se solicita', max_length=200, verbose_name='Solicitado a')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa asociada a la solicitud', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Solicitud al Cliente',
                'verbose_name_plural': 'Solicitudes a Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='Texto de la respuesta del cliente', verbose_name='Respuesta')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='client_request_attachments/%Y/%m/', verbose_name='Adjunto')),
                ('responded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='tickets.clientrequest', verbose_name='Solicitud')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Respuesta de Solicitud',
                'verbose_name_plural': 'Respuestas de Solicitudes',
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['sequence'], name='tickets_cli_sequenc_3b35e4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', '-created_at'], name='tickets_cli_status_cd2824_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['company', '-created_at'], name='tickets_cli_company_48d97a_idx'),
        ),
    ]
