# Generated by Django 4.2.20 on 2025-11-20 09:37

from django.db import migrations, models
import uuid


def generate_unique_tokens(apps, schema_editor):
    """Genera tokens únicos para empresas existentes"""
    Company = apps.get_model('tickets', 'Company')
    for company in Company.objects.all():
        company.client_requests_token = uuid.uuid4()
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0271_clientrequest_clientrequestresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_requests_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para que los clientes accedan a sus solicitudes', null=True, verbose_name='Token de Solicitudes'),
        ),
        migrations.RunPython(generate_unique_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='client_requests_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para que los clientes accedan a sus solicitudes', unique=True, verbose_name='Token de Solicitudes'),
        ),
    ]
