# Generated by Django 4.2.20 on 2025-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0272_company_client_requests_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Documento o archivo de referencia para el cliente', null=True, upload_to='client_request_attachments/', verbose_name='Archivo adjunto'),
        ),
    ]
