# Generated by Django 4.2.20 on 2025-11-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0273_add_attachment_to_client_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar este conjunto de solicitudes', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True, help_text='Descripción de para qué sirve esta plantilla', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, se puede usar para crear solicitudes', verbose_name='Activa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_request_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Solicitud',
                'verbose_name_plural': 'Plantillas de Solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequestTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requested_to', models.CharField(help_text='Nombre de la persona a quien se solicita', max_length=200, verbose_name='Solicitado a')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en la lista', verbose_name='Orden')),
                ('attachment', models.FileField(blank=True, help_text='Documento de referencia para esta solicitud', null=True, upload_to='client_request_template_attachments/', verbose_name='Archivo adjunto')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.clientrequesttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Item de Plantilla',
                'verbose_name_plural': 'Items de Plantilla',
                'ordering': ['order', 'id'],
            },
        ),
    ]
