# Generated by Django 4.2.20 on 2025-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0274_add_client_request_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipledocumentationitem',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que se ha descargado este archivo', verbose_name='Contador de Descargas'),
        ),
    ]
