# Generated by Django 4.2.20 on 2025-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0275_add_download_count_to_multiple_doc_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipledocumentationitem',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del documento (opcional)', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
