# Generated by Django 4.2.20 on 2025-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0276_add_expiration_date_to_multiple_doc_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, help_text='IBAN o número de cuenta bancaria', max_length=100, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_holder',
            field=models.CharField(blank=True, help_text='Nombre del titular de la cuenta bancaria', max_length=200, verbose_name='Titular de la Cuenta'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Nombre del banco', max_length=200, verbose_name='Nombre del Banco'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_swift',
            field=models.CharField(blank=True, help_text='Código SWIFT o BIC del banco', max_length=50, verbose_name='SWIFT/BIC'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_url',
            field=models.URLField(blank=True, help_text='Sitio web del banco', verbose_name='URL del Banco'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad de la empresa', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, help_text='País de la empresa', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Términos y condiciones de pago (se mostrarán en las cotizaciones)', verbose_name='Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Código postal', max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, help_text='Estado o provincia de la empresa', max_length=100, verbose_name='Estado/Provincia'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Número de identificación fiscal', max_length=50, verbose_name='NIF/CIF/Tax ID'),
        ),
    ]
