# Generated by Django 4.2.20 on 2025-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0277_company_bank_account_company_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_terms_description',
            field=models.TextField(blank=True, help_text='Descripción detallada de las condiciones de pago para las cotizaciones', verbose_name='Descripción de Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='company',
            name='quotation_general_description',
            field=models.TextField(blank=True, help_text='Descripción general que aparecerá en todas las cotizaciones de esta empresa', verbose_name='Descripción General de Cotizaciones'),
        ),
    ]
