# Generated by Django 4.2.20 on 2025-11-24 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0278_company_payment_terms_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('country', models.CharField(blank=True, help_text='País desde donde se accedió', max_length=100, verbose_name='País')),
                ('country_code', models.CharField(blank=True, help_text='Código ISO del país (ej: US, MX, ES)', max_length=2, verbose_name='Código de País')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/Dispositivo')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tickets.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Visita a Cotización',
                'verbose_name_plural': 'Visitas a Cotizaciones',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['quotation'], name='tickets_quo_quotati_2ee596_idx'), models.Index(fields=['viewed_at'], name='tickets_quo_viewed__70cdda_idx'), models.Index(fields=['country'], name='tickets_quo_country_3d8b9f_idx')],
            },
        ),
    ]
