# Generated by Django 4.2.20 on 2025-11-25 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0280_contact_had_meeting_contact_meeting_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Visita a Cotizacion', 'verbose_name_plural': 'Visitas a Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contacted_by_phone',
            field=models.BooleanField(default=False, help_text='Marcar si se contacto al cliente por telefono', verbose_name='Contactado por telefono'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contacted_by_web',
            field=models.BooleanField(default=False, help_text='Marcar si se contacto al cliente por web o email', verbose_name='Contactado por web/email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Fecha del ultimo contacto realizado', null=True, verbose_name='Fecha del ultimo contacto'),
        ),
        migrations.AlterField(
            model_name='quotationview',
            name='country',
            field=models.CharField(blank=True, help_text='Pais desde donde se accedio', max_length=100, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='quotationview',
            name='country_code',
            field=models.CharField(blank=True, help_text='Codigo ISO del pais (ej: US, MX, ES)', max_length=2, verbose_name='Codigo de Pais'),
        ),
        migrations.AlterField(
            model_name='quotationview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP'),
        ),
        migrations.AlterField(
            model_name='quotationview',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tickets.quotation', verbose_name='Cotizacion'),
        ),
        migrations.CreateModel(
            name='SharedAIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(help_text='Token único para acceder a la conversación compartida', max_length=32, unique=True, verbose_name='Token de compartición')),
                ('title', models.CharField(help_text='Título que se mostrará en la vista pública', max_length=200, verbose_name='Título público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compartición activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de vistas')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_chats', to='tickets.aichatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Chat IA Compartido',
                'verbose_name_plural': 'Chats IA Compartidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
