# Generated by Django 4.2.20 on 2025-11-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0281_alter_quotationview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(help_text='Token único para acceder al mensaje compartido', max_length=32, unique=True, verbose_name='Token de compartición')),
                ('title', models.CharField(blank=True, help_text='Título opcional para el mensaje compartido', max_length=200, verbose_name='Título público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compartición activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de compartición')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de vistas')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha en que expira el enlace compartido (opcional)', null=True, verbose_name='Fecha de expiración')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_instances', to='tickets.aichatmessage', verbose_name='Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ai_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que compartió')),
            ],
            options={
                'verbose_name': 'Mensaje IA Compartido',
                'verbose_name_plural': 'Mensajes IA Compartidos',
                'ordering': ['-created_at'],
            },
        ),
        # Eliminar tabla de forma segura solo si existe
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS tickets_sharedaichat CASCADE;',
            reverse_sql='-- No reverse operation',
        ),
    ]
