# Generated by Django 4.2.20 on 2025-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0282_sharedaichatmessage_delete_sharedaichat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedaichatmessage',
            name='share_token',
            field=models.CharField(help_text='Token único para acceder al mensaje compartido', max_length=64, unique=True, verbose_name='Token de compartición'),
        ),
    ]
