# Generated by Django 4.2.20 on 2025-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0282_sharedaichatmessage_delete_sharedaichat'),
    ]

    operations = [
        # Modificar columna de forma segura solo si la tabla existe
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'tickets_sharedaichatmessage') THEN
                    ALTER TABLE tickets_sharedaichatmessage ALTER COLUMN share_token TYPE VARCHAR(64);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'tickets_sharedaichatmessage') THEN
                    ALTER TABLE tickets_sharedaichatmessage ALTER COLUMN share_token TYPE VARCHAR(32);
                END IF;
            END $$;
            """,
        ),
    ]
