# Generated by Django 4.2.20 on 2025-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0283_increase_share_token_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de cumpleaños'),
        ),
    ]
