# Generated by Django 4.2.20 on 2025-11-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0284_userprofile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del evento', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del evento', verbose_name='Descripción')),
                ('event_date', models.DateTimeField(help_text='Fecha y hora del evento', verbose_name='Fecha y Hora')),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización del evento (opcional)', null=True, verbose_name='Fecha de Finalización')),
                ('location', models.CharField(blank=True, help_text='Lugar donde se realizará el evento', max_length=300, verbose_name='Ubicación')),
                ('color', models.CharField(default='#007bff', help_text='Color del evento en el calendario (formato hexadecimal)', max_length=7, verbose_name='Color')),
                ('is_all_day', models.BooleanField(default=False, help_text='Marcar si el evento dura todo el día', verbose_name='Todo el día')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['event_date'],
            },
        ),
    ]
