# Generated by Django 4.2.20 on 2025-11-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0285_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
