# Generated by Django 4.2.20 on 2025-11-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0286_remove_event_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Viaje')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('destination', models.CharField(max_length=200, verbose_name='Destino Principal')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('is_public', models.BooleanField(default=False, help_text='Permitir que el viaje sea visible públicamente', verbose_name='Público')),
                ('public_token', models.UUIDField(default=uuid.uuid4, help_text='Token para compartir el viaje públicamente', unique=True, verbose_name='Token Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Lugar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visita en el itinerario', verbose_name='Orden')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Visita')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Visita')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Tiempo estimado de visita en minutos', null=True, verbose_name='Duración (minutos)')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el lugar', verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tickets.trip', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Parada de Viaje',
                'verbose_name_plural': 'Paradas de Viaje',
                'ordering': ['trip', 'order'],
            },
        ),
    ]
