# Generated by Django 4.2.20 on 2025-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0287_trip_tripstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='historical_info',
            field=models.TextField(blank=True, help_text='Historia e información interesante sobre el lugar (aprox. 200 palabras)', verbose_name='Información Histórica'),
        ),
    ]
