# Generated by Django 4.2.20 on 2025-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0288_tripstop_historical_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo')], default='positive', max_length=10, verbose_name='Estado'),
        ),
    ]
