# Generated by Django 4.2.20 on 2025-11-25 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0289_add_neutral_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Contador')),
                ('token', models.CharField(help_text='Token único para identificar este contador', max_length=64, unique=True, verbose_name='Token')),
                ('domain', models.CharField(blank=True, help_text='Dominio donde se instalará el contador (opcional)', max_length=255, verbose_name='Dominio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Total de Visitas')),
                ('total_page_views', models.PositiveIntegerField(default=0, verbose_name='Total de Páginas Vistas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_counters', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contador Web',
                'verbose_name_plural': 'Contadores Web',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebCounterVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, verbose_name='URL Visitada')),
                ('referrer', models.CharField(blank=True, max_length=2048, verbose_name='Referrer')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operativo')),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=50, verbose_name='Tipo de Dispositivo')),
                ('screen_resolution', models.CharField(blank=True, max_length=50, verbose_name='Resolución de Pantalla')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Idioma')),
                ('session_id', models.CharField(blank=True, max_length=64, verbose_name='ID de Sesión')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de Visita')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tickets.webcounter', verbose_name='Contador')),
            ],
            options={
                'verbose_name': 'Visita de Contador Web',
                'verbose_name_plural': 'Visitas de Contadores Web',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sharedaichatmessage',
            name='share_token',
            field=models.CharField(help_text='Token único para acceder al mensaje compartido', max_length=64, unique=True, verbose_name='Token de compartición'),
        ),
        migrations.DeleteModel(
            name='SharedAIChat',
        ),
        migrations.AddIndex(
            model_name='webcountervisit',
            index=models.Index(fields=['-created_at', 'counter'], name='tickets_web_created_13c7de_idx'),
        ),
        migrations.AddIndex(
            model_name='webcountervisit',
            index=models.Index(fields=['counter', 'session_id'], name='tickets_web_counter_33e007_idx'),
        ),
    ]
