# Generated by Django 4.2.20 on 2025-11-26 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0291_ensure_sharedaichatmessage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de Horas')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Hora')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Importe Total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('valid_until', models.DateTimeField(verbose_name='Válido Hasta')),
                ('public_token', models.CharField(help_text='Token único para acceso público', max_length=64, unique=True, verbose_name='Token Público')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('response_notes', models.TextField(blank=True, verbose_name='Notas de Respuesta del Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cotización Rápida',
                'verbose_name_plural': 'Cotizaciones Rápidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
