# Generated by Django 4.2.20 on 2025-11-26 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0292_quickquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Visualización')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Dispositivo')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tickets.quickquote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Visualización de Cotización',
                'verbose_name_plural': 'Visualizaciones de Cotizaciones',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
