# Generated by Django 4.2.20 on 2025-11-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0293_quickquoteview'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_quotes', to='tickets.company', verbose_name='Empresa'),
        ),
    ]
