# Generated by Django 4.2.20 on 2025-11-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0294_quickquote_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquote',
            name='sequence_number',
            field=models.CharField(blank=True, help_text='Formato: CR-YYYY-XX', max_length=20, verbose_name='Número de Secuencia'),
        ),
    ]
