# Generated by Django 4.2.20 on 2025-11-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0295_quickquote_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quote_terms_conditions',
            field=models.TextField(blank=True, help_text='Términos y condiciones que se mostrarán en las cotizaciones rápidas', verbose_name='Términos y Condiciones de Cotizaciones'),
        ),
    ]
