# Generated by Django 4.2.20 on 2025-11-26 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0296_userprofile_quote_terms_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.quickquote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Comentario de Cotización',
                'verbose_name_plural': 'Comentarios de Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
