# Generated by Django 4.2.20 on 2025-11-27 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0297_quickquotecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.CharField(blank=True, help_text='Formato: MM-YYYY-XX', max_length=20, verbose_name='Número de Secuencia')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('public_token', models.CharField(help_text='Token único para acceso público', max_length=64, unique=True, verbose_name='Token Público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('label_1', models.CharField(default='Medición 1', max_length=100, verbose_name='Etiqueta Medición 1')),
                ('label_2', models.CharField(default='Medición 2', max_length=100, verbose_name='Etiqueta Medición 2')),
                ('label_3', models.CharField(default='Medición 3', max_length=100, verbose_name='Etiqueta Medición 3')),
                ('label_4', models.CharField(default='Medición 4', max_length=100, verbose_name='Etiqueta Medición 4')),
                ('label_5', models.CharField(default='Medición 5', max_length=100, verbose_name='Etiqueta Medición 5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Medición Múltiple',
                'verbose_name_plural': 'Mediciones Múltiples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiMeasurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('value_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor 1')),
                ('value_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor 2')),
                ('value_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor 3')),
                ('value_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor 4')),
                ('value_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor 5')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tickets.multimeasurement', verbose_name='Medición')),
            ],
            options={
                'verbose_name': 'Registro de Medición',
                'verbose_name_plural': 'Registros de Mediciones',
                'ordering': ['-date'],
                'unique_together': {('measurement', 'date')},
            },
        ),
    ]
