# Generated by Django 4.2.20 on 2025-11-27 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0298_multimeasurement_multimeasurementrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multimeasurementrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='multimeasurementrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
    ]
