# Generated by Django 4.2.20 on 2025-11-27 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0299_alter_multimeasurementrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Partida')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Presupuestado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Partida de Egreso',
                'verbose_name_plural': 'Partidas de Egresos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetIncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Partida')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Presupuestado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Partida de Ingreso',
                'verbose_name_plural': 'Partidas de Ingresos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Presupuesto')),
                ('month', models.IntegerField(help_text='1-12', verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('expense_transactions', models.ManyToManyField(blank=True, related_name='expense_budgets', to='tickets.budgettransaction')),
                ('income_transactions', models.ManyToManyField(blank=True, related_name='income_budgets', to='tickets.budgettransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto Personal',
                'verbose_name_plural': 'Presupuestos Personales',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'name', 'month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tickets.personalbudget', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='expense_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tickets.budgetexpenseitem', verbose_name='Partida de Egreso'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='income_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tickets.budgetincomeitem', verbose_name='Partida de Ingreso'),
        ),
        migrations.AddField(
            model_name='budgetincomeitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='tickets.personalbudget', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='budgetexpenseitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='tickets.personalbudget', verbose_name='Presupuesto'),
        ),
    ]
