# Generated by Django 4.2.20 on 2025-11-27 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0300_budgetexpenseitem_budgetincomeitem_budgettransaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalbudget',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'Presupuesto Personal', 'verbose_name_plural': 'Presupuestos Personales'},
        ),
        migrations.AlterUniqueTogether(
            name='personalbudget',
            unique_together={('user', 'name', 'year')},
        ),
        migrations.RemoveField(
            model_name='personalbudget',
            name='month',
        ),
    ]
