# Generated by Django 4.2.20 on 2025-11-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0301_alter_personalbudget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransaction',
            name='month',
            field=models.IntegerField(default=1, help_text='Mes de la transacción (1-12)', verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='year',
            field=models.IntegerField(default=2025, help_text='Año de la transacción', verbose_name='Año'),
        ),
    ]
