# Generated by Django 4.2.20 on 2025-11-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0302_budgettransaction_month_budgettransaction_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbudget',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Si está marcado, solo el creador puede ver este presupuesto', verbose_name='Privado'),
        ),
    ]
