# Generated by Django 4.2.20 on 2025-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0303_personalbudget_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='public_views_count',
            field=models.IntegerField(default=0, verbose_name='Vistas del enlace público'),
        ),
        migrations.AlterField(
            model_name='budgetexpenseitem',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mensual en euros para esta partida', max_digits=10, verbose_name='Monto Presupuestado Mensual (€)'),
        ),
        migrations.AlterField(
            model_name='budgetincomeitem',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mensual en euros para esta partida', max_digits=10, verbose_name='Monto Presupuestado Mensual (€)'),
        ),
    ]
