# Generated by Django 4.2.20 on 2025-11-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0304_meeting_public_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendee',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='response_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado de respuesta'),
        ),
    ]
