# Generated by Django 4.2.20 on 2025-11-27 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0305_meetingattendee_response_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('sad', '😞 Triste'), ('neutral', '😐 Neutro'), ('happy', '😊 Feliz')], max_length=10, verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.meetingattendee', verbose_name='Asistente')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tickets.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Evaluación de reunión',
                'verbose_name_plural': 'Evaluaciones de reuniones',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'attendee')},
            },
        ),
    ]
