# Generated by Django 4.2.20 on 2025-11-27 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0306_meetingrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Dispositivo')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operativo')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de acceso')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='tickets.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['meeting', '-accessed_at'], name='tickets_mee_meeting_ed6f39_idx'), models.Index(fields=['country'], name='tickets_mee_country_98959e_idx'), models.Index(fields=['device_type'], name='tickets_mee_device__b54733_idx')],
            },
        ),
    ]
