# Generated by Django 4.2.20 on 2025-11-27 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0307_meetingaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del enlace')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.meeting', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Enlace de reunión',
                'verbose_name_plural': 'Enlaces de reunión',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
