# Generated by Django 4.2.20 on 2025-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0308_meetinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Número de Tarea'),
        ),
    ]
