# Generated by Django 4.2.20 on 2025-11-28 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0309_task_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la tabla (ej: usuarios, comentarios)', max_length=100, unique=True, verbose_name='Nombre de la tabla')),
                ('display_name', models.CharField(help_text='Nombre amigable para mostrar', max_length=200, verbose_name='Nombre de visualización')),
                ('description', models.TextField(blank=True, help_text='Descripción del propósito de la tabla', verbose_name='Descripción')),
                ('api_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token de seguridad para acceder a la API de esta tabla', unique=True, verbose_name='Token de API')),
                ('is_active', models.BooleanField(default=True, help_text='Si la tabla y su API están activas', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('allow_public_read', models.BooleanField(default=False, help_text='Permitir GET sin autenticación', verbose_name='Permitir lectura pública')),
                ('allow_public_create', models.BooleanField(default=False, help_text='Permitir POST sin autenticación', verbose_name='Permitir creación pública')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_tables_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tabla Dinámica',
                'verbose_name_plural': 'Tablas Dinámicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicTableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Datos del registro en formato JSON', verbose_name='Datos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se creó el registro', null=True, verbose_name='IP de creación')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tickets.dynamictable', verbose_name='Tabla')),
            ],
            options={
                'verbose_name': 'Registro de Tabla',
                'verbose_name_plural': 'Registros de Tablas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table', '-created_at'], name='tickets_dyn_table_i_3146ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='DynamicTableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del campo (ej: titulo, email, contenido)', max_length=100, verbose_name='Nombre del campo')),
                ('display_name', models.CharField(help_text='Nombre amigable para mostrar', max_length=200, verbose_name='Nombre de visualización')),
                ('field_type', models.CharField(choices=[('text', 'Texto corto'), ('textarea', 'Texto largo'), ('number', 'Número'), ('decimal', 'Decimal'), ('boolean', 'Verdadero/Falso'), ('date', 'Fecha'), ('datetime', 'Fecha y hora'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON')], default='text', max_length=20, verbose_name='Tipo de campo')),
                ('is_required', models.BooleanField(default=False, help_text='Si el campo es obligatorio', verbose_name='Requerido')),
                ('default_value', models.TextField(blank=True, help_text='Valor por defecto del campo', null=True, verbose_name='Valor por defecto')),
                ('max_length', models.IntegerField(blank=True, help_text='Longitud máxima para campos de texto', null=True, verbose_name='Longitud máxima')),
                ('help_text', models.CharField(blank=True, help_text='Descripción o ayuda del campo', max_length=500, verbose_name='Texto de ayuda')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización del campo', verbose_name='Orden')),
                ('is_unique', models.BooleanField(default=False, help_text='Si el valor debe ser único en la tabla', verbose_name='Único')),
                ('is_indexed', models.BooleanField(default=False, help_text='Si el campo debe ser indexado para búsquedas rápidas', verbose_name='Indexado')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.dynamictable', verbose_name='Tabla')),
            ],
            options={
                'verbose_name': 'Campo de Tabla',
                'verbose_name_plural': 'Campos de Tablas',
                'ordering': ['table', 'order', 'id'],
                'unique_together': {('table', 'name')},
            },
        ),
    ]
