# Generated by Django 4.2.20 on 2025-11-28 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0310_dynamictable_dynamictablerecord_dynamictablefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo para identificar esta petición', max_length=200, verbose_name='Título')),
                ('url', models.URLField(help_text='URL completa del endpoint', max_length=500, verbose_name='URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='Método HTTP')),
                ('headers', models.TextField(blank=True, help_text='Headers personalizados (formato: Name: Value, uno por línea)', verbose_name='Headers')),
                ('body', models.TextField(blank=True, help_text='Cuerpo de la petición (JSON)', verbose_name='Body')),
                ('token', models.CharField(blank=True, help_text='Token de autenticación (Bearer, API Key, etc.)', max_length=500, verbose_name='Token')),
                ('api_type', models.CharField(choices=[('internal', 'API Interna'), ('external', 'API Externa')], default='external', max_length=20, verbose_name='Tipo de API')),
                ('description', models.TextField(blank=True, help_text='Notas sobre esta petición', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_favorite', models.BooleanField(default=False, help_text='Marcar como favorito para acceso rápido', verbose_name='Favorito')),
                ('last_used', models.DateTimeField(blank=True, help_text='Última vez que se ejecutó esta petición', null=True, verbose_name='Último uso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_api_requests', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('dynamic_table', models.ForeignKey(blank=True, help_text='Solo si es API interna', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_requests', to='tickets.dynamictable', verbose_name='Tabla Dinámica')),
            ],
            options={
                'verbose_name': 'API Guardada',
                'verbose_name_plural': 'APIs Guardadas',
                'ordering': ['-is_favorite', '-last_used', '-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='tickets_sav_created_b49c4d_idx'), models.Index(fields=['created_by', 'is_favorite'], name='tickets_sav_created_af6ec6_idx')],
            },
        ),
    ]
