# Generated by Django 4.2.20 on 2025-11-28 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0311_savedapirequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictable',
            name='public_form_description',
            field=models.TextField(blank=True, help_text='Texto descriptivo que se muestra en el formulario', verbose_name='Descripción del formulario'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='public_form_enabled',
            field=models.BooleanField(default=False, help_text='Habilitar formulario web público para crear registros', verbose_name='Formulario público habilitado'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='public_form_password',
            field=models.CharField(blank=True, help_text='Contraseña opcional para proteger el formulario público', max_length=100, verbose_name='Contraseña del formulario'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='public_form_success_message',
            field=models.CharField(default='¡Gracias! Tu información ha sido registrada correctamente.', help_text='Mensaje que se muestra después de enviar el formulario', max_length=500, verbose_name='Mensaje de éxito'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='public_form_title',
            field=models.CharField(blank=True, help_text='Título personalizado para el formulario público', max_length=200, verbose_name='Título del formulario'),
        ),
        migrations.AddField(
            model_name='dynamictable',
            name='public_form_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Token único para acceder al formulario público', null=True, verbose_name='Token del formulario público'),
        ),
    ]
