# Generated by Django 4.2.20 on 2025-11-28 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0312_dynamictable_public_form_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictable',
            name='public_form_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Token único para acceder al formulario público', null=True, unique=True, verbose_name='Token del formulario público'),
        ),
    ]
