# Generated by Django 4.2.20 on 2025-11-28 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0313_alter_dynamictable_public_form_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedaichatmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje IA Compartido (Deprecated)', 'verbose_name_plural': 'Mensajes IA Compartidos (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='sharedaichatmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_instances_old', to='tickets.aichatmessage', verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='sharedaichatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ai_messages_old', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que compartió'),
        ),
        migrations.AlterModelTable(
            name='sharedaichatmessage',
            table='tickets_sharedaichatmessage_old',
        ),
        migrations.CreateModel(
            name='PublicAIMessageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token único para acceder al mensaje compartido', max_length=64, unique=True, verbose_name='Token de compartición')),
                ('public_title', models.CharField(blank=True, help_text='Título opcional para el mensaje compartido', max_length=200, verbose_name='Título público')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Compartición activa')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de compartición')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de vistas')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Fecha en que expira el enlace compartido (opcional)', null=True, verbose_name='Fecha de expiración')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_shares', to='tickets.aichatmessage', verbose_name='Mensaje de Chat')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_message_shares', to=settings.AUTH_USER_MODEL, verbose_name='Compartido por')),
            ],
            options={
                'verbose_name': 'Compartición de Mensaje IA',
                'verbose_name_plural': 'Comparticiones de Mensajes IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='tickets_pub_token_b7f7f4_idx'), models.Index(fields=['shared_by', '-created_at'], name='tickets_pub_shared__262daa_idx'), models.Index(fields=['is_active', '-created_at'], name='tickets_pub_is_acti_e0e449_idx')],
            },
        ),
    ]
