# Generated by Django 4.2.20 on 2025-11-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0316_create_social_network_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL del video de YouTube', null=True, verbose_name='URL de YouTube'),
        ),
        migrations.AddField(
            model_name='socialpostlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Me gusta'), ('love', 'Me encanta'), ('dislike', 'No me gusta')], default='like', max_length=10, verbose_name='Tipo de reacción'),
        ),
    ]
