# Generated by Django 4.2.20 on 2025-11-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0317_add_reactions_and_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Solo visible para el creador', verbose_name='Privado'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='share_token',
            field=models.CharField(blank=True, help_text='Token único para compartir públicamente', max_length=100, null=True, unique=True, verbose_name='Token de compartir'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['share_token'], name='tickets_soc_share_t_d231ad_idx'),
        ),
    ]
