# Generated by Django 4.2.20 on 2025-11-28 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0318_add_privacy_and_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostcomment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del invitado'),
        ),
        migrations.AddField(
            model_name='socialpostcomment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del invitado'),
        ),
        migrations.AlterField(
            model_name='socialpostcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='SocialCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Me gusta'), ('love', 'Me encanta'), ('dislike', 'No me gusta')], default='like', max_length=10, verbose_name='Tipo de reacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='tickets.socialpostcomment', verbose_name='Comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción de Comentario',
                'verbose_name_plural': 'Reacciones de Comentarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', 'user'], name='tickets_soc_comment_db5c6b_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
