# Generated by Django 4.2.20 on 2025-11-28 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0319_add_guest_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='socialpost',
            name='company_only',
            field=models.BooleanField(default=True, help_text='Si está marcado, solo los usuarios de la misma empresa pueden ver esta publicación', verbose_name='Solo mi empresa'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['company_only', '-created_at'], name='tickets_soc_company_06b9cc_idx'),
        ),
        migrations.AddField(
            model_name='socialpostfavorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tickets.socialpost', verbose_name='Publicación'),
        ),
        migrations.AddField(
            model_name='socialpostfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='socialpostfavorite',
            index=models.Index(fields=['user', '-created_at'], name='tickets_soc_user_id_93b729_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpostfavorite',
            index=models.Index(fields=['post', 'user'], name='tickets_soc_post_id_4b4142_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialpostfavorite',
            unique_together={('post', 'user')},
        ),
    ]
