# Generated by Django 4.2.20 on 2025-11-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0320_socialpostfavorite_socialpost_company_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='public_views_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que se ha visto la publicación pública', verbose_name='Vistas públicas'),
        ),
    ]
