# Generated by Django 4.2.20 on 2025-11-29 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0321_socialpost_public_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], help_text='Calificación de 1 a 5 estrellas', verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional sobre el servicio', verbose_name='Comentario')),
                ('rated_by_name', models.CharField(help_text='Nombre de quien califica', max_length=200, verbose_name='Nombre')),
                ('rated_by_email', models.EmailField(help_text='Email de quien califica', max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de calificación')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tickets.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Calificación de Orden de Trabajo',
                'verbose_name_plural': 'Calificaciones de Órdenes de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('author_name', models.CharField(max_length=200, verbose_name='Nombre del autor')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email del autor')),
                ('is_public', models.BooleanField(default=True, help_text='Si está marcado, el comentario será visible en la vista pública', verbose_name='Visible públicamente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_comments', to='tickets.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Comentario de Orden de Trabajo',
                'verbose_name_plural': 'Comentarios de Órdenes de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
    ]
