# Generated by Django 4.2.20 on 2025-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0322_workorderrating_workordercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Permite que esta orden sea visible públicamente', verbose_name='Publicar públicamente'),
        ),
    ]
