# Generated by Django 4.2.20 on 2025-11-29 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0323_alter_workorder_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('sequence', models.CharField(help_text='Ej: DRF-2025-001', max_length=50, verbose_name='Secuencia')),
                ('public_share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_requirement_documents', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_frd_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento de Requerimientos Funcionales',
                'verbose_name_plural': 'Documentos de Requerimientos Funcionales',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='FunctionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Número secuencial del requerimiento', verbose_name='Número')),
                ('description', models.TextField(help_text='Descripción del alcance o requerimiento', verbose_name='Descripción')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('approved_by_name', models.CharField(blank=True, max_length=200, verbose_name='Aprobado por (nombre)')),
                ('approved_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Aprobado por (email)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tickets.functionalrequirementdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Requerimiento Funcional',
                'verbose_name_plural': 'Requerimientos Funcionales',
                'ordering': ['document', 'number'],
                'unique_together': {('document', 'number')},
            },
        ),
    ]
