# Generated by Django 4.2.20 on 2025-11-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0324_functionalrequirementdocument_functionalrequirement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='functionalrequirementdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='functionalrequirementdocument',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre libre de la empresa si no está en el listado', max_length=200, verbose_name='Nombre de Empresa'),
        ),
        migrations.AlterField(
            model_name='functionalrequirementdocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functional_requirement_documents', to='tickets.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='functionalrequirementdocument',
            name='sequence',
            field=models.CharField(editable=False, help_text='Se genera automáticamente', max_length=50, unique=True, verbose_name='Secuencia'),
        ),
    ]
