# Generated by Django 4.2.20 on 2025-11-29 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0325_alter_functionalrequirementdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRequirementDocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de visita')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tickets.functionalrequirementdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Vista de DRF',
                'verbose_name_plural': 'Vistas de DRF',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
