# Generated by Django 4.2.20 on 2025-11-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0326_functionalrequirementdocumentview'),
    ]

    operations = [
    ]
