# Generated by Django 4.2.20 on 2025-11-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0327_auto_20251129_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalrequirementdocument',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción general del proyecto o alcance', verbose_name='Descripción General'),
        ),
    ]
