# Generated by Django 4.2.20 on 2025-11-29 02:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0330_functionalrequirement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRequirementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Nombre del autor')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email del autor')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.functionalrequirement', verbose_name='Requerimiento')),
            ],
            options={
                'verbose_name': 'Comentario de Requerimiento',
                'verbose_name_plural': 'Comentarios de Requerimientos',
                'ordering': ['created_at'],
            },
        ),
    ]
