# Generated by Django 4.2.20 on 2025-11-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0332_contact_assigned_to_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_size',
            field=models.CharField(choices=[('small', 'Pequeña (Menos de 10 empleados)'), ('medium', 'Mediana (10 a 50 empleados)'), ('large', 'Grande (Más de 50 empleados)')], default='small', help_text='Tamaño de la empresa del contacto', max_length=10, verbose_name='Tamaño de Empresa'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo'), ('not_now', 'No ahora')], default='negative', max_length=10, verbose_name='Estado'),
        ),
    ]
