# Generated by Django 4.2.20 on 2025-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0333_contact_company_size_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo'), ('not_now', 'No ahora'), ('do_not_contact', 'No Contactar')], default='negative', max_length=20, verbose_name='Estado'),
        ),
    ]
