# Generated by Django 4.2.20 on 2025-11-29 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0334_alter_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_contact_goal', models.PositiveIntegerField(default=0, help_text='Número de contactos nuevos que debe crear al mes', verbose_name='Objetivo de contactos al mes')),
                ('monthly_positive_contact_goal', models.PositiveIntegerField(default=0, help_text='Número de contactos positivos que debe conseguir al mes', verbose_name='Objetivo de contactos positivos al mes')),
                ('monthly_meeting_goal', models.PositiveIntegerField(default=0, help_text='Número de reuniones que debe realizar al mes', verbose_name='Objetivo de reuniones mensuales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Plan activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plan de Venta',
                'verbose_name_plural': 'Planes de Venta',
                'ordering': ['-created_at'],
            },
        ),
    ]
