# Generated by Django 4.2.20 on 2025-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0335_salesplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplan',
            name='monthly_won_goal',
            field=models.PositiveIntegerField(default=0, help_text='Número de contactos ganados que debe conseguir al mes', verbose_name='Objetivo de ganados al mes'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo'), ('not_now', 'No ahora'), ('do_not_contact', 'No Contactar'), ('won', 'Ganado')], default='negative', max_length=20, verbose_name='Estado'),
        ),
    ]
