# Generated by Django 4.2.20 on 2025-11-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0336_salesplan_monthly_won_goal_alter_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('share_token', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Token de Compartir')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_groups', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Grupo de Accesos',
                'verbose_name_plural': 'Grupos de Accesos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Enlace')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono Bootstrap (ej: bi-link-45deg)', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', help_text='Color del botón (primary, success, info, warning, danger, etc.)', max_length=20, verbose_name='Color')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.accessgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Enlace de Acceso',
                'verbose_name_plural': 'Enlaces de Acceso',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
