# Generated by Django 4.2.20 on 2025-11-29 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0337_accessgroup_accesslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_public', models.BooleanField(default=False, verbose_name='Vista Pública Activada')),
                ('share_token', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Token de Compartir')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plan de Tareas',
                'verbose_name_plural': 'Planes de Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Día 1, Lunes, Semana 1', max_length=100, verbose_name='Título del Día')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del Día')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tickets.taskplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Día del Plan',
                'verbose_name_plural': 'Días del Plan',
                'ordering': ['order', 'created_at'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TaskPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título de la Tarea')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada el')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Estimadas')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tickets.taskplanday', verbose_name='Día')),
            ],
            options={
                'verbose_name': 'Tarea del Plan',
                'verbose_name_plural': 'Tareas del Plan',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
