# Generated by Django 4.2.20 on 2025-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0339_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
    ]
