# Generated by Django 4.2.20 on 2025-11-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0340_checklistitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Visualizaciones'),
        ),
    ]
