# Generated by Django 4.2.20 on 2025-11-29 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0341_checklist_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de la transacción (ej: T001, TICKET, REPORTE)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo de la transacción', max_length=200, verbose_name='Nombre')),
                ('url', models.CharField(help_text='URL de acceso (puede ser relativa o absoluta)', max_length=500, verbose_name='URL')),
                ('visible_for_all', models.BooleanField(default=True, help_text='Si está marcado, todos pueden ver esta transacción. Si no, solo agentes.', verbose_name='Visible para Todos')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la transacción', verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, default='bi-link-45deg', help_text='Clase del ícono Bootstrap (ej: bi-link-45deg, bi-file-text)', max_length=50, verbose_name='Ícono Bootstrap')),
                ('is_active', models.BooleanField(default=True, help_text='Solo las transacciones activas aparecen en la búsqueda', verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='tickets_tra_code_585dd3_idx'), models.Index(fields=['name'], name='tickets_tra_name_e906db_idx'), models.Index(fields=['is_active'], name='tickets_tra_is_acti_e2895b_idx')],
            },
        ),
    ]
