# Generated by Django 4.2.20 on 2025-11-29 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0342_transaction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del concepto o tema', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del concepto', verbose_name='Descripción')),
                ('source_code', models.TextField(blank=True, help_text='Código fuente de ejemplo o snippet', verbose_name='Código Fuente')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: python, django, api)', max_length=500, verbose_name='Etiquetas')),
                ('category', models.CharField(blank=True, help_text='Categoría del conocimiento (ej: Backend, Frontend, Base de Datos)', max_length=100, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Base de Conocimiento',
                'verbose_name_plural': 'Base de Conocimientos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='tickets_kno_title_660eee_idx'), models.Index(fields=['category'], name='tickets_kno_categor_cc1947_idx'), models.Index(fields=['is_active'], name='tickets_kno_is_acti_f0d864_idx')],
            },
        ),
    ]
