# Generated by Django 4.2.20 on 2025-11-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0343_knowledge_base_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('ru', 'Ruso'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('ar', 'Árabe'), ('hi', 'Hindi'), ('tr', 'Turco'), ('nl', 'Neerlandés'), ('pl', 'Polaco'), ('sv', 'Sueco'), ('no', 'Noruego'), ('da', 'Danés'), ('fi', 'Finlandés'), ('cs', 'Checo')], default='en', max_length=10, verbose_name='Idioma Origen')),
                ('target_language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('ru', 'Ruso'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('ar', 'Árabe'), ('hi', 'Hindi'), ('tr', 'Turco'), ('nl', 'Neerlandés'), ('pl', 'Polaco'), ('sv', 'Sueco'), ('no', 'Noruego'), ('da', 'Danés'), ('fi', 'Finlandés'), ('cs', 'Checo')], default='es', max_length=10, verbose_name='Idioma Destino')),
                ('source_text', models.TextField(help_text='Texto a traducir', verbose_name='Texto Original')),
                ('translated_text', models.TextField(help_text='Resultado de la traducción', verbose_name='Texto Traducido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Traducción',
                'verbose_name_plural': 'Traducciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_language'], name='tickets_tra_source__3de276_idx'), models.Index(fields=['target_language'], name='tickets_tra_target__f0d80b_idx'), models.Index(fields=['created_at'], name='tickets_tra_created_b2961e_idx')],
            },
        ),
    ]
