# Generated by Django 4.2.20 on 2025-11-30 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0344_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='source_language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('ru', 'Ruso'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('ar', 'Árabe'), ('hi', 'Hindi'), ('tr', 'Turco'), ('nl', 'Neerlandés'), ('pl', 'Polaco'), ('sv', 'Sueco'), ('no', 'Noruego'), ('da', 'Danés'), ('fi', 'Finlandés'), ('cs', 'Checo'), ('ca', 'Catalán'), ('val', 'Valenciano')], default='en', max_length=10, verbose_name='Idioma Origen'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('ru', 'Ruso'), ('zh', 'Chino'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('ar', 'Árabe'), ('hi', 'Hindi'), ('tr', 'Turco'), ('nl', 'Neerlandés'), ('pl', 'Polaco'), ('sv', 'Sueco'), ('no', 'Noruego'), ('da', 'Danés'), ('fi', 'Finlandés'), ('cs', 'Checo'), ('ca', 'Catalán'), ('val', 'Valenciano')], default='es', max_length=10, verbose_name='Idioma Destino'),
        ),
        migrations.CreateModel(
            name='SQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar la consulta', max_length=200, verbose_name='Nombre de la Consulta')),
                ('query', models.TextField(help_text='Solo se permiten consultas SELECT', verbose_name='Consulta SQL')),
                ('result', models.TextField(blank=True, help_text='Resultado de la última ejecución', null=True, verbose_name='Resultado')),
                ('row_count', models.IntegerField(default=0, help_text='Número de filas retornadas', verbose_name='Cantidad de Filas')),
                ('execution_time', models.FloatField(default=0.0, help_text='Tiempo de ejecución en segundos', verbose_name='Tiempo de Ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sql_queries', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Consulta SQL',
                'verbose_name_plural': 'Consultas SQL',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='tickets_sql_created_d17ceb_idx'), models.Index(fields=['created_at'], name='tickets_sql_created_a1ea00_idx'), models.Index(fields=['is_favorite'], name='tickets_sql_is_favo_cdb6f1_idx')],
            },
        ),
    ]
