# Generated by Django 4.2.20 on 2025-11-30 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0345_alter_translation_source_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar esta conexión', max_length=200, verbose_name='Nombre de la Conexión')),
                ('url', models.URLField(help_text='URL completa del servidor Odoo (ej: https://miodoo.com)', verbose_name='URL de Odoo')),
                ('port', models.IntegerField(default=8069, help_text='Puerto del servidor Odoo', verbose_name='Puerto')),
                ('database', models.CharField(help_text='Nombre de la base de datos en Odoo', max_length=200, verbose_name='Base de Datos')),
                ('username', models.CharField(help_text='Usuario de Odoo', max_length=200, verbose_name='Usuario')),
                ('password', models.CharField(help_text='Contraseña del usuario', max_length=200, verbose_name='Contraseña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Última prueba de conexión')),
                ('connection_status', models.CharField(choices=[('not_tested', 'No probada'), ('success', 'Exitosa'), ('failed', 'Fallida')], default='not_tested', max_length=50, verbose_name='Estado de Conexión')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odoo_connections', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Conexión Odoo',
                'verbose_name_plural': 'Conexiones Odoo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OdooRPCTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la tabla', max_length=200, verbose_name='Nombre Descriptivo')),
                ('odoo_model', models.CharField(help_text='Nombre del modelo en Odoo (ej: product.product, res.partner)', max_length=200, verbose_name='Modelo Odoo')),
                ('description', models.TextField(blank=True, help_text='Descripción de la tabla y su propósito', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_tables', to='tickets.odooconnection', verbose_name='Conexión')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odoo_rpc_tables', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tabla RPC Odoo',
                'verbose_name_plural': 'Tablas RPC Odoo',
                'ordering': ['name'],
                'unique_together': {('connection', 'odoo_model')},
            },
        ),
        migrations.CreateModel(
            name='OdooRPCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Datos en formato JSON para enviar a Odoo', verbose_name='Datos')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('success', 'Exitoso'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('odoo_id', models.IntegerField(blank=True, help_text='ID del registro creado en Odoo', null=True, verbose_name='ID en Odoo')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la sincronización falló', verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odoo_rpc_data', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='tickets.odoorpctable', verbose_name='Tabla')),
            ],
            options={
                'verbose_name': 'Dato RPC Odoo',
                'verbose_name_plural': 'Datos RPC Odoo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OdooRPCField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del campo', max_length=200, verbose_name='Nombre Descriptivo')),
                ('odoo_field_name', models.CharField(help_text='Nombre técnico del campo en Odoo (ej: name, default_code)', max_length=200, verbose_name='Nombre del Campo en Odoo')),
                ('field_type', models.CharField(choices=[('char', 'Texto'), ('text', 'Texto Largo'), ('integer', 'Entero'), ('float', 'Decimal'), ('boolean', 'Booleano'), ('date', 'Fecha'), ('datetime', 'Fecha y Hora'), ('selection', 'Selección'), ('many2one', 'Relación Many2One'), ('one2many', 'Relación One2Many'), ('many2many', 'Relación Many2Many')], default='char', max_length=50, verbose_name='Tipo de Campo')),
                ('is_required', models.BooleanField(default=False, help_text='Si el campo es obligatorio', verbose_name='Requerido')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en Excel', verbose_name='Orden')),
                ('help_text', models.TextField(blank=True, help_text='Instrucciones para llenar este campo', verbose_name='Texto de Ayuda')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.odoorpctable', verbose_name='Tabla')),
            ],
            options={
                'verbose_name': 'Campo RPC Odoo',
                'verbose_name_plural': 'Campos RPC Odoo',
                'ordering': ['table', 'order', 'name'],
                'unique_together': {('table', 'odoo_field_name')},
            },
        ),
    ]
