# Generated by Django 4.2.20 on 2025-11-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0346_odooconnection_odoorpctable_odoorpcdata_odoorpcfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoorpctable',
            name='public_url_enabled',
            field=models.BooleanField(default=False, help_text='Permite acceso público para importar datos', verbose_name='URL Pública Habilitada'),
        ),
        migrations.AddField(
            model_name='odoorpctable',
            name='public_url_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que expira el acceso público (opcional)', null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='odoorpctable',
            name='public_url_password',
            field=models.CharField(blank=True, help_text='Dejar en blanco para permitir acceso sin contraseña', max_length=128, verbose_name='Contraseña de URL Pública'),
        ),
        migrations.AddField(
            model_name='odoorpctable',
            name='public_url_token',
            field=models.CharField(blank=True, help_text='Token único para acceso público', max_length=64, null=True, unique=True, verbose_name='Token de URL Pública'),
        ),
        migrations.AlterField(
            model_name='odoorpcdata',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_data', to='tickets.odoorpctable', verbose_name='Tabla'),
        ),
        migrations.AlterField(
            model_name='odoorpcfield',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_fields', to='tickets.odoorpctable', verbose_name='Tabla'),
        ),
    ]
