# Generated by Django 4.2.20 on 2025-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0347_odoorpctable_public_url_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooconnection',
            name='public_portal_enabled',
            field=models.BooleanField(default=False, help_text='Permite acceso público a todas las tablas de esta conexión', verbose_name='Portal Público Habilitado'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_portal_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que expira el acceso al portal (opcional)', null=True, verbose_name='Fecha de Expiración del Portal'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_portal_password',
            field=models.CharField(blank=True, help_text='Dejar en blanco para permitir acceso sin contraseña', max_length=128, verbose_name='Contraseña del Portal'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_portal_token',
            field=models.CharField(blank=True, help_text='Token único para acceso al portal público', max_length=64, null=True, unique=True, verbose_name='Token del Portal Público'),
        ),
    ]
