# Generated by Django 4.2.20 on 2025-11-30 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0348_odooconnection_public_portal_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odoorpcdata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('fetched', 'Obtenido')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='OdooRPCImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='odoo_rpc_imports/%Y/%m/', verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('records_imported', models.IntegerField(default=0, verbose_name='Registros importados')),
                ('records_success', models.IntegerField(default=0, verbose_name='Registros exitosos')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Registros fallidos')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_files', to='tickets.odoorpctable', verbose_name='Tabla')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odoo_rpc_imports', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo de Importación RPC',
                'verbose_name_plural': 'Archivos de Importación RPC',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
