# Generated by Django 4.2.20 on 2025-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0349_alter_odoorpcdata_status_odoorpcimportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooconnection',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Si está marcada como privada, solo el usuario creador puede verla y usarla', verbose_name='Privada'),
        ),
    ]
