# Generated by Django 4.2.20 on 2025-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0350_add_is_private_to_odoo_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooconnection',
            name='public_portal_allow_import',
            field=models.BooleanField(default=True, help_text='Si está activo, los usuarios pueden importar datos. Si no, solo pueden descargar plantillas', verbose_name='Permitir Importación'),
        ),
    ]
