# Generated by Django 4.2.20 on 2025-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0351_add_public_portal_allow_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='odooconnection',
            name='public_operations_enabled',
            field=models.BooleanField(default=False, help_text='Permite acceso público al portal de operaciones RPC', verbose_name='Portal de Operaciones Público Habilitado'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_operations_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que expira el acceso al portal de operaciones (opcional)', null=True, verbose_name='Fecha de Expiración del Portal de Operaciones'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_operations_password',
            field=models.CharField(blank=True, help_text='Dejar en blanco para permitir acceso sin contraseña', max_length=128, verbose_name='Contraseña del Portal de Operaciones'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_operations_read_only',
            field=models.BooleanField(default=False, help_text='Si está activo, solo permite operaciones de búsqueda (no crear, actualizar o eliminar)', verbose_name='Portal de Operaciones Solo Lectura'),
        ),
        migrations.AddField(
            model_name='odooconnection',
            name='public_operations_token',
            field=models.CharField(blank=True, help_text='Token único para acceso al portal de operaciones RPC', max_length=64, null=True, unique=True, verbose_name='Token del Portal de Operaciones'),
        ),
    ]
