# Generated by Django 4.2.20 on 2025-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0352_add_public_operations_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoorpctable',
            name='public_form_enabled',
            field=models.BooleanField(default=False, help_text='Permite crear registros vía formulario público', verbose_name='Formulario Público Habilitado'),
        ),
        migrations.AddField(
            model_name='odoorpctable',
            name='public_form_expires_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que expira el formulario público (opcional)', null=True, verbose_name='Fecha de Expiración del Formulario'),
        ),
        migrations.AddField(
            model_name='odoorpctable',
            name='public_form_password',
            field=models.CharField(blank=True, help_text='Dejar en blanco para permitir acceso sin contraseña', max_length=128, verbose_name='Contraseña de Formulario Público'),
        ),
        migrations.AddField(
            model_name='odoorpctable',
            name='public_form_token',
            field=models.CharField(blank=True, help_text='Token único para formulario público', max_length=64, null=True, unique=True, verbose_name='Token de Formulario Público'),
        ),
    ]
