# Generated by Django 4.2.20 on 2025-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0353_add_public_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='public_share_enabled',
            field=models.BooleanField(default=False, verbose_name='Compartir Públicamente'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='public_share_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='public_share_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Contraseña de Acceso'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='public_share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de Compartir'),
        ),
    ]
