# Generated by Django 4.2.20 on 2025-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0354_add_public_share_to_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL del perfil de Facebook', max_length=500, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL del perfil de Instagram', max_length=500, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL del perfil de LinkedIn', max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='URL del perfil de TikTok', max_length=500, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='URL del perfil de Twitter/X', max_length=500, verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, help_text='Sitio web de la empresa o contacto', max_length=500, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL del canal de YouTube', max_length=500, verbose_name='YouTube'),
        ),
    ]
