# Generated by Django 4.2.20 on 2025-11-30 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0355_add_social_media_to_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Chatbot')),
                ('type', models.CharField(choices=[('internal', 'Interno (Solo esta web)'), ('external', 'Externo (Script integrable)')], default='internal', max_length=20, verbose_name='Tipo de Chatbot')),
                ('description', models.TextField(help_text='Describe el propósito del chatbot (ej: Agente de ventas que se dedica a captar leads)', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('use_ai', models.BooleanField(default=True, help_text='Habilitar asistencia de IA para respuestas no configuradas', verbose_name='Usar IA')),
                ('ai_context', models.TextField(blank=True, help_text='Información adicional para que la IA entienda el contexto del negocio', verbose_name='Contexto para IA')),
                ('welcome_message', models.TextField(default='¡Hola! ¿En qué puedo ayudarte?', verbose_name='Mensaje de bienvenida')),
                ('primary_color', models.CharField(default='#007bff', help_text='Color del botón y encabezado (formato: #RRGGBB)', max_length=7, verbose_name='Color primario')),
                ('position', models.CharField(choices=[('bottom-right', 'Inferior Derecha'), ('bottom-left', 'Inferior Izquierda')], default='bottom-right', max_length=20, verbose_name='Posición en pantalla')),
                ('script_token', models.CharField(blank=True, help_text='Token único para integración externa', max_length=64, unique=True, verbose_name='Token de script')),
                ('allowed_domains', models.TextField(blank=True, help_text='Dominios donde se puede integrar (uno por línea). Dejar vacío para permitir todos.', verbose_name='Dominios permitidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='Total de conversaciones')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total de mensajes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID de sesión')),
                ('user_email', models.EmailField(blank=True, help_text='Email capturado durante la conversación', max_length=254, verbose_name='Email del usuario')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del usuario')),
                ('user_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono del usuario')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de conversación')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('is_lead', models.BooleanField(default=False, help_text='Marcado si se capturó información de contacto', verbose_name='Es lead')),
                ('lead_quality', models.CharField(blank=True, choices=[('hot', 'Caliente'), ('warm', 'Tibio'), ('cold', 'Frío')], max_length=20, verbose_name='Calidad del lead')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tickets.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Conversación del Chatbot',
                'verbose_name_plural': 'Conversaciones del Chatbot',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Pregunta que el usuario puede hacer', max_length=500, verbose_name='Pregunta')),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas para detectar esta pregunta', max_length=500, verbose_name='Palabras clave')),
                ('answer', models.TextField(help_text='Respuesta que el chatbot dará', verbose_name='Respuesta')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en sugerencias', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('use_ai', models.BooleanField(default=False, help_text='La IA puede expandir o mejorar esta respuesta', verbose_name='Mejorar con IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('times_used', models.IntegerField(default=0, verbose_name='Veces utilizada')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tickets.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Pregunta del Chatbot',
                'verbose_name_plural': 'Preguntas del Chatbot',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(help_text='True si es mensaje del bot, False si es del usuario', verbose_name='Es del bot')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('used_ai', models.BooleanField(default=False, help_text='True si la respuesta fue generada por IA', verbose_name='Usó IA')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Hora del mensaje')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.chatbotconversation', verbose_name='Conversación')),
                ('matched_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_messages', to='tickets.chatbotquestion', verbose_name='Pregunta coincidente')),
            ],
            options={
                'verbose_name': 'Mensaje del Chatbot',
                'verbose_name_plural': 'Mensajes del Chatbot',
                'ordering': ['timestamp'],
            },
        ),
    ]
