# Generated by Django 4.2.20 on 2025-11-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0356_add_chatbot_models'),
    ]

    operations = [
    ]
