# Generated by Django 4.2.20 on 2025-11-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0357_generate_chatbot_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='bot_message_color',
            field=models.CharField(default='#f0f0f0', help_text='Color de fondo para los mensajes del bot (formato: #RRGGBB)', max_length=7, verbose_name='Color mensajes del bot'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='icon_choice',
            field=models.CharField(choices=[('chat', 'Chat (por defecto)'), ('robot', 'Robot'), ('headset', 'Auriculares'), ('person', 'Persona')], default='chat', help_text='Icono que se muestra en el botón flotante', max_length=20, verbose_name='Icono del botón'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='secondary_color',
            field=models.CharField(default='#0056b3', help_text='Color secundario para efectos hover (formato: #RRGGBB)', max_length=7, verbose_name='Color secundario'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='user_message_color',
            field=models.CharField(default='#007bff', help_text='Color de fondo para los mensajes del usuario (formato: #RRGGBB)', max_length=7, verbose_name='Color mensajes del usuario'),
        ),
    ]
