# Generated by Django 4.2.20 on 2025-11-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0358_chatbot_bot_message_color_chatbot_icon_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversation',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad detectada del usuario', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='country',
            field=models.CharField(blank=True, help_text='País detectado del usuario', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP del usuario en la sesión', null=True, verbose_name='Dirección IP'),
        ),
    ]
