# Generated by Django 4.2.20 on 2025-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0359_chatbotconversation_city_chatbotconversation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='response_delay',
            field=models.IntegerField(default=0, help_text='Segundos que espera el bot antes de responder (0 = inmediato)', verbose_name='Tiempo de espera (segundos)'),
        ),
    ]
