# Generated by Django 4.2.20 on 2025-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0360_chatbot_response_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversation',
            name='hide_chat',
            field=models.BooleanField(default=False, help_text='Si está marcado, el chat no se mostrará a este usuario', verbose_name='Ocultar chat'),
        ),
    ]
