# Generated by Django 4.2.20 on 2025-11-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0361_chatbot_conversation_hide_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversation',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Marca si la conversación ya fue revisada por un administrador', verbose_name='Revisada'),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisada por'),
        ),
    ]
