# Generated by Django 4.2.20 on 2025-11-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0362_chatbotconversation_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='total_clicks',
            field=models.IntegerField(default=0, help_text='Número de veces que han dado click para abrir el chat', verbose_name='Total de clicks en el botón'),
        ),
    ]
