# Generated by Django 4.2.20 on 2025-12-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0363_chatbot_total_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del click')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tickets.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Click del Chatbot',
                'verbose_name_plural': 'Clicks del Chatbot',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['chatbot', '-clicked_at'], name='tickets_cha_chatbot_f50904_idx')],
            },
        ),
    ]
