# Generated by Django 4.2.20 on 2025-12-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0364_chatbotclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(default='#6c757d', help_text='Color en formato hexadecimal (ej: #FF5733)', max_length=7, verbose_name='Color')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Etiqueta de Contacto',
                'verbose_name_plural': 'Etiquetas de Contacto',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas para categorizar este contacto', related_name='contacts', to='tickets.contacttag', verbose_name='Etiquetas'),
        ),
    ]
