# Generated by Django 4.2.20 on 2025-12-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0365_contacttag_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que se dirige la orden de trabajo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tickets.company', verbose_name='Empresa'),
        ),
    ]
