# Generated by Django 4.2.20 on 2025-12-02 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0366_make_workorder_company_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la plantilla', max_length=200, verbose_name='Título')),
                ('body', models.TextField(help_text='Contenido del correo electrónico', verbose_name='Cuerpo del mensaje')),
                ('category', models.CharField(choices=[('general', 'General'), ('ventas', 'Ventas'), ('soporte', 'Soporte'), ('marketing', 'Marketing'), ('seguimiento', 'Seguimiento'), ('recordatorio', 'Recordatorio')], default='general', max_length=50, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(default=1, help_text='Orden de visualización (menor número = mayor prioridad)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Correo',
                'verbose_name_plural': 'Plantillas de Correo',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('change_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo del cambio')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.emailtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Historial de Plantilla',
                'verbose_name_plural': 'Historiales de Plantillas',
                'ordering': ['-changed_at'],
            },
        ),
    ]
