# Generated by Django 4.2.20 on 2025-12-02 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0367_add_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre del contador', max_length=200, verbose_name='Título')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Valor del contador', max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(help_text='Fecha del contador', verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales (opcional)', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'ordering': ['-date', 'title'],
                'unique_together': {('title', 'date', 'user')},
            },
        ),
    ]
