# Generated by Django 4.2.20 on 2025-12-02 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0368_add_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número de la factura', max_length=100, verbose_name='Número de Factura')),
                ('supplier', models.CharField(help_text='Nombre del proveedor', max_length=200, verbose_name='Proveedor')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Importe total de la factura', max_digits=12, verbose_name='Importe')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scanned', 'Escaneado')], default='draft', max_length=20, verbose_name='Estado')),
                ('image', models.ImageField(help_text='Imagen escaneada de la factura', upload_to='invoices/%Y/%m/', verbose_name='Imagen de la factura')),
                ('json_data', models.JSONField(blank=True, help_text='Datos extraídos por OCR en formato JSON', null=True, verbose_name='Datos OCR')),
                ('public_token', models.CharField(help_text='Token para acceso público y API', max_length=100, unique=True, verbose_name='Token público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Factura OCR',
                'verbose_name_plural': 'Facturas OCR',
                'ordering': ['-created_at'],
            },
        ),
    ]
