# Generated by Django 4.2.20 on 2025-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0369_add_ocr_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrinvoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe total de la factura (se extrae automáticamente del OCR)', max_digits=12, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='ocrinvoice',
            name='number',
            field=models.CharField(blank=True, help_text='Número de la factura (se extrae automáticamente del OCR)', max_length=100, null=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='ocrinvoice',
            name='supplier',
            field=models.CharField(blank=True, help_text='Nombre del proveedor (se extrae automáticamente del OCR)', max_length=200, null=True, verbose_name='Proveedor'),
        ),
    ]
