# Generated by Django 4.2.20 on 2025-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0370_alter_ocrinvoice_amount_alter_ocrinvoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinvoice',
            name='impuesto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe del impuesto (IVA, etc.)', max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='ocrinvoice',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe neto sin impuestos', max_digits=12, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='ocrinvoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe total con impuestos', max_digits=12, verbose_name='Total'),
        ),
    ]
