# Generated by Django 4.2.20 on 2025-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0371_add_neto_impuesto_total_to_ocr_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinvoice',
            name='downloaded',
            field=models.BooleanField(default=False, help_text='Indica si la factura ha sido descargada vía API', verbose_name='Descargada'),
        ),
        migrations.AddField(
            model_name='ocrinvoice',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se descargó la factura por primera vez', null=True, verbose_name='Fecha de descarga'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_public_upload_enabled',
            field=models.BooleanField(default=True, help_text='Permite activar o desactivar el enlace público para que usuarios suban facturas', verbose_name='Habilitar enlace público para subir facturas'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='ocr_public_upload_token',
            field=models.CharField(blank=True, help_text='Token autogenerado para acceso a la API de listado de facturas', max_length=100, unique=True, verbose_name='Token del enlace público'),
        ),
    ]
