# Generated by Django 4.2.20 on 2025-12-02 21:22

from django.db import migrations, models


def generate_sequence_numbers(apps, schema_editor):
    """Generar números de secuencia únicos para registros existentes"""
    OCRInvoice = apps.get_model('tickets', 'OCRInvoice')
    for index, invoice in enumerate(OCRInvoice.objects.all().order_by('id'), start=1):
        invoice.sequence_number = f'OCR-{index:06d}'
        invoice.save(update_fields=['sequence_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0372_add_ocr_config_and_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinvoice',
            name='sequence_number',
            field=models.CharField(
                help_text='Número de secuencia interno autogenerado',
                max_length=50,
                null=True,
                blank=True,
                verbose_name='Número de Secuencia'
            ),
        ),
        migrations.RunPython(generate_sequence_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ocrinvoice',
            name='sequence_number',
            field=models.CharField(
                help_text='Número de secuencia interno autogenerado',
                max_length=50,
                unique=True,
                verbose_name='Número de Secuencia'
            ),
        ),
    ]
