# Generated by Django 4.2.20 on 2025-12-02 22:00

from django.db import migrations


def update_sequence_numbers(apps, schema_editor):
    """Actualizar números de secuencia a formato simple (1, 2, 3...)"""
    OCRInvoice = apps.get_model('tickets', 'OCRInvoice')
    for index, invoice in enumerate(OCRInvoice.objects.all().order_by('id'), start=1):
        invoice.sequence_number = str(index)
        invoice.save(update_fields=['sequence_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0373_ocrinvoice_sequence_number'),
    ]

    operations = [
        migrations.RunPython(update_sequence_numbers, migrations.RunPython.noop),
    ]
