# Generated by Django 4.2.20 on 2025-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0374_update_sequence_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrinvoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Borrador'),
                    ('scanned', 'Escaneado'),
                    ('downloaded', 'Descargada')
                ],
                default='draft',
                max_length=20,
                verbose_name='Estado'
            ),
        ),
    ]
