# Generated by Django 4.2.20 on 2025-12-03 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0375_alter_ocrinvoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor ingresado', max_digits=12, verbose_name='Valor')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre este cambio (opcional)', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.counter', verbose_name='Contador')),
                ('user', models.ForeignKey(help_text='Usuario que realizó el cambio', on_delete=django.db.models.deletion.CASCADE, related_name='counter_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Contador',
                'verbose_name_plural': 'Historiales de Contadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
