# Generated by Django 4.2.20 on 2025-12-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0376_counterhistory'),
    ]

    operations = [
    ]
