# Generated by Django 4.2.20 on 2025-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0377_add_counter_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_sales_kpi',
            field=models.BooleanField(default=False, help_text='Marcar si esta URL es parte del seguimiento de KPIs de ventas', verbose_name='KPI de Ventas'),
        ),
    ]
