# Generated by Django 4.2.20 on 2025-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0378_shorturl_is_sales_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='stage',
            field=models.CharField(blank=True, choices=[('stage_1', '1er contacto - Presentación, apertura'), ('stage_2', '2do contacto - Necesidades reales, diagnóstico'), ('stage_3', '3er contacto - Demo o propuesta inicial'), ('stage_4', '4to contacto - Ajustes, dudas, objeciones'), ('stage_5', '5to contacto - Negociación y cierre'), ('stage_6', '6to contacto - Negociación y cierre'), ('stage_7', '7mo contacto - Negociación y cierre'), ('stage_8', '8vo contacto - Negociación y cierre')], help_text='Etapa del proceso de ventas', max_length=10, null=True, verbose_name='Etapa'),
        ),
    ]
