# Generated by Django 4.2.20 on 2025-12-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0380_contactcomment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linked_company',
            field=models.ForeignKey(blank=True, help_text='Empresa creada a partir de este contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='tickets.company', verbose_name='Empresa vinculada'),
        ),
    ]
