# Generated by Django 4.2.20 on 2025-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0381_contact_linked_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de visitas'),
        ),
    ]
