# Generated by Django 4.2.20 on 2025-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0382_course_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='link_copy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces copiado el link'),
        ),
    ]
