# Generated by Django 4.2.20 on 2025-12-17 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0383_courseclass_link_copy_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('resuelto', 'Resuelto')], default='creado', max_length=20, verbose_name='Estado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.course', verbose_name='Curso')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Comentario de Curso',
                'verbose_name_plural': 'Comentarios de Cursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
