# Generated by Django 4.2.20 on 2025-12-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0385_alter_coursecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='solution_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de solución'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='solution_note',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de solución'),
        ),
    ]
