# Generated by Django 4.2.20 on 2025-12-17 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0386_coursecomment_solution_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('sad', '😞 Triste'), ('neutral', '😐 Neutro'), ('happy', '😊 Feliz')], max_length=10, verbose_name='Calificación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tickets.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Calificación de Curso',
                'verbose_name_plural': 'Calificaciones de Cursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
