# Generated by Django 4.2.20 on 2025-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0387_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_password',
            field=models.CharField(blank=True, help_text='Contraseña para acceder al curso (opcional)', max_length=100, verbose_name='Contraseña de acceso'),
        ),
        migrations.AddField(
            model_name='course',
            name='access_url',
            field=models.URLField(blank=True, help_text='URL donde se accede al curso (opcional)', max_length=500, verbose_name='URL de acceso'),
        ),
        migrations.AddField(
            model_name='course',
            name='access_username',
            field=models.CharField(blank=True, help_text='Usuario para acceder al curso (opcional)', max_length=100, verbose_name='Usuario de acceso'),
        ),
    ]
