# Generated by Django 4.2.20 on 2025-12-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0388_course_access_password_course_access_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='pendiente', max_length=20, verbose_name='Estado de aprobación'),
        ),
        migrations.AddField(
            model_name='course',
            name='approved_by_email',
            field=models.EmailField(blank=True, help_text='Correo de la persona que aprobó/desaprobó', max_length=254, verbose_name='Aprobado por (correo)'),
        ),
        migrations.AddField(
            model_name='course',
            name='approved_by_name',
            field=models.CharField(blank=True, help_text='Nombre de la persona que aprobó/desaprobó', max_length=200, verbose_name='Aprobado por (nombre)'),
        ),
    ]
