# Generated by Django 4.2.20 on 2025-12-17 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0389_course_approval_date_course_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], max_length=20, verbose_name='Estado')),
                ('approved_by_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('approved_by_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aprobación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tickets.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aprobación de Curso',
                'verbose_name_plural': 'Aprobaciones de Cursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
