# Generated by Django 4.2.20 on 2025-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0390_courseapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.UUIDField(blank=True, help_text='Token único para autenticación en la API REST', null=True, unique=True, verbose_name='Token de API'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_api_access',
            field=models.BooleanField(default=False, help_text='Permite que este usuario utilice la API REST del sistema', verbose_name='Habilitar acceso a la API'),
        ),
    ]
