# Generated by Django 4.2.20 on 2025-12-24 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0391_userprofile_api_token_userprofile_enable_api_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la política de privacidad', max_length=200, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(help_text='URL amigable (se genera automáticamente del título)', max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='Contenido completo de la política de privacidad', verbose_name='Contenido')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la política está activa y visible públicamente', verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_privacy_policies', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Política de Privacidad',
                'verbose_name_plural': 'Políticas de Privacidad',
                'ordering': ['-created_at'],
            },
        ),
    ]
