# Generated by Django 4.2.20 on 2026-01-07 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0392_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.CharField(blank=True, help_text='Formato: CS-YYYY-XX', max_length=20, verbose_name='Número de Secuencia')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de Firma'), ('signed', 'Firmado'), ('active', 'Activo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Frecuencia de Pago')),
                ('number_of_payments', models.IntegerField(default=12, verbose_name='Número de Cuotas')),
                ('public_token', models.CharField(blank=True, help_text='Token único para acceso público', max_length=64, unique=True, verbose_name='Token Público')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('signed_by_name', models.CharField(blank=True, max_length=200, verbose_name='Firmado por (Nombre)')),
                ('signed_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Firmado por (Email)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_contracts', to='tickets.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contrato de Soporte',
                'verbose_name_plural': 'Contratos de Soporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(verbose_name='Número de Cuota')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.supportcontract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pago de Contrato',
                'verbose_name_plural': 'Pagos de Contratos',
                'ordering': ['due_date', 'payment_number'],
            },
        ),
    ]
