# Generated by Django 4.2.20 on 2026-01-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0393_supportcontract_supportcontractpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontract',
            name='provider_company',
            field=models.ForeignKey(blank=True, help_text='Compañía que ofrece el servicio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_support_contracts', to='tickets.company', verbose_name='Compañía Proveedora'),
        ),
        migrations.AlterField(
            model_name='supportcontract',
            name='company',
            field=models.ForeignKey(help_text='Empresa cliente del servicio', on_delete=django.db.models.deletion.CASCADE, related_name='support_contracts', to='tickets.company', verbose_name='Cliente'),
        ),
    ]
