# Generated by Django 4.2.20 on 2026-01-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0394_supportcontract_provider_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(help_text='Número de factura (ej: FAC-2025-001)', max_length=50, unique=True, verbose_name='Secuencia/Número')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Factura')),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite de pago (opcional)', null=True, verbose_name='Fecha de Vencimiento')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios adicionales', verbose_name='Notas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('company', models.ForeignKey(help_text='Empresa a la que se factura', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tickets.company', verbose_name='Cliente/Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Factura de 3ros',
                'verbose_name_plural': 'Facturas de 3ros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional del producto/servicio', verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de impuesto (ej: 21 para IVA 21%)', max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuestos')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Línea')),
                ('line_number', models.IntegerField(default=1, verbose_name='Número de Línea')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tickets.invoice', verbose_name='Factura')),
                ('product', models.ForeignKey(help_text='Producto o servicio facturado', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='tickets.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
                'ordering': ['line_number'],
            },
        ),
    ]
