# Generated by Django 4.2.20 on 2026-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0395_invoice_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar Americano ($)'), ('GBP', 'Libra Esterlina (£)'), ('JPY', 'Yen Japonés (¥)'), ('CAD', 'Dólar Canadiense (C$)'), ('AUD', 'Dólar Australiano (A$)'), ('CHF', 'Franco Suizo (CHF)'), ('CNY', 'Yuan Chino (¥)'), ('MXN', 'Peso Mexicano ($)'), ('COP', 'Peso Colombiano ($)')], default='USD', help_text='Moneda en la que se factura', max_length=10, verbose_name='Moneda'),
        ),
    ]
