# Generated by Django 4.2.20 on 2026-01-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0396_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invoice_next_number',
            field=models.IntegerField(default=1, help_text='Próximo número secuencial para la factura', verbose_name='Próximo Número de Factura'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_sequence_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefijo para la secuencia de facturas (ej: MCVARQ/2025/)', max_length=50, verbose_name='Prefijo de Secuencia de Factura'),
        ),
    ]
