# Generated by Django 4.2.20 on 2026-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0397_userprofile_invoice_next_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='footer_message',
            field=models.TextField(blank=True, help_text='Mensaje que aparecerá al final de la factura (condiciones de pago, términos, etc.)', verbose_name='Mensaje al pie'),
        ),
    ]
