# Generated by Django 4.2.20 on 2026-01-10 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0398_invoice_footer_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensaje o comentario sobre la factura', verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.invoice', verbose_name='Factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje de Factura',
                'verbose_name_plural': 'Mensajes de Facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
