# Generated by Django 4.2.20 on 2026-02-26 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0399_invoicemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('source_name', models.CharField(help_text='Ej: BBVA, efectivo, tarjeta corporativa…', max_length=100, verbose_name='Fuente / Banco')),
                ('source_type', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('corporate_card', 'Tarjeta Corporativa'), ('advance', 'Anticipo de Viaje'), ('other', 'Otro')], default='bank_transfer', max_length=20, verbose_name='Tipo de fuente')),
                ('invoice_reference', models.CharField(blank=True, help_text='Número de factura, transferencia o comprobante', max_length=200, null=True, verbose_name='Referencia de factura / comprobante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('received_at', models.DateField(verbose_name='Fecha de recepción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='tickets.expensereport', verbose_name='Rendición de gastos')),
            ],
            options={
                'verbose_name': 'Fondo de Rendición',
                'verbose_name_plural': 'Fondos de Rendición',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
