# Generated by Django 4.2.20 on 2026-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0400_add_expense_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_see_all_contacts',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario puede ver todos los contactos. Si no, solo ve los que creó o tiene asignados.', verbose_name='Ver todos los contactos'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='category',
            field=models.CharField(choices=[('food', 'Comida'), ('transport', 'Transporte'), ('hotel', 'Hotel/Alojamiento'), ('fuel', 'Combustible'), ('materials', 'Materiales'), ('entertainment', 'Entretenimiento'), ('communication', 'Comunicaciones'), ('office', 'Oficina/Suministros'), ('medical', 'Gastos médicos'), ('training', 'Capacitación'), ('direct_salary', 'Salarios Directos'), ('indirect_salary', 'Salarios Indirectos'), ('asset_purchase', 'Compra de Activos'), ('marketing', 'Marketing'), ('software', 'Software'), ('other', 'Otros')], max_length=20, verbose_name='Categoría'),
        ),
    ]
