# Generated by Django 4.2.20 on 2026-02-26 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0401_add_can_see_all_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHourLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción de la tarea o actividad realizada', max_length=300, verbose_name='Descripción')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Cantidad de horas trabajadas en esta actividad', max_digits=6, verbose_name='Horas')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_hour_lines', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_lines', to='tickets.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_hour_lines', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Línea de Horas',
                'verbose_name_plural': 'Líneas de Horas',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
