# Generated by Django 4.2.20 on 2026-04-16 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0403_add_manual_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de acceso')),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Accedido por')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tickets.manual', verbose_name='Manual')),
            ],
            options={
                'verbose_name': 'Acceso a Manual',
                'verbose_name_plural': 'Accesos a Manuales',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
