# Generated by Django 4.2.20 on 2026-04-18 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0405_rfi_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado'),
        ),
    ]
