# Generated by Django 4.2.20 on 2026-04-18 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0406_rfi_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.rfi', verbose_name='RFI')),
            ],
            options={
                'verbose_name': 'Comentario RFI',
                'verbose_name_plural': 'Comentarios RFI',
                'ordering': ['created_at'],
            },
        ),
    ]
