# Generated by Django 4.2.20 on 2026-04-18 18:18

from django.db import migrations, models


def populate_rfi_codes(apps, schema_editor):
    RFI = apps.get_model('tickets', 'RFI')
    for i, rfi in enumerate(RFI.objects.order_by('id'), start=1):
        rfi.code = f"RF{i:05d}"
        rfi.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0407_rfi_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código'),
        ),
        migrations.RunPython(populate_rfi_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rfi',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
