# Generated by Django 4.2.20 on 2026-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0408_rfi_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
    ]
