# Generated by Django 4.2.20 on 2026-04-18 18:32

from django.db import migrations, models
import uuid


def populate_public_tokens(apps, schema_editor):
    RFI = apps.get_model('tickets', 'RFI')
    for rfi in RFI.objects.all():
        rfi.public_token = uuid.uuid4()
        rfi.save(update_fields=['public_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0409_rfi_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='public_token',
            field=models.UUIDField(null=True, editable=False, verbose_name='Token público'),
        ),
        migrations.RunPython(populate_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rfi',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público'),
        ),
    ]
