# Generated by Django 4.2.20 on 2026-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0410_rfi_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rficomment',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo (invitado)'),
        ),
        migrations.AddField(
            model_name='rficomment',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre (invitado)'),
        ),
    ]
