# Generated by Django 4.2.20 on 2026-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0411_rfi_comment_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='commit',
            field=models.CharField(blank=True, default='', help_text='Hash, URL o referencia del commit relacionado', max_length=500, verbose_name='Commit'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calificación del ticket de 1 a 5 estrellas', null=True, verbose_name='Calificación'),
        ),
    ]
