# Generated by Django 4.2.20 on 2026-04-18 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0412_ticket_commit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Comentario generado automáticamente por el sistema', verbose_name='Mensaje del sistema'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('working', 'Trabajando'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
