# Generated by Django 4.2.20 on 2026-04-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0413_ticket_working_status_system_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción general del proyecto', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('on_hold', 'En Pausa'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre estimada')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de compartir')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por coma', max_length=300, verbose_name='Etiquetas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_books', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_books', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_books', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Libro de Proyecto',
                'verbose_name_plural': 'Libros de Proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('is_agent_entry', models.BooleanField(default=False, help_text='Indica si fue escrita por un agente', verbose_name='Entrada de agente')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_book_attachments/%Y/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_book_entries', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tickets.projectbook', verbose_name='Libro de Proyecto')),
            ],
            options={
                'verbose_name': 'Entrada de Libro de Proyecto',
                'verbose_name_plural': 'Entradas de Libros de Proyecto',
                'ordering': ['created_at'],
            },
        ),
    ]
