# Generated by Django 4.2.20 on 2026-04-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0414_project_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('temas', models.TextField(blank=True, help_text='Descripción general de los temas que cubre la capacitación', verbose_name='Temas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('assigned_companies', models.ManyToManyField(blank=True, related_name='capacitaciones_asignadas', to='tickets.company', verbose_name='Empresas asignadas')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='capacitaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asignados')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacitacionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tarea', models.CharField(max_length=500, verbose_name='Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tickets.capacitacion', verbose_name='Capacitación')),
            ],
            options={
                'verbose_name': 'Línea de Capacitación',
                'verbose_name_plural': 'Líneas de Capacitación',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacitacionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('enlace', models.URLField(verbose_name='Enlace / URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tickets.capacitacionlinea', verbose_name='Línea')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitacion_respuestas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Respuesta de Capacitación',
                'verbose_name_plural': 'Respuestas de Capacitación',
                'ordering': ['created_at'],
            },
        ),
    ]
