# Generated by Django 4.2.20 on 2026-04-20 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0415_capacitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público'),
        ),
    ]
