# Generated by Django 4.2.20 on 2026-05-03 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0416_capacitacion_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='error_401',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario no podrá iniciar sesión y verá un mensaje de error 401', verbose_name='Error 401'),
        ),
        migrations.CreateModel(
            name='BlockedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del intento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='Agente de usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de login bloqueado',
                'verbose_name_plural': 'Intentos de login bloqueados',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
