# Generated by Django 4.2.20 on 2026-05-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0417_add_error_401_blocked_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
    ]
