# Generated by Django 4.2.20 on 2026-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0418_checklist_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='public_can_toggle',
            field=models.BooleanField(default=True, verbose_name='Permitir marcar tareas públicamente'),
        ),
    ]
