# Generated by Django 4.2.20 on 2026-05-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0419_checklist_public_can_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='Enlace URL'),
        ),
    ]
