# Generated by Django 4.2.20 on 2026-05-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0420_checklistitem_notes_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Catálogo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Catálogo de Apps',
                'verbose_name_plural': 'Catálogos de Apps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppCatalogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tickets.appcatalog', verbose_name='Catálogo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_lines', to='tickets.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Línea de Catálogo',
                'verbose_name_plural': 'Líneas de Catálogo',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
