# Generated by Django 4.2.20 on 2026-05-10 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0421_appcatalog_appcatalogline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('url', models.URLField(max_length=500, verbose_name='URL del Video')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tickets.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Video de Producto',
                'verbose_name_plural': 'Videos de Producto',
                'ordering': ['created_at'],
            },
        ),
    ]
