# Generated by Django 4.2.20 on 2026-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0422_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcatalog',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si está marcado, aparecerá en la página pública de catálogos', verbose_name='Público'),
        ),
    ]
