# Generated by Django 4.2.20 on 2026-05-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0423_appcatalog_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si está marcado, este producto podrá verse en los catálogos públicos', verbose_name='Visible en catálogo público'),
        ),
    ]
