# Generated by Django 4.2.20 on 2026-05-10 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0425_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Número de cotización, ej: COT-2026-001', max_length=20, unique=True, verbose_name='Referencia')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('customer_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Cotización de Carrito',
                'verbose_name_plural': 'Cotizaciones de Carrito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.product', verbose_name='Producto')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.cartquotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Línea de Cotización',
                'verbose_name_plural': 'Líneas de Cotización',
            },
        ),
    ]
