# Generated by Django 4.2.20 on 2026-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0426_cart_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcatalog',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas del catálogo'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas del producto'),
        ),
    ]
