# Generated by Django 4.2.20 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0427_view_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Correo al que los clientes deben enviar el comprobante de pago', max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Nombre que aparece en la página de cotización para enviar comprobante de pago', max_length=150, verbose_name='Nombre de contacto'),
        ),
    ]
