# Generated by Django 4.2.20 on 2026-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0428_system_config_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='paypal_payment_email',
            field=models.EmailField(blank=True, default='', help_text='Cuenta de PayPal a la que los clientes pueden enviar el pago de su cotización', max_length=254, verbose_name='Email de PayPal para pagos'),
        ),
    ]
