# Generated by Django 4.2.20 on 2026-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0429_system_config_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='forma_trabajo_url',
            field=models.URLField(blank=True, default='', help_text='Enlace al documento o página que describe tu forma de trabajo (se mostrará en el formulario ¿Quién eres?)', verbose_name='URL Forma de trabajo'),
        ),
    ]
