# Generated by Django 4.2.20 on 2026-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0430_system_config_forma_trabajo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_name',
            field=models.CharField(blank=True, help_text='Nombre técnico o código interno del producto', max_length=200, verbose_name='Nombre Técnico'),
        ),
    ]
