# Generated by Django 4.2.20 on 2026-05-15 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0431_add_technical_name_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_surveys', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_surveys_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Levantamiento de Procesos',
                'verbose_name_plural': 'Levantamientos de Procesos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSurveyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Línea de Levantamiento',
                'verbose_name_plural': 'Líneas de Levantamiento',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
