# Generated by Django 4.2.20 on 2026-05-15 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0432_process_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público'),
        ),
    ]
