# Generated by Django 4.2.20 on 2026-05-15 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0433_process_survey_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyLineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('body', models.TextField(blank=True, verbose_name='Comentario')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='process_survey_attachments/%Y/%m/', verbose_name='Adjunto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.processsurveyline', verbose_name='Línea')),
            ],
            options={
                'verbose_name': 'Comentario de Línea',
                'verbose_name_plural': 'Comentarios de Línea',
                'ordering': ['created_at'],
            },
        ),
    ]
