# Generated by Django 4.2.20 on 2026-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0434_process_survey_line_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurveyline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
