# Generated by Django 4.2.20 on 2026-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0435_process_survey_line_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del proyecto'),
        ),
    ]
