# Generated by Django 4.2.20 on 2026-05-15 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0436_process_survey_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('signer_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('signature_data', models.TextField(verbose_name='Firma (base64)')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Firmado el')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
                'ordering': ['signed_at'],
            },
        ),
    ]
