# Generated by Django 4.2.20 on 2026-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0437_process_survey_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='folio',
            field=models.CharField(blank=True, help_text='Generado automáticamente. Formato: LP-0001', max_length=20, unique=True, verbose_name='Folio'),
        ),
    ]
