# Generated by Django 4.2.20 on 2026-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0439_process_survey_page_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurveyline',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Oculto en vista pública'),
        ),
    ]
