# Generated by Django 4.2.20 on 2026-05-18 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0442_process_survey_line_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_surveys_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
