# Generated by Django 4.2.20 on 2026-05-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0443_process_survey_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nombre descriptivo del enlace', max_length=300, verbose_name='Etiqueta')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'URL de Levantamiento',
                'verbose_name_plural': 'URLs de Levantamiento',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
