# Generated by Django 4.2.20 on 2026-05-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0444_process_survey_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='source_survey_line',
            field=models.ForeignKey(blank=True, help_text='Línea de levantamiento de procesos a partir de la cual se generó este ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.processsurveyline', verbose_name='Línea de levantamiento origen'),
        ),
    ]
