# Generated by Django 4.2.20 on 2026-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0445_ticket_source_survey_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='requester_company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa del solicitante'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='requester_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País del solicitante'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del solicitante'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='requester_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del solicitante'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono del solicitante'),
        ),
    ]
