# Generated by Django 4.2.20 on 2026-05-18 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0446_processsurvey_requester_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Versión analizada')),
                ('total_lines', models.PositiveSmallIntegerField(default=0, verbose_name='Total de procesos')),
                ('analysis_text', models.TextField(verbose_name='Análisis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Análisis IA de Levantamiento',
                'verbose_name_plural': 'Análisis IA de Levantamientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
