# Generated by Django 4.2.20 on 2026-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0447_processsurvey_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='status',
            field=models.CharField(choices=[('proceso', 'En proceso'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='proceso', max_length=20, verbose_name='Estado'),
        ),
    ]
