# Generated by Django 4.2.20 on 2026-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0448_add_status_to_processsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurveypageview',
            name='status_at_view',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Estado al momento de la visita'),
        ),
    ]
