# Generated by Django 4.2.20 on 2026-05-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0449_add_status_at_view_to_processsurvey_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
    ]
