# Generated by Django 4.2.20 on 2026-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0450_add_rejection_reason_to_processsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='importe_currency',
            field=models.CharField(blank=True, default='USD', max_length=10, verbose_name='Moneda'),
        ),
    ]
