# Generated by Django 4.2.20 on 2026-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0451_add_importe_to_processsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='contract_text',
            field=models.TextField(blank=True, help_text='Texto libre del contrato asociado a este levantamiento', verbose_name='Contrato'),
        ),
    ]
