# Generated by Django 4.2.20 on 2026-06-13 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0452_processsurvey_contract_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processsurvey',
            name='contract_text',
        ),
        migrations.CreateModel(
            name='ProcessSurveyClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(blank=True, help_text='Ej: Objeto del contrato, Vigencia, Confidencialidad…', max_length=300, verbose_name='Título de la cláusula')),
                ('body', models.TextField(verbose_name='Texto de la cláusula')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Cláusula',
                'verbose_name_plural': 'Cláusulas',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
