# Generated by Django 4.2.20 on 2026-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0453_processsurvey_clauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del contrato'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='contract_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Título del contrato'),
        ),
    ]
