# Generated by Django 4.2.20 on 2026-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0454_processsurvey_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Imagen de la firma que se usará en contratos y documentos', null=True, upload_to='user_signatures/', verbose_name='Firma digital'),
        ),
    ]
