# Generated by Django 4.2.20 on 2026-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0455_userprofile_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='client_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='contract_client_signatures/', verbose_name='Firma del cliente'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma del cliente'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='client_signed_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del firmante (cliente)'),
        ),
    ]
