# Generated by Django 4.2.20 on 2026-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0456_processsurvey_client_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='client_rep_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID/NUE del representante cliente'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='client_rep_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del representante cliente'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='client_rep_role',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo del representante cliente'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='provider_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Domicilio del proveedor'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='provider_civil_status',
            field=models.CharField(blank=True, max_length=80, verbose_name='Estado civil del proveedor'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='provider_nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad del proveedor'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='provider_nif',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIF/DNI/Pasaporte del proveedor'),
        ),
        migrations.AddField(
            model_name='processsurvey',
            name='provider_occupation',
            field=models.CharField(blank=True, default='Autónomo', max_length=100, verbose_name='Ocupación del proveedor'),
        ),
    ]
