# Generated by Django 4.2.20 on 2026-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0457_processsurvey_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='client_signed_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del firmante (cliente)'),
        ),
    ]
