# Generated by Django 4.2.20 on 2026-06-13 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0458_processsurvey_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyContractView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Dispositivo')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_views', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Apertura de contrato',
                'verbose_name_plural': 'Aperturas de contrato',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
