# Generated by Django 4.2.20 on 2026-06-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0459_processsurvey_contract_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='is_public_contract',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el enlace público no permite ver ni firmar el contrato.', verbose_name='Contrato público'),
        ),
        migrations.AddField(
            model_name='processsurveyclause',
            name='is_hidden_public',
            field=models.BooleanField(default=False, help_text='Si está activado, esta cláusula aparece borrosa en el contrato público.', verbose_name='No visible en público'),
        ),
    ]
