# Generated by Django 4.2.20 on 2026-06-13 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0460_contract_public_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyContractVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de acceso')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_visitors', to='tickets.processsurvey', verbose_name='Levantamiento')),
            ],
            options={
                'verbose_name': 'Visitante de contrato',
                'verbose_name_plural': 'Visitantes de contrato',
                'ordering': ['-created_at'],
            },
        ),
    ]
