# Generated by Django 4.2.20 on 2026-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0461_contract_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurveyclause',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
