# Generated by Django 4.2.20 on 2026-06-16 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0462_add_updated_at_to_clause'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyClauseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_before', models.TextField(verbose_name='Texto anterior')),
                ('body_after', models.TextField(verbose_name='Texto nuevo')),
                ('edited_by_name', models.CharField(blank=True, max_length=200, verbose_name='Editado por')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de edición')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.processsurveyclause', verbose_name='Cláusula')),
            ],
            options={
                'verbose_name': 'Historial de cláusula',
                'verbose_name_plural': 'Historial de cláusulas',
                'ordering': ['-edited_at'],
            },
        ),
    ]
