# Generated by Django 4.2.20 on 2026-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0463_add_clause_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsurvey',
            name='contract_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento del contrato'),
        ),
    ]
