# Generated by Django 4.2.20 on 2026-06-17 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0464_processsurvey_contract_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSurveyLineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(default='#6c757d', help_text='Color en formato hexadecimal, ej: #0d6efd', max_length=20, verbose_name='Color')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_line_categories', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Categoría de Línea',
                'verbose_name_plural': 'Categorías de Línea',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='processsurveyline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='tickets.processsurveylinecategory', verbose_name='Categoría'),
        ),
    ]
