# Generated by Django 4.2.20 on 2026-06-30 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0465_add_process_survey_line_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('folio', models.CharField(blank=True, help_text='Generado automáticamente. Formato: PI-0001', max_length=20, unique=True, verbose_name='Folio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_infos', to='tickets.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_infos_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Información de Proyecto',
                'verbose_name_plural': 'Información de Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInfoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Texto')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_info_lines', to='tickets.processsurveylinecategory', verbose_name='Categoría')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tickets.projectinfo', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Línea de Proyecto',
                'verbose_name_plural': 'Líneas de Proyecto',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
