# Generated by Django 4.2.20 on 2026-06-30 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0466_add_project_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público'),
        ),
    ]
