# Generated by Django 4.2.20 on 2026-06-30 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0467_add_project_info_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfoVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Apertura')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tickets.projectinfo', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Visita Pública',
                'verbose_name_plural': 'Visitas Públicas',
                'ordering': ['-visited_at'],
            },
        ),
    ]
