# Generated by Django 4.2.20 on 2026-06-30 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0468_add_project_info_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del proyecto'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='pin',
            field=models.CharField(blank=True, help_text='Si se establece, la vista pública solicitará este PIN.', max_length=20, verbose_name='PIN de acceso'),
        ),
        migrations.AddField(
            model_name='projectinfoline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='projectinfoline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.CreateModel(
            name='ProjectInfoResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_override', models.CharField(blank=True, max_length=150, verbose_name='Cargo (sobreescribe perfil)')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='tickets.projectinfo', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_info_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Responsable de Proyecto',
                'verbose_name_plural': 'Responsables de Proyecto',
                'ordering': ['added_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
