# Generated by Django 4.2.20 on 2026-06-30 08:59

from django.db import migrations, models
import uuid


def gen_unique_tokens(apps, schema_editor):
    ProjectInfoLine = apps.get_model('tickets', 'ProjectInfoLine')
    for line in ProjectInfoLine.objects.all():
        line.public_share_token = uuid.uuid4()
        line.save(update_fields=['public_share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0469_project_info_extras'),
    ]

    operations = [
        # Paso 1: añadir sin restricción UNIQUE
        migrations.AddField(
            model_name='projectinfoline',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token público de línea'),
        ),
        # Paso 2: rellenar con UUIDs únicos en filas existentes
        migrations.RunPython(gen_unique_tokens, migrations.RunPython.noop),
        # Paso 3: aplicar la restricción UNIQUE
        migrations.AlterField(
            model_name='projectinfoline',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público de línea'),
        ),
    ]
