# Generated by Django 4.2.20 on 2026-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0471_pi_line_comments_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Es Spam'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Motivo de Spam'),
        ),
    ]
