# Generated by Django 4.2.20 on 2026-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0472_add_spam_fields_to_landing_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('nie', 'NIE'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='dni', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('que_hara', models.TextField(verbose_name='¿Qué hará?')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Registro de Entrada',
                'verbose_name_plural': 'Registros de Entrada',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
