# Generated by Django 4.2.20 on 2026-08-15 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0473_add_registro_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntradaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token Público')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Registro de Entrada',
                'verbose_name_plural': 'Configuración Registro de Entrada',
            },
        ),
    ]
