# Generated by Django 4.2.20 on 2026-08-31 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0474_add_registro_entrada_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_info_links_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.projectinfo', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Enlace de Proyecto',
                'verbose_name_plural': 'Enlaces de Proyecto',
                'ordering': ['-created_at'],
            },
        ),
    ]
