# Generated by Django 4.2.20 on 2026-08-31 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0475_add_project_info_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfolink',
            name='public_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público de enlace'),
        ),
    ]
