# Generated by Django 4.2.20 on 2026-09-03 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0477_add_project_info_link_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace / URL')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='tickets.capacitacion', verbose_name='Capacitación')),
            ],
            options={
                'verbose_name': 'Clase de Capacitación',
                'verbose_name_plural': 'Clases de Capacitación',
                'ordering': ['orden', 'fecha', 'created_at'],
            },
        ),
    ]
