# Generated by Django 4.2.20 on 2026-09-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0478_capacitacionclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacionlinea',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tickets.capacitacionclase', verbose_name='Clase'),
        ),
    ]
