# Generated by Django 4.2.20 on 2026-09-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0479_capacitacionlinea_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tickets.capacitacionclase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Asistencia a Clase',
                'verbose_name_plural': 'Asistencias a Clases',
                'ordering': ['nombre'],
            },
        ),
    ]
