# Generated by Django 4.2.20 on 2026-09-03 08:52

import uuid

from django.db import migrations, models
import django.db.models.deletion


def backfill_public_tokens(apps, schema_editor):
    CapacitacionClase = apps.get_model('tickets', 'CapacitacionClase')
    for clase in CapacitacionClase.objects.all():
        clase.public_token = uuid.uuid4()
        clase.save(update_fields=['public_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0480_capacitacionasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacionclase',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=False, verbose_name='Token público'),
        ),
        migrations.RunPython(backfill_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='capacitacionclase',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público'),
        ),
        migrations.CreateModel(
            name='CapacitacionSolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(verbose_name='Cambio solicitado')),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='tickets.capacitacionclase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Clase',
                'verbose_name_plural': 'Solicitudes de Cambio de Clase',
                'ordering': ['-created_at'],
            },
        ),
    ]
