# Generated by Django 4.2.20 on 2026-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0481_capacitacionclase_public_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacionclase',
            name='resumen',
            field=models.TextField(blank=True, verbose_name='Resumen de la clase'),
        ),
    ]
