# Generated by Django 4.2.20 on 2026-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0482_capacitacionclase_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacionlinea',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
