# Generated by Django 4.2.20 on 2026-09-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0483_capacitacionlinea_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('contrasena', models.CharField(blank=True, max_length=150, verbose_name='Contraseña')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='tickets.capacitacion', verbose_name='Capacitación')),
            ],
            options={
                'verbose_name': 'Enlace de Capacitación',
                'verbose_name_plural': 'Enlaces de Capacitación',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
