# Generated by Django 4.2.20 on 2026-09-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0484_capacitacionenlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionClaseReaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='tickets.capacitacionclase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Reacción a Clase',
                'verbose_name_plural': 'Reacciones a Clases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacitacionClaseComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.capacitacionclase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Comentario de Clase',
                'verbose_name_plural': 'Comentarios de Clase',
                'ordering': ['-created_at'],
            },
        ),
    ]
