# Generated by Django 4.2.20 on 2026-09-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0485_capacitacionclasereaccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la API', max_length=200, verbose_name='Nombre')),
                ('value', models.BooleanField(choices=[(True, 'Verdadero'), (False, 'Falso')], default=True, help_text='Valor booleano que devolverá la API', verbose_name='Valor')),
                ('text', models.TextField(blank=True, help_text='Contenido de texto largo que devolverá la API', verbose_name='Texto')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivada, la API dejará de responder', verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_api_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'APIs',
                'ordering': ['-created_at'],
            },
        ),
    ]
